---
sidebar: sidebar 
permalink: hu-aix-73.html 
keywords: Host Utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Descreve como usar o IBM AIX 7.3 e/ou PowerVM VIOS 4.x com o ONTAP 
---
= Configurar AIX 7.3/VIOS 4.x para FCP e iSCSI com armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O software AIX Host Utilities fornece ferramentas de gerenciamento e diagnóstico para hosts AIX conectados ao armazenamento ONTAP .  Ao instalar o AIX Host Utilities em um host AIX 7.3/VIOS 4.x, você pode usá-lo para ajudar a gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP .



== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.  Se sua configuração não suportar inicialização SAN, você poderá usar uma inicialização local.

[role="tabbed-block"]
====
.Inicialização de SAN
--
A inicialização SAN é o processo de configuração de um disco conectado à SAN (um LUN) como um dispositivo de inicialização para um host AIX/PowerVM.  Você pode configurar um LUN de inicialização SAN para funcionar em um ambiente AIX Multipath I/O (MPIO) que esteja usando o protocolo FC e executando o AIX Host Utilities com o protocolo FC ou FCoE.  O método usado para criar um LUN de inicialização SAN e instalar uma nova imagem de sistema operacional em um ambiente AIX MPIO depende do protocolo que você está usando.

.Passos
. Use olink:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o seu sistema operacional AIX, protocolo e versão do ONTAP oferecem suporte à inicialização SAN.
. Siga as práticas recomendadas para configurar uma inicialização SAN na documentação do fornecedor.


--
.Arranque local
--
Execute uma inicialização local instalando o sistema operacional AIX no disco rígido local, por exemplo, em um SSD, SATA ou RAID.

--
====


== Etapa 2: instalar os utilitários do host AIX

A NetApp recomenda fortemente a instalação do AIX Host Utilities para dar suporte ao gerenciamento de LUN do ONTAP e auxiliar o suporte técnico na coleta de dados de configuração.  O pacote MPIO do Host Utilities fornece suporte MPIO para AIX e VIOS.


NOTE: A instalação do AIX Host Utilities fornece configurações de tempo limite adicionais no seu host AIX.

link:hu-aix-80.html["Instalar o AIX Host Utilities 8.0"] .



== Etapa 3: Confirme a configuração multipath do seu host

Você pode usar multipathing com AIX e PowerVM para gerenciar LUNs ONTAP .

O multipathing permite que você configure vários caminhos de rede entre o host e o sistema de armazenamento.  Se um caminho falhar, o tráfego continua com os caminhos restantes.  Os ambientes AIX e PowerVM dos utilitários de host usam a solução de multicaminhos nativa (MPIO) do AIX.

O Path Control Module (PCM) é responsável por controlar vários caminhos para um host AIX.  O PCM é um código fornecido pelo fornecedor de armazenamento que lida com o gerenciamento de caminhos e é instalado e habilitado durante a instalação dos Utilitários do Host.

Para garantir que o multipathing esteja configurado corretamente para seu host, verifique se você tem as configurações recomendadas da NetApp configuradas para seus LUNs ONTAP .

.Passos
. Verifique se "MPIO NetApp" está disponível.  "MPIO NetApp" é carregado durante a instalação do AIX Host Utilities e fica disponível após a reinicialização do host.
+
[source, cli]
----
lsdev -Cc disk
----
+
.Exemplo de saída
`hdisk1  Available 00-00-02 MPIO NetApp FCP Default PCM Disk`

. Os utilitários de host do AIX carregam as seguintes configurações de parâmetros para LUNs ONTAP .
+
.Mostrar definições de parâmetros
[%collapsible]
====
[cols="4*"]
|===
| Parâmetro | Ambiente | Valor para AIX | Nota 


| algoritmo | MPIO | round_robin | Definido por Host Utilities (Utilitários do anfitrião) 


| hcheck_cmd | MPIO | inquérito | Definido por Host Utilities (Utilitários do anfitrião) 


| hcheck_interval | MPIO | 30 | Definido por Host Utilities (Utilitários do anfitrião) 


| hcheck_mode | MPIO | não ativo | Definido por Host Utilities (Utilitários do anfitrião) 


| lun_reset_spt | MPIO / não MPIO | sim | Definido por Host Utilities (Utilitários do anfitrião) 


| max_transfer | MPIO / não MPIO | FC LUNs: 0x100000 bytes | Definido por Host Utilities (Utilitários do anfitrião) 


| qfull_dly | MPIO / não MPIO | atraso de 2 segundos | Definido por Host Utilities (Utilitários do anfitrião) 


| queue_depth | MPIO / não MPIO | 64 | Definido por Host Utilities (Utilitários do anfitrião) 


| reserve_policy | MPIO / não MPIO | no_reserve | Definido por Host Utilities (Utilitários do anfitrião) 


| re_timeout (disco) | MPIO / não MPIO | 30 segundos | Usa os valores padrão do SO 


| dyntrk | MPIO / não MPIO | Sim | Usa os valores padrão do SO 


| fc_err_recov | MPIO / não MPIO | FAIL_FAIL | Usa os valores padrão do SO 


| q_type | MPIO / não MPIO | simples | Usa os valores padrão do SO 


| num_cmd_elems | MPIO / não MPIO | 1024 para AIX 3072 para VIOS | FC EN1B, FC EN1C 


| num_cmd_elems | MPIO / não MPIO | 1024 para AIX | FC EN0G 
|===
====
. Configure as seguintes configurações para otimizar as operações de E/S para FC e iSCSI.
+
[role="tabbed-block"]
====
.FCP
--
[cols="4*"]
|===
| Parâmetro | Versões AIX | Valor padrão do sistema operacional AIX | Valor recomendado da NetApp 


.4+| rw_timeout (disco) | AIX 7.3TL3 | NPIV:30 segundos, vSCSI:45 segundos | NPIV: 30 segundos, vSCSI: 120 segundos 


| AIX 7.2TL5 | NPIV:30 segundos, vSCSI:45 segundos | NPIV: 30 segundos, vSCSI: 120 segundos 


| VIOS 3.1 | 30 segundos | 30 segundos 


| VIOS 4.1 | 30 segundos | 30 segundos 
|===
--
.ISCSI
--
[cols="4*"]
|===
| Parâmetro | Versões AIX | Valor padrão do sistema operacional AIX | Valor recomendado da NetApp 


.5+| rw_timeout (disco) | AIX 7.3TL3 | vSCSI:45 segundos | vSCSI:120 segundos 


| AIX 7.2TL5 | vSCSI:45 segundos | vSCSI:120 segundos 


| VIOS 3.1 | 120 segundos | 30 segundos 


| VIOS 4.1 | 120 segundos | 30 segundos 


| Todos os AIX7.2 e AIX 7.3 autônomos | 120 segundos | 30 segundos 


| isw_err_recov (iscsi0) | Todos os AIX7.2 e AIX 7.3 autônomos | falha_atrasada | falha_rápida 
|===
--
====
. Se sua configuração de armazenamento incluir sincronização ativa do MetroCluster ou do SnapMirror , altere as configurações padrão:
+
[role="tabbed-block"]
====
.MetroCluster
--
Por padrão, o sistema operacional AIX impõe um tempo limite de E/S menor quando não há caminhos disponíveis para um LUN.  Isso pode ocorrer em configurações que incluem malha SAN de switch único e em configurações do MetroCluster que apresentam failovers não planejados.  Para obter informações adicionais e alterações recomendadas nas configurações padrão, consulte o artigo da Base de conhecimentolink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Quais são as considerações de suporte ao host AIX em uma configuração do MetroCluster ?"^] .

--
.Sincronização ativa do SnapMirror
--
A partir do ONTAP 9.11.1, a sincronização ativa do SnapMirror é suportada para um host AIX.  O cluster principal em uma configuração AIX é o cluster "ativo".

Em uma configuração AIX, os failovers são disruptivos.  Com cada failover, você precisa executar uma nova varredura no host para que as operações de E/S sejam retomadas.

Consulte o artigo da Base de Conhecimentolink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Como configurar um host AIX para sincronização ativa do SnapMirror"^] .

--
====
. Verifique as configurações dos parâmetros e se vários caminhos estão listados para um LUN ONTAP :
+
[source, cli]
----
lsmpio
----
+
No exemplo a seguir, para um sistema AFF ou FAS , o PCM é listado para NetApp.

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
# lsmpio -l hdisk1
name    path_id  status   path_status  parent  connection

hdisk1  0        Enabled  Non          fscsi6  203200a098ba7afe,5b000000000000
hdisk1  1        Enabled  Non          fscsi8  203100a098ba7afe,5b000000000000
hdisk1  2        Enabled  Sel,Opt      fscsi6  203000a098ba7afe,5b000000000000
hdisk1  3        Enabled  Sel,Opt      fscsi8  203800a098ba7afe,5b000000000000
#
lsattr -El hdisk1
*PCM             PCM/friend/NetAppDefaultPCM Path Control Module*                     False
PR_key_value    0x6d0000000002              Persistant Reserve Key Value            True
algorithm       round_robin                 Algorithm                               True
clr_q           no                          Device CLEARS its Queue on error        True
dist_err_pcnt   0                           Distributed Error Sample Time           True
dist_tw_width   50                          Distributed Error Sample Time           True
hcheck_cmd      inquiry                     Health Check Command                    True
hcheck_interval 30                          Health Check Interval                   True
hcheck_mode     nonactive                   Health Check Mode                       True
location                                    Location Label                          True
lun_id          0x5b000000000000            Logical Unit Number ID                  False
lun_reset_spt   yes                         LUN Level Reset                         True
max_transfer    0x100000                    Maximum TRANSFER Size                   True
node_name       0x204800a098ba7afe          FC Node Name                            False
pvid            none                        Physical volume identifier              False
q_err           yes                         Use QERR bit                            True
q_type          simple                      Queuing TYPE                            True
qfull_dly       2                           Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                          Queue DEPTH                             True
reassign_to     120                         REASSIGN time out value                 True
reserve_policy  PR_shared                   Reserve Policy                          True
rw_timeout      30                          READ/WRITE time out value               True
scsi_id         0xec409                     SCSI ID                                 False
start_timeout   60                          START unit time out value               True
timeout_policy  fail_path                   Active/Passive Disk Path Control Module True
ww_name         0x203200a098ba7afe          FC World Wide Name                      False
----
====
. Verifique o status do caminho para LUNs ONTAP :
+
[source, cli]
----
sanlun lun show
----
+
Os exemplos de saída a seguir mostram o status correto do caminho para LUNs ONTAP em uma configuração ASA, AFF ou FAS .

+
[role="tabbed-block"]
====
.Configurações do ASA
--
Uma configuração ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos ("primários").  Isso melhora o desempenho ao atender operações de E/S por todos os caminhos ao mesmo tempo.

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----
=====
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados ("primários") e dois caminhos ativos/não otimizados ("secundários"):

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1
----
=====
--
====




== Etapa 4: Revise os problemas conhecidos

Não há problemas conhecidos.



== O que se segue?

link:hu-aix-command-reference.html["Saiba mais sobre como usar a ferramenta AIX Host Utilities"] .
