---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: Os Utilitários unificados de host do AIX ajudam você a gerenciar o storage do NetApp ONTAP anexado a um host AIX. 
---
= Instale os Utilitários de host AIX 7,0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os Utilitários unificados de host do AIX ajudam você a gerenciar o storage do NetApp ONTAP anexado a um host AIX.

Os Utilitários de host DO AIX suportam os seguintes protocolos:

* FC
* FCoE
* ISCSI


Os Utilitários de host DO AIX suportam os seguintes ambientes:

* AIX MPIO (SO NATIVO)
* PowerVM
+
Para obter mais informações sobre o PowerVM, consulte o Livro Vermelho IBM PowerVM Live Partition Mobility.



.Antes de começar
* Para uma operação confiável, verifique se toda a configuração iSCSI, FC ou FCoE é suportada.
+
Pode utilizar o https://mysupport.netapp.com/matrix/imt.jsp?components=65623%3B64703%3B&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar a sua configuração.

* O rastreamento dinâmico deve estar habilitado para todos os iniciadores FC e FCoE.



NOTE: O pacote de software de utilitários de host NetApp AIX está disponível no link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Site de suporte da NetApp"^]em um arquivo tar.gz compactado. Você deve instalar o kit de utilitários de host AIX ao usar o MPIO AIX com armazenamento NetApp ONTAP.

.Passos
. Faça login no seu host.
+
** Em um host AIX, faça login como *root*.
** Em um host PowerVM, faça login como *padmin* e digite o `oem_setup_env` comando para se tornar um usuário root.


. Aceda ao https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Site de suporte da NetApp"^] e transfira o ficheiro comprimido que contém os Utilitários do sistema anfitrião para um diretório do sistema anfitrião.
. Vá para o diretório que contém o download.
. Descompacte o arquivo e extraia o pacote de software do kit de ferramentas SAN:
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
O diretório a seguir é criado quando você descompacta o arquivo: `ntap_aix_host_utilities_7.0`. Este diretório contém um dos seguintes subdiretórios: MPIO, NON_MPIO ou SAN_Tool_Kit.

. Instale o AIX MPIO:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Instale o kit de ferramentas SAN:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. Reinicie o host.
. Verifique a instalação:
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. Confirme a versão do software:
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
. Verifique se o parâmetro SCSI UNMAP `lbp_enabled` é adicionado ao ODM executando os seguintes comandos:
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== Kit de ferramentas SAN

AIX Host Utilities é um software host NetApp que fornece um kit de ferramentas de linha de comando em seu host IBM AIX. O kit de ferramentas é instalado quando você instala o pacote de utilitários de host do NetApp. Este kit fornece o `sanlun` utilitário, que ajuda a gerenciar LUNs e adaptadores de barramento de host (HBAs). O `sanlun` comando retorna informações sobre os LUNs mapeados para o seu host, multipathing e informações necessárias para criar grupos de iniciadores.

*Exemplo*

No exemplo a seguir, o `sanlun lun show` comando retorna as informações de LUN.

[listing]
----
# sanlun lun show all
----
*Exemplo de saída*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Este kit de ferramentas é comum em todas as configurações e protocolos do Host Utilities. Como resultado, alguns de seus conteúdos se aplicam a uma configuração, mas não a outra. Ter componentes não utilizados não afeta o desempenho do sistema. O kit de ferramentas SAN é suportado nas versões AIX e PowerVM/VIOS os.
