---
sidebar: sidebar 
permalink: hu-aix-release-notes.html 
keywords: host utilities, aix, 6.1 netapp, 7.0, ontap, powervm 
summary: Notas de versão para AIX Host Utilities 6,1 
---
= AIX Host Utilities Notas de lançamento
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As notas de versão descrevem novos recursos e aprimoramentos, problemas corrigidos na versão atual, problemas e limitações conhecidos e cuidados importantes relacionados à configuração e ao gerenciamento do seu host AIX específico com seu sistema de armazenamento ONTAP .

Para obter informações específicas sobre as versões e atualizações do sistema operacional compatíveis com os Utilitários do host, consulte link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^].

As versões do AIX Host Utilities contêm os seguintes novos recursos e aprimoramentos.



== Novidades no AIX Host Utilities 8.0

Um IBM Interim Fix (ifix) está disponível para o AIX Host Utilities 8.0 que garante a `sanlun fcp show adapter –v` O comando exibe as informações corretas de velocidade do HBA, como velocidades suportadas e negociadas para os adaptadores.  Você pode instalar o ifix nas seguintes versões do AIX e VIOS:

* AIX: 7,3 TL3 SP0, 7,3 TL2 SP2, 7,3 TL1 SP4, 7,2 TL5 SP9, 7,2 TL5 SP8
* VIOS: 4.1.1.0, 4.1.0.21, 3.1.4.50, 3.1.4.41




== Novidades no AIX Host Utilities 7.0

O AIX Host Utilities 7,0 suporta O DESBLOQUEIO SCSI no sistema operacional do host AIX. Com os utilitários de host AIX 7,0, o provisionamento de thin SCSI funciona perfeitamente com LUNs AIX e NetApp para dispositivos FC.



== Novidades no AIX Host Utilities 6.1

AIX Host Utilities 6,1 inclui suporte para o problema de falha de memória que ocorreu em versões anteriores do sistema operacional host AIX. Com AIX Host Utilities 6,1, apenas o binário sanlun mudou. O Microsoft Multipath I/o (MPIO) e o ODM relacionado permanecem inalterados.



== Problemas e limitações conhecidos

Você deve estar ciente dos seguintes problemas e limitações conhecidos que podem afetar o desempenho do seu host específico:

[cols="4"]
|===
| ID do bug | Afeta a versão | Título | Descrição 


| N/A. | 7,0 | O SCSI DESMAPEIA o suporte para LUNs iSCSI ONTAP | O AIX Host Utilities 7,0 suporta apenas o recurso DE DESINSTALAÇÃO SCSI para dispositivos FC. O suporte DE DESBLOQUEIO SCSI para dispositivos iSCSI não está incluído nesta versão. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1069147["1069147"^] |  | AIX HU Sanlun relata velocidade HBA incorreta | Instâncias de sanlun exibindo velocidades HBA incorretas são relatadas durante a execução do `sanlun fcp show adapter –v` comando. O `sanlun fcp show adapter –v` comando exibe as informações das placas HBA, como velocidades suportadas e negociadas para os adaptadores. Este parece ser apenas um problema de relatório. Para identificar a velocidade real, use o `fcstat fcsx` comando. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"^] fornece informações completas para a maioria dos problemas conhecidos, incluindo soluções alternativas sugeridas sempre que possível. Algumas combinações de palavras-chave e tipos de bug que você pode querer usar incluem o seguinte:

* FCP Geral: Exibe bugs FC e HBA que não estão associados a um host específico.
* FCP - AIX

