---
sidebar: sidebar 
permalink: hu-aix-san-toolkit.html 
keywords: san, toolkit, command, line, AIX, hot, utilities 
summary: O software host AIX Host Utilities fornece um kit de ferramentas de linha de comando no seu host IBM AIX. 
---
= Saiba mais sobre o AIX SAN Toolkit para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O AIX Host Utilities é um software host da NetApp que fornece um kit de ferramentas de linha de comando no seu host IBM AIX.  O kit de ferramentas SAN é instalado quando você instala o pacote NetApp Host Utilities.  O kit de ferramentas fornece o `sanlun` utilitário, que ajuda você a gerenciar LUNs ONTAP e adaptadores de barramento de host (HBAs).  O `sanlun` O comando retorna informações sobre LUNs ONTAP mapeados para seu host, multipathing e informações necessárias para criar grupos de iniciadores.

O exemplo de saída a seguir mostra as informações do ONTAP LUN retornadas para o `sanlun lun show` comando:

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: O SAN Toolkit é comum em todas as configurações de host e protocolos de transporte do AIX.  Como resultado, todos os componentes não se aplicam a todas as configurações.  Componentes não utilizados não afetam o desempenho do sistema.  O SAN Toolkit é compatível com versões de sistema operacional AIX e PowerVM/VIOS.



== O que se segue?

link:hu-aix-command-reference.html["Saiba mais sobre como usar a ferramenta AIX Host Utilities"] .
