---
sidebar: sidebar 
permalink: hu-proxmox-ve-9x.html 
keywords: proxmox, VE, 9.x, netapp, ontap, iscsi, fcp 
summary: Instale os utilitários de host Linux em um host Proxmox VE 9.x para gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP . 
---
= Configure o Proxmox VE 9.x para FCP e iSCSI com armazenamento ONTAP.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configure o Proxmox VE 9.x para multipathing com parâmetros e configurações específicos para operações de protocolo FCP e iSCSI com armazenamento ONTAP .

FCP e iSCSI com Proxmox VE 9.x apresentam as seguintes limitações conhecidas:

* Os utilitários de host Linux não são compatíveis com os sistemas operacionais Proxmox VE 9.x.
* A configuração de inicialização SAN não é suportada.




== Etapa 1: confirme a configuração multipath para seu host

Você pode usar o recurso de multipathing com o Proxmox VE 9.x para gerenciar LUNs do ONTAP .

Para garantir que o multipathing esteja configurado corretamente para o host, verifique se o `/etc/multipath.conf` arquivo está definido e se você tem as configurações recomendadas do NetApp configuradas para os LUNs do ONTAP.

.Passos
. Verifique se o `/etc/multipath.conf` arquivo sai. Se o arquivo não existir, crie um arquivo vazio de zero bytes:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Na primeira vez que o `multipath.conf` arquivo é criado, talvez seja necessário ativar e iniciar os serviços multipath para carregar as configurações recomendadas:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Cada vez que você inicializar o host, o arquivo vazio de `/etc/multipath.conf` zero byte carrega automaticamente os parâmetros de multipath de host recomendados pelo NetApp como as configurações padrão. Você não deve precisar fazer alterações no `/etc/multipath.conf` arquivo para o seu host porque o sistema operacional é compilado com os parâmetros multipath que reconhecem e gerenciam LUNs ONTAP corretamente.
+
A tabela a seguir mostra as configurações de parâmetros multipath compilados nativos do sistema operacional Linux para LUNs ONTAP.

+
.Mostrar definições de parâmetros
[%collapsible]
====
[cols="2"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "2 pg_init_retries 50" 


| flush_on_last_del | "sempre" 


| hardware_handler | "1" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
====
. Opcionalmente, substitua o valor padrão para o `find_multipaths` parâmetro para garantir que os LUNs do ONTAP sejam descobertos e gerenciados corretamente pelo multipathd:
+
--
.. Definir `find_multipaths` para "não" na seção de padrões de `/etc/multipath.conf` :
+
[source, cli]
----
defaults {
    find_multipaths "no"
}
----
.. Recarregue o serviço multipath:
+
[source, cli]
----
systemctl reload multipathd
----


--
+

NOTE: Por padrão, a configuração multipath nativa do sistema operacional Proxmox é definida. `find_multipaths` para "*strict*" com o byte zero vazio `/etc/multipath.conf` O arquivo de configuração é atualizado a cada inicialização do host.  Isso pode impedir que o host descubra LUNs ONTAP recém-apresentados como dispositivos multipath, o que significa que eles não aparecem automaticamente sob controle multipath.  Os LUNs ONTAP existentes permanecem descobertos e sob controle de múltiplos caminhos após cada reinicialização.

. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Os parâmetros multipath padrão são compatíveis com configurações ASA, AFF e FAS. Nessas configurações, um único LUN ONTAP não deve exigir mais de quatro caminhos. Se houver mais de quatro caminhos, isso pode causar problemas com os caminhos durante uma falha de storage.

+
As saídas de exemplo a seguir mostram as configurações de parâmetro e o status do caminho corretos para LUNs ONTAP em uma configuração ASA, AFF ou FAS.

+
[role="tabbed-block"]
====
.Configuração ASA
--
Uma configuração do ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
multipath -ll
3600a098038315071592b59713261566d dm-38 NETAPP,LUN C-Mode
size=100G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 8:0:0:7 sdbv 68:144 active ready running
  |- 9:0:0:7 sdbx 68:176 active ready running
  |- 6:0:0:7 sdbr 68:80  active ready running
  `- 7:0:0:7 sdbt 68:112 active ready running

----
=====
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir mostra a saída para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383149764b5d567257516273 dm-0 NETAPP,LUN C-Mode
size=150G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:3:0  sdcg 69:64  active ready running
| `- 10:0:0:0  sdb  8:16   active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 10:0:1:0  sdc  8:32   active ready running
  `- 16:0:2:0  sdcf 69:48  active ready running
----
=====
--
====




== Etapa 2: confirme a configuração iSCSI para o seu host

Certifique-se de que iSCSI esteja configurado corretamente para seu host.

.Sobre esta tarefa
Você executa as seguintes etapas no host iSCSI.

.Passos
. Verifique se o pacote iniciador iSCSI (open-iscsi) está instalado:
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
open-iscsi/noble-updates,noble-updates,now 2.1.9-3ubuntu5.4 amd64
----
. Verifique o nome do nó do iniciador iSCSI, que está localizado no  `/etc/iscsi/initiatorname.iscsi` arquivo:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configure o parâmetro de tempo limite da sessão iSCSI localizado no arquivo  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
O parâmetro  `replacement_timeout`iSCSI controla por quanto tempo a camada iSCSI deve esperar que um caminho ou sessão com tempo limite expirado se restabeleça antes de falhar quaisquer comandos nele. Você deve definir o valor de  `replacement_timeout`para 5 no arquivo de configuração iSCSI.

. Ative o serviço iSCSI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Inicie o serviço iSCSI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verifique se o serviço iSCSI está em execução:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
●iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Mon 2026-01-12 12:53:18 IST; 2 days ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
   Main PID: 1127419 (iscsid)
      Tasks: 2 (limit: 76557)
     Memory: 4.3M (peak: 8.8M)
        CPU: 1.657s
     CGroup: /system.slice/iscsid.service
             ├─1127418 /usr/sbin/iscsid
             └─1127419 /usr/sbin/iscsid
----
====
. Descubra os alvos iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.100.197
192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8
----
====
. Faça login nos destinos:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Defina o iSCSI para fazer login automaticamente quando o host for inicializado:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 -p 192.168.100.197:3260 -o update -n node.startup -v automatic
----
. Verifique as sessões iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.200.197:3260,1047 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [2] 192.168.100.197:3260,1046 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [3] 192.168.100.199:3260,1048 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
tcp: [4] 192.168.200.199:3260,1049 iqn.1992-08.com.netapp:sn.7cd154a7d35411f0a25ed039eaa95f59:vs.8 (non-flash)
----
====




== Etapa 3: opcionalmente, exclua um dispositivo do multipathing

Se necessário, você pode excluir um dispositivo de multipathing adicionando o WWID para o dispositivo indesejado à estrofe "lista negra" para o `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" é o disco SCSI local que você deseja adicionar à lista negra.

+
Um exemplo WWID é `360030057024d0730239134810c0cb833`.

. Adicione o WWID à estrofe "blacklist":
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Etapa 4: personalizar parâmetros multicaminho para LUNs ONTAP

Se o seu host estiver conetado a LUNs de outros fornecedores e qualquer configuração de parâmetro multipath for substituída, você precisará corrigi-los adicionando estrofes posteriormente `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Se você não fizer isso, os LUNs do ONTAP podem não funcionar como esperado.

Verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações que possam estar substituindo o <<multipath-parameter-settings,configurações padrão para parâmetros multipath>>.


CAUTION: Não deve substituir as definições de parâmetros recomendadas para LUNs ONTAP. Essas configurações são necessárias para o desempenho ideal da configuração do seu host. Entre em Contato com o suporte da NetApp, seu fornecedor de sistemas operacionais ou ambos para obter mais informações.

O exemplo a seguir mostra como corrigir um padrão substituído. Neste exemplo, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP, e você não pode remover esses parâmetros porque os storages ONTAP ainda estão conetados ao host. Em vez disso, você corrige os valores `path_checker` de e `no_path_retry` adicionando uma estrofe de dispositivo ao `multipath.conf` arquivo que se aplica especificamente aos LUNs ONTAP.

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Etapa 5: Revise os problemas conhecidos

Não há problemas conhecidos.
