---
sidebar: sidebar 
permalink: hu-sles-16spx.html 
keywords: host utilities, suse linux enterprise server 16,netapp, ontap, fcp, iscsi 
summary: Instale os utilitários de host Linux em um servidor SUSE Linux Enterprise Server 16 para gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP. 
---
= Configurar o SUSE Linux Enterprise Server 16 para FCP e iSCSI com armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O software Linux Host Utilities fornece ferramentas de gerenciamento e diagnóstico para hosts Linux conectados ao armazenamento ONTAP. Ao instalar o Linux Host Utilities em um host SUSE Linux Enterprise Server 16, você pode usar o Host Utilities para ajudar a gerenciar as operações dos protocolos FCP e iSCSI com LUNs ONTAP.



== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.

.Antes de começar
Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.

.Passos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crie um LUN de inicialização SAN e mapeie-o para o host"^].
. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Verifique se a configuração foi bem-sucedida reinicializando o host e verificando se o sistema operacional está funcionando.




== Passo 2: Instale os Utilitários de host do Linux

A NetApp recomenda fortemente a instalação dos utilitários de host Linux para suportar o gerenciamento de LUN ONTAP e auxiliar o suporte técnico na coleta de dados de configuração.

link:hu_luhu_71.html["Instale o Linux Host Utilities 7,1"].


NOTE: A instalação dos Utilitários de host do Linux não altera nenhuma configuração de tempo limite do host no seu host Linux.



== Etapa 3: Confirme a configuração multipath do seu host

Você pode usar o recurso de multipathing com o SUSE Linux Enterprise Server 16 para gerenciar ONTAP LUNs.

Para garantir que o multipathing esteja configurado corretamente para o host, verifique se o `/etc/multipath.conf` arquivo está definido e se você tem as configurações recomendadas do NetApp configuradas para os LUNs do ONTAP.

.Passos
. Verifique se o `/etc/multipath.conf` arquivo existe:
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Se o arquivo não existir, crie um arquivo vazio de zero bytes:

+
[source, cli]
----
touch /etc/multipath.conf
----
. Na primeira vez que o `multipath.conf` arquivo é criado, talvez seja necessário ativar e iniciar os serviços multipath para carregar as configurações recomendadas:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Cada vez que você inicializar o host, o arquivo vazio de `/etc/multipath.conf` zero byte carrega automaticamente os parâmetros de multipath de host recomendados pelo NetApp como as configurações padrão. Você não deve precisar fazer alterações no `/etc/multipath.conf` arquivo para o seu host porque o sistema operacional do host é compilado com os parâmetros multipath que reconhecem e gerenciam LUNs ONTAP corretamente.
+
A tabela a seguir mostra as configurações de parâmetros multipath compilados pelo sistema operacional Linux nativo para LUNs ONTAP.

+
.Mostrar definições de parâmetros
[%collapsible]
====
[cols="2"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "2 pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
====
. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Os parâmetros multipath padrão suportam configurações ASA, AFF e FAS . Nessas configurações, um único LUN ONTAP não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas durante uma falha de armazenamento.

+
As saídas de exemplo a seguir mostram as configurações de parâmetro e o status do caminho corretos para LUNs ONTAP em uma configuração ASA, AFF ou FAS.

+
[role="tabbed-block"]
====
.Configuração ASA
--
Uma configuração do ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir exibe a saída de um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Passo 4: confirme a configuração iSCSI para o seu host

Para garantir que o multipath esteja configurado corretamente para o seu host, defina o  `timeout` parâmetro no seu host e confirme que o serviço iSCSI está em execução e conectando-se aos destinos iSCSI.

.Passos
. Verifique se o pacote do iniciador iSCSI (iscsi-initiator-utils) está instalado:
+
[source, cli]
----
rpm -qa | grep open-iscsi
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
open-iscsi-2.1.11-160000.2.2.x86_64
----
. Verifique o nome do nó do iniciador iSCSI, que está localizado no  `/etc/iscsi/initiatorname.iscsi` arquivo:
+
[listing]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configure o parâmetro de tempo limite da sessão iSCSI localizado no arquivo  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
O parâmetro  `replacement_timeout`iSCSI controla por quanto tempo a camada iSCSI deve esperar que um caminho ou sessão com tempo limite expirado se restabeleça antes de falhar quaisquer comandos nele. Você deve definir o valor de  `replacement_timeout`para 5 no arquivo de configuração iSCSI.

. Ative o serviço iSCSI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Inicie o serviço iSCSI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verifique se o serviço iSCSI está em execução:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
● iscsid.service - Open-iSCSI
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Tue 2025-12-02 11:36:21 EST; 2 weeks 1 day ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
             man:iscsiuio(8)
             man:iscsiadm(8)
   Main PID: 2263 (iscsid)
     Status: "Ready to process requests"
      Tasks: 1 (limit: 816061)
     Memory: 18.5M
        CPU: 14.480s
     CGroup: /system.slice/iscsid.service
             └─2263 /usr/sbin/iscsid -f -d2
----
====
. Descubra os alvos iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal  192.168.30.87
192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23
----
====
. Faça login nos destinos:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Defina o iSCSI para fazer login automaticamente quando o host for inicializado:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 -p 192.168.30.87:3260 -o update -n node.startup -v automatic
----
. Verifique as sessões iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.30.87:3260,1139 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [2] 192.168.31.97:3260,1142 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [3] 192.168.31.87:3260,1141 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
tcp: [4] 192.168.30.97:3260,1140 iqn.1992-08.com.netapp:sn.064a9b19b3ee11f09dcad039eabac370:vs.23 (non-flash)
----
====




== Etapa 5: opcionalmente, exclua um dispositivo do multipathing

Se necessário, você pode excluir um dispositivo de multipathing adicionando o WWID para o dispositivo indesejado à estrofe "lista negra" para o `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" é o disco SCSI local que você deseja adicionar à lista negra.

+
Um exemplo WWID é `360030057024d0730239134810c0cb833`.

. Adicione o WWID à estrofe "blacklist":
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Etapa 6: personalizar os parâmetros de multipath para ONTAP LUNs

Se o seu host estiver conetado a LUNs de outros fornecedores e qualquer configuração de parâmetro multipath for substituída, você precisará corrigi-los adicionando estrofes posteriormente `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Se você não fizer isso, os LUNs do ONTAP podem não funcionar como esperado.

Verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações que possam estar substituindo o <<multipath-parameter-settings,configurações padrão para parâmetros multipath>>.


CAUTION: Não deve substituir as definições de parâmetros recomendadas para LUNs ONTAP. Essas configurações são necessárias para o desempenho ideal da configuração do seu host. Entre em Contato com o suporte da NetApp, seu fornecedor de sistemas operacionais ou ambos para obter mais informações.

O exemplo a seguir mostra como corrigir um padrão substituído. Neste exemplo, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP, e você não pode remover esses parâmetros porque os storages ONTAP ainda estão conetados ao host. Em vez disso, você corrige os valores `path_checker` de e `no_path_retry` adicionando uma estrofe de dispositivo ao `multipath.conf` arquivo que se aplica especificamente aos LUNs ONTAP.

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Etapa 7: Revise os problemas conhecidos

Não há problemas conhecidos.



== O que se segue?

* link:hu-luhu-command-reference.html["Saiba mais sobre como usar a ferramenta Linux Host Utilities"] .
* Saiba mais sobre espelhamento ASM
+
O espelhamento do Gerenciamento Automático de armazenamento (ASM) pode exigir alterações nas configurações de multipath do Linux para permitir que o ASM reconheça um problema e alterne para um grupo de falhas alternativo. A maioria das configurações ASM no ONTAP usa redundância externa, o que significa que a proteção de dados é fornecida pelo array externo e o ASM não espelha dados. Alguns sites usam ASM com redundância normal para fornecer espelhamento bidirecional, normalmente em diferentes sites. link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bancos de dados Oracle no ONTAP"^]Consulte para obter mais informações.

* Saiba mais sobre a virtualização do SUSE Linux (KVM)
+
O SUSE Linux pode servir como um host KVM. Isso permite executar várias máquinas virtuais em um único servidor físico usando a tecnologia de Máquina Virtual baseada no Kernel do Linux (KVM). O host KVM não requer configurações explícitas de host para LUNs ONTAP .


