---
sidebar: sidebar 
permalink: hu-veritas-8x.html 
keywords: host utilities, veritas, infoscale, 8, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: Utilize os utilitários de host Linux com o Veritas Infoscale 8 para hosts RHEL e Oracle Linux para ajudar você a gerenciar operações de protocolo FC, FCoE e iSCSI com LUNs ONTAP . 
---
= Configure o Veritas Infoscale 8 para FC, FCoE e iSCSI com armazenamento ONTAP.
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O software Linux Host Utilities fornece ferramentas de gerenciamento e diagnóstico para hosts Linux conectados ao armazenamento ONTAP . Utilize os utilitários de host Linux com o Veritas Infoscale 8 para hosts Oracle Linux (baseado em kernel compatível com Red Hat), Red Hat Enterprise Linux (RHEL) e SUSE Linux Enterprise Server para oferecer suporte ao gerenciamento de operações de protocolo FC, FCoE e iSCSI com LUNs ONTAP .



== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.

.Antes de começar
* Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.
* Consulte o Portal de Suporte da Veritas (Matriz de Produtos, Pesquisa de Plataformas e Matriz HCL) para verificar o suporte à configuração de inicialização SAN e problemas conhecidos.


.Passos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crie um LUN de inicialização SAN e mapeie-o para o host"^].
. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Verifique se a configuração foi bem-sucedida reinicializando o host e verificando se o sistema operacional está funcionando.




== Passo 2: Instale os Utilitários de host do Linux

A NetApp recomenda enfaticamente link:hu-luhu-release-notes.html["Instalando os utilitários do host Linux"] Para dar suporte ao gerenciamento de LUNs do ONTAP e auxiliar o suporte técnico na coleta de dados de configuração.


NOTE: A instalação dos Utilitários de host do Linux não altera nenhuma configuração de tempo limite do host no seu host Linux.



== Etapa 3: Confirme a configuração do Veritas Dynamic Multipathing para o seu host.

Utilize o Veritas Dynamic Multipathing (VxDMP) com o Veritas Infoscale 8 para gerenciar LUNs ONTAP .

Para garantir que o VxDMP esteja configurado corretamente para o seu host, você precisa verificar a configuração do VxDMP e conferir a configuração da Biblioteca de Suporte de Array (ASL) e do Módulo de Política de Array (APM). Os pacotes ASL e APM para sistemas de armazenamento NetApp são instalados durante a instalação do software Veritas.


NOTE: Para ambientes multipath heterogêneos, incluindo Veritas Infoscale, Linux Native Device Mapper e gerenciador de volumes LVM, consulte a documentação de administração de produtos da Veritas para obter as configurações.

.Antes de começar
Certifique-se de que sua configuração atenda aos requisitos do sistema. Veja o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] e a Matriz Veritas HCL.

.Passos
. Verifique se o array de destino ONTAP está conectado ao multipath VxDMP:
+
[source, cli]
----
vxdmpadm
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. Verifique a configuração dos pacotes ASL e APM. A NetApp recomenda que você utilize os pacotes mais recentes compatíveis, listados no portal de suporte da Veritas.
+
.Mostrar exemplo de configuração de ASL e APM
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. Para uma configuração ideal do sistema em operações de failover de armazenamento, verifique se você possui os seguintes parâmetros ajustáveis do Veritas VxDMP:
+
[cols="2*"]
|===
| Parâmetro | Definição 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval | 60 
|===
. Configure as opções de ajuste do DMP para o modo online:
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. Verifique se as configurações de tunables estão corretas:
+
[source, cli]
----
# vxdmpadm gettune
----
+
O exemplo a seguir mostra os parâmetros ajustáveis do VxDMP em vigor em um host SAN.

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. Configure os valores de tempo limite do protocolo:
+
[role="tabbed-block"]
====
.FC/FCoE
--
Utilize os valores de tempo limite padrão para FC e FCoE.

--
.iSCSI
--
Defina o `replacement_timeout` Valor do parâmetro definido como 120.

O iSCSI `replacement_timeout` Este parâmetro controla por quanto tempo a camada iSCSI deve esperar que um caminho ou sessão com tempo limite expirado se restabeleça antes de falhar em quaisquer comandos nele. A NetApp recomenda definir o valor de `replacement_timeout` para 120 no arquivo de configuração iSCSI.

[source, cli]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. Configure os valores "udev rport" do host para hosts RHEL das séries 8 e 9 para dar suporte ao ambiente Veritas Infoscale em cenários de failover de armazenamento.
+
Configure os valores de "udev rport" criando o arquivo. `/etc/udev/rules.d/40-rport.rules` com o seguinte conteúdo de arquivo:

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Consulte a documentação padrão do produto Veritas Infoscale para todas as outras configurações específicas da Veritas.

. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
Em configurações AFF, FAS ou ASA , um único LUN ONTAP não deve exigir mais de quatro caminhos. Mais de quatro caminhos podem causar problemas durante uma falha de armazenamento.

+
Os exemplos a seguir mostram as configurações de parâmetros e o status do caminho corretos para LUNs ONTAP em uma configuração ASA, AFF ou FAS .

+
[role="tabbed-block"]
====
.Configuração ASA
--
Uma configuração do ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir exibe a saída de um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

.Mostrar exemplo
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== Etapa 4: Problemas conhecidos

Não há problemas conhecidos.



== O que se segue?

* link:hu-luhu-command-reference.html["Saiba mais sobre como usar a ferramenta Linux Host Utilities"] .

