---
sidebar: sidebar 
permalink: hu-wuhu-release-notes.html 
keywords: host utilities, linux, 7.1, 7.2, netapp, ontap, release, notes 
summary: Notas de versão para Utilitários de sistema anfitrião do Windows 
---
= Notas de lançamento dos Utilitários do sistema anfitrião do Windows
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As notas de versão descrevem novos recursos, aprimoramentos, problemas conhecidos, limitações e cuidados importantes relacionados à configuração e ao gerenciamento do seu host Windows específico com seu sistema de armazenamento ONTAP .

Para obter informações específicas sobre as versões e atualizações do sistema operacional compatíveis com os Utilitários do host, consulte link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^].



== Novidades no Windows Host Utilities 8.0

O Windows Host Utilities 8.0 inclui configurações de parâmetros adicionais para drivers NVMe/FC.  Esses parâmetros são carregados automaticamente quando você instala o Windows Host Utilities 8.0.



== Novidades no Windows Host Utilities 7.2

O Windows Host Utilities 7,2 inclui suporte para configurações de parâmetros de driver NVMe/FC e correções de bugs para novas placas de fornecedores.



== Novidades no Windows Host Utilities 7.1

O Windows Host Utilities 7.1 inclui suporte para sistemas de armazenamento da série E, software ONTAP 9 e tempos limite de iSCSI aprimorados para failover mais rápido.



== Problemas e limitações conhecidos

Você deve estar ciente dos seguintes problemas e limitações conhecidos que podem afetar o desempenho do seu host específico.

[cols="30, 15, 30, 30"]
|===
| Título | Afeta a versão | Descrição | Solução alternativa 


| A execução `linux_gos_timeout-install.sh` do script não é mais necessária em convidados do Hyper-V que executam o Red Hat Enterprise Linux ou o SUSE Linux Enterprise Server | 7,1 | Não é mais necessário executar `linux_gos_timeout-install.sh` o script para alterar o tempo limite de disco nos convidados Red Hat Enterprise Linux 5, Red Hat Enterprise Linux 6 ou SUSE Linux Enterprise Server 11 Hyper-V porque as configurações de tempo limite padrão estão sendo usadas. O `linux_gos_timeout-install.sh` script que foi incluído em versões anteriores dos Utilitários de host não está mais incluído na versão do Windows Host Utilities 7,1. O Windows Host Utilities 7,1 usa as configurações padrão de tempo limite do disco. | Não aplicável 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] fornece informações completas para a maioria dos problemas conhecidos, incluindo soluções alternativas sugeridas sempre que possível.
