---
sidebar: sidebar 
permalink: hu-wuhu-80.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: O Windows Host Utilities inclui um programa de instalação que define os parâmetros necessários do registro do Windows e do HBA para que o host do Windows manipule corretamente os comportamentos do sistema de armazenamento para plataformas ONTAP . 
---
= Instalar o Windows Host Utilities 8.0 para armazenamento ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os Utilitários de host do Windows permitem que você conete um computador host do Windows aos sistemas de armazenamento do NetApp.

Os Utilitários de host do Windows suportam as seguintes versões do Windows:

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016


O Windows Host Utilities inclui um programa de instalação que define os parâmetros necessários do registro do Windows e do Host Bus Adapter (HBA) para que um host Windows possa manipular corretamente os comportamentos do sistema de armazenamento para plataformas ONTAP .

Ao instalar o software Host Utilities, o instalador define os parâmetros necessários do registo do Windows e do HBA.

Os seguintes programas e arquivos são instalados no computador host do Windows. O diretório padrão é `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programa | Finalidade 


| `\NetAppQCLI\fcconfig.exe` | Utilizado pelo programa de instalação para definir os parâmetros HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizado pelo programa de instalação para definir os parâmetros HBA. 


| `san_version.exe` | Exibe a versão dos Utilitários do host e HBAs FC. 
|===
Os Utilitários de host oferecem suporte a diferentes configurações de host do Windows, protocolos e opções de multipathing. Para obter mais informações, consulte https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^] .



== Etapa 1: verifique a configuração do seu host e do sistema de armazenamento

Verifique se a configuração do seu host e do sistema de armazenamento são compatíveis antes de instalar o Windows Host Utilities para o<<supported-windows-versions-80,Versão Windows suportada>> .

.Passos
. Verifique a configuração suportada no http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade"^].
. Verifique os hotfixes necessários para a versão do host do Windows Server emlink:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentação do Windows de host SAN"] .
+
Por exemplo, olink:https://docs.netapp.com/us-en/ontap-sanhost/hu-windows-2025.html["Configure o Windows Server 2025 para armazenamento ONTAP"] a documentação fornece instruções para instalar hotfixes do Windows para o Windows Server 2025.

. link:https://docs.netapp.com/us-en/ontap/san-admin/verify-license-fc-iscsi-task.html["Adicione a licença iSCSI ou FCP"^] .
. Inicie o serviço de destino.
. Verifique o cabeamento.
+
Consulte o https://docs.netapp.com/us-en/ontap/san-config/index.html["Referência de configuração SAN"^] para obter informações detalhadas sobre cabeamento e configuração.





== Etapa 2: configurar HBAs e switches FC

Instalar e configurar um ou mais adaptadores de barramento de host FC (HBAs) compatíveis para conexões FC ao sistema de storage.

O instalador de Utilitários de host do Windows define as configurações de HBA FC necessárias.


CAUTION: Você deve permitir apenas que o instalador do Windows Host Utilities defina os parâmetros do HBA.  Isso garante que o host Windows possa manipular corretamente os comportamentos do sistema de armazenamento para plataformas ONTAP .

.Passos
. Instale um ou mais HBAs FC compatíveis de acordo com as instruções fornecidas pelo fornecedor do HBA.
. Obtenha os drivers e utilitários de gerenciamento HBA suportados e instale-os de acordo com as instruções fornecidas pelo fornecedor HBA.
. https://docs.netapp.com/us-en/ontap/san-management/index.html["Conecte os HBAs aos seus switches FC ou diretamente ao sistema de armazenamento"^] .
. https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["Crie zonas no switch FC de acordo com a documentação do switch FC"^] .
. Para ONTAP, zoneie o switch pelo WWPN.  Certifique-se de usar o WWPN das interfaces lógicas (LIFs) e não o WWPN das portas físicas nos controladores de armazenamento. Consulte o  https://docs.netapp.com/us-en/ontap/san-config/index.html["Referência de configuração SAN"^] para maiores informações.




== Etapa 3: instalar os utilitários do host do Windows

O programa de instalação instala o pacote Windows Host Utilities e define o registro do Windows e as configurações do HBA.

.Sobre esta tarefa
Opcionalmente, você pode incluir suporte a múltiplos caminhos ao instalar o pacote de software Windows Host Utilities.  O instalador solicitará as seguintes opções:

* Escolha `MPIO` se você tiver mais de um caminho do host do Windows ou da máquina virtual para o sistema de armazenamento.
* Escolher `no MPIO` somente se você estiver usando um único caminho para o sistema de armazenamento.


Você também pode escolher o suporte a múltiplos caminhos usando um prompt de linha de comando do Windows.

Para convidados do Hyper-V, os discos brutos (pass-through) não aparecem no sistema operacional convidado se você escolher o suporte a múltiplos caminhos.  Você pode usar discos brutos ou MPIO, mas não pode usar ambos no sistema operacional convidado.


CAUTION: Se você não instalar o software MPIO, o sistema operacional Windows pode ver cada caminho como um disco separado. Isso pode levar à corrupção de dados.


NOTE: O Windows XP ou o Windows Vista em execução numa máquina virtual Hyper-V não suporta MPIO.

.Passos
Você pode instalar o Host Utilities interativamente ou usando a linha de comando do Windows.  O novo pacote de instalação do Host Utilities deve estar em um caminho acessível ao host Windows.

[role="tabbed-block"]
====
.Instale de forma interativa
--
Instale o pacote de software Windows Host Utilities interativamente executando o programa de instalação e seguindo as instruções.

. Baixe o arquivo executável do https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/8.0/downloads["Site de suporte da NetApp"^] .
. Mude para o diretório onde você baixou o arquivo executável.
. Execute o `netapp_windows_host_utilities_8.0.0_x64` arquivo e siga as instruções na tela.
. Reinicie o host do Windows quando solicitado.


--
.Instalar de forma não interativa
--
Execute uma instalação não interativa dos Utilitários do Host usando a linha de comando do Windows.  O sistema será reinicializado automaticamente quando a instalação estiver concluída.

. Digite o seguinte comando no prompt de comando do Windows:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` É o nome do `.msi` arquivo para a arquitetura da CPU.
** MULTIPATHING especifica se o suporte MPIO está instalado. Os valores permitidos são "0" para não e "1" para sim.
** `inst_path` É o caminho onde os arquivos do Host Utilities estão instalados. O caminho padrão é `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver as opções padrão do Microsoft Installer (MSI) para Registro e outras funções, digite `msiexec /help` no prompt de comando do Windows. Por exemplo, o `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` comando exibe informações de Registro.

--
====


== O que se segue?

link:hu-wuhu-configuration.html["Saiba mais sobre a configuração dos utilitários do host do Windows para armazenamento ONTAP."]
