---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: Descreve como descobrir e configurar LUNS com AIX 
---
= (AIX MPIO sem PowerVM) descobrindo e configurando LUNs com AIX
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando você está usando AIX sem PowerVM, você usa o comando cfgmgr para fazer com que o host descubra os LUNs. Não é necessário reiniciar o host para descobrir os LUNs. Para confirmar que o host descobriu os LUNS, você pode usar o utilitário sanlun.


NOTE: As etapas a seguir não se aplicam a um host que esteja executando um ambiente PowerVM.

.Passos
. Faça login como root no host.
. No host AIX, digite o seguinte comando para descobrir os LUNs recém-criados:
+
`cfgmgr`

+
O `cfgmgr` comando ajuda com o seguinte:

+
** Os iniciadores para fazer login no tecido.
** O sistema para verificar se existem novos dispositivos.
** O sistema para criar novas entradas de dispositivo.


. Para exibir todos os discos AIX, incluindo os LUNs NetApp, digite o seguinte comando:
+
`lsdev -Cc disk`

+
Os LUNs aparecem no host como discos. Você pode usar esses discos da mesma maneira que usa discos locais no host. O arquivo ODM de configurações do host instalado como parte dos Utilitários do host faz com que os LUNs sejam exibidos como discos FCP do NetApp.

+
Anote os números da instância do hdisk. Você os usa quando executa a configuração do caminho.

+
O seguinte é o tipo de saída que o comando lsdev -cc disk produz em um ambiente usando FC.

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. Digite o seguinte comando para obter informações sobre sua configuração:
+
`lsattr -El hdisk_name`

+
Este comando produz a seguinte saída.

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Se a sua configuração suportar ALUA, você pode usá-la para definir a prioridade do caminho. Verifique se o ALUA está ativado:
+
`lun igroup show -instance igroup_name`

+
.. Se o ALUA não estiver ativado, ative-o:
+
`igroup set igroup_name alua yes`



. Se sua configuração não suportar ALUA, você deve executar o utilitário dotpaths para definir as prioridades do caminho. O utilitário dotpaths é instalado quando você instala os Utilitários do host. Não use o utilitário dotpaths se o ALUA estiver habilitado.
+
.. Para definir a prioridade para todos os LUNs Data ONTAP, introduza:
+
`dotpaths`

.. Para definir prioridade para um conjunto específico de disco, introduza:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Use a `-v` opção para ativar o modo verboso e exibir todas as prioridades. Use a `-q` opção para consultar todas as prioridades de disco ou individuais.



. Para verificar se o host descobriu os LUNs, digite o seguinte comando:
+
`# sanlun lun show`

+
.Exemplo
Este exemplo mostra a saída típica `sanlun lun show` do comando em um ambiente multipathing MPIO.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

