---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_powervm_vscsi.html 
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering 
summary: Descreve como usar Discover e configurar LUNs com PowerVM vSCSI 
---
= (PowerVM vSCSI) descobrindo e configurando LUNs
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando você estiver usando servidores PowerVM vSCSI e VIO, você deve usar o login padmin e os comandos apropriados para configurar e descobrir LUNs.

.Passos
. Faça login no host como padmin.
. No host AIX, digite o seguinte comando para descobrir os LUNs recém-criados:
+
`cfgdev`

+
O comando cfgdev causa:

+
** Os iniciadores para fazer login no tecido.
** O sistema para verificar se existem novos dispositivos.
** O sistema para criar novas entradas de dispositivo onde os novos LUNs são mapeados como dispositivos MPIO utilizando o PCM predefinido.


. Para verificar se os dispositivos hdisk MPIO foram criados, digite o seguinte comando:
+
`lsdev -type disk`

+
Os LUNs aparecem no host como discos. Você pode usar esses discos da mesma maneira que usa discos locais no host.

+
Anote os números da instância do hdisk. Você os usa quando executa a configuração do caminho.

+
O `lsdev -type disk` comando produz o seguinte tipo de saída. A saída no exemplo a seguir é truncada.

+
[listing]
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----
. Para obter informações sobre a configuração, digite o seguinte comando:
+
`lsdev -dev hdisk_name -attr`

+
O `lsdev -dev hdisk_name -attr` comando produz a seguinte saída:

+
[listing]
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Se sua configuração não suportar ALUA, você deve executar o utilitário dotpaths para definir as prioridades do caminho. O utilitário dotpaths é instalado quando você instala os Utilitários do host. Não use o utilitário dotpaths se o ALUA estiver habilitado. Mude para o `oem_setup_env` modo para executar os dotpaths inserindo o seguinte comando:
+
`oem_setup_env`

+
Quando você entra `oem_setup_env` no modo, o prompt de linha de comando muda de um sinal de dólar para um sinal de libra e você permanece `oem_setup_env` no modo até que você o interrompa inserindo um comando como exit.

+
.Exemplo
``# vioserver$ oem_setup_env`

. Se a sua configuração suportar ALUA, você pode usá-la para definir a prioridade do caminho. Verifique se o ALUA está ativado:
+
`lun igroup show -instance igroup_name`

+
.. Se o ALUA não estiver ativado, ative-o:
+
`igroup set igroup_name alua yes`



. Se sua configuração não suportar ALUA, você deve executar o utilitário dotpaths para definir as prioridades do caminho. O utilitário dotpaths é instalado quando você instala os Utilitários do host. Não use o utilitário dotpaths se o ALUA estiver habilitado.
+
.. Para definir a prioridade para todos os LUNs Data ONTAP, introduza:
+
`dotpaths`

.. Para definir prioridade para um conjunto específico de disco, introduza:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Use a `-v` opção para ativar o modo verboso e exibir todas as prioridades. Use a `-q` opção para consultar todas as prioridades de disco ou individuais.

+
O seguinte é um exemplo de uso do utilitário dotpaths:

+
[listing]
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----


. Para verificar se o host descobriu os LUNs, digite o seguinte comando:
+
`# sanlun lun show -p`

+
.Exemplo
Este exemplo mostra a saída típica `sanlun lun show -p` do comando para uma configuração de conexão direta. Ele também inclui o `sanlun lun show -d hdisk9 -v` comando para exibir informações sobre hdisk9. A saída deste comando foi truncada.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
[listing]
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----

