---
sidebar: sidebar 
permalink: hu_citrix_84.html 
keywords: host utilities, citrix, Xenserver, 8 series, netapp, ontap, san, boot 
summary: Configure o Citrix Xenserver 8.4 para multipathing e com parâmetros e configurações específicos para operações de protocolo FCP e iSCSI com armazenamento ONTAP . 
---
= Configurar o Citrix Xenserver 8.4 para FCP e iSCSI com armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configure o Citrix Xenserver 8.4 para multipathing e com parâmetros e configurações específicos para operações de protocolo FCP e iSCSI com armazenamento ONTAP .

[NOTE]
====
O pacote de software Linux Host Utilities não oferece suporte aos sistemas operacionais Citrix Xenserver.

====


== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.

.Antes de começar
Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.

.Passos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crie um LUN de inicialização SAN e mapeie-o para o host"^].
. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Verifique se a configuração foi bem-sucedida reinicializando o host e verificando se o sistema operacional está funcionando.




== Etapa 2: confirme a configuração multipath para seu host

Você pode usar multipathing com o Citrix Xenserver 8.4 para gerenciar LUNs ONTAP .

Para garantir que o multipathing esteja configurado corretamente para o host, verifique se o `/etc/multipath.conf` arquivo está definido e se você tem as configurações recomendadas do NetApp configuradas para os LUNs do ONTAP.

.Passos
. Verifique se o  `/etc/multipath.conf` arquivo existe. Se o arquivo não existir, crie um arquivo vazio de zero bytes:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Na primeira vez que o `multipath.conf` arquivo é criado, talvez seja necessário ativar e iniciar os serviços multipath para carregar as configurações recomendadas:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Cada vez que você inicializar o host, o arquivo vazio de `/etc/multipath.conf` zero byte carrega automaticamente os parâmetros de multipath de host recomendados pelo NetApp como as configurações padrão. Você não deve precisar fazer alterações no `/etc/multipath.conf` arquivo para o seu host porque o sistema operacional do host é compilado com os parâmetros multipath que reconhecem e gerenciam LUNs ONTAP corretamente.
+
A tabela a seguir mostra as configurações de parâmetros multipath compilados pelo sistema operacional Linux nativo para LUNs ONTAP.

+
.Mostrar definições de parâmetros
[%collapsible]
====
[cols="2"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
====
. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
[source, cli]
----
/sbin/mpathutil list
----
+
Os parâmetros multipath padrão são compatíveis com configurações ASA, AFF e FAS. Nessas configurações, um único LUN ONTAP não deve exigir mais de quatro caminhos. Se houver mais de quatro caminhos, isso pode causar problemas com os caminhos durante uma falha de storage.

+
As saídas de exemplo a seguir mostram as configurações de parâmetro e o status do caminho corretos para LUNs ONTAP em uma configuração ASA, AFF ou FAS.

+
[role="tabbed-block"]
====
.Configuração ASA
--
Uma configuração do ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  |- 15:0:1:0  sdc  8:32    active ready running
  |- 16:0:0:0  sdcf 69:48   active ready running
  `- 16:0:1:0  sdcg 69:64   active ready running
----
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir exibe a saída de um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
/usr/sbin/mpathutil status
show topology
create: 3600a098038315045572b5930646f4b63 dm-1 NETAPP  ,LUN C-Mode
size=9.0G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 15:0:0:0  sdb  8:16    active ready running
  `- 15:0:1:0  sdc  8:32    active ready running
`-+- policy='service-time 0' prio=50 status=active
     |- 16:0:0:0  sdcf 69:48   active ready running
     `- 16:0:1:0  sdcg 69:64   active ready running
----
--
====




== Etapa 3: opcionalmente, exclua um dispositivo do multipathing

Se necessário, você pode excluir um dispositivo de multipathing adicionando o WWID para o dispositivo indesejado à estrofe "lista negra" para o `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" é o disco SCSI local que você deseja adicionar à lista negra.

+
Um exemplo WWID é `360030057024d0730239134810c0cb833`.

. Adicione o WWID à estrofe "blacklist":
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Etapa 4: personalizar parâmetros multicaminho para LUNs ONTAP

Se o seu host estiver conetado a LUNs de outros fornecedores e qualquer configuração de parâmetro multipath for substituída, você precisará corrigi-los adicionando estrofes posteriormente `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Se você não fizer isso, os LUNs do ONTAP podem não funcionar como esperado.

Verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações que possam estar substituindo o <<multipath-parameter-settings,configurações padrão para parâmetros multipath>>.


CAUTION: Não deve substituir as definições de parâmetros recomendadas para LUNs ONTAP. Essas configurações são necessárias para o desempenho ideal da configuração do seu host. Entre em Contato com o suporte da NetApp, seu fornecedor de sistemas operacionais ou ambos para obter mais informações.

O exemplo a seguir mostra como corrigir um padrão substituído. Neste exemplo, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP, e você não pode remover esses parâmetros porque os storages ONTAP ainda estão conetados ao host. Em vez disso, você corrige os valores `path_checker` de e `no_path_retry` adicionando uma estrofe de dispositivo ao `multipath.conf` arquivo que se aplica especificamente aos LUNs ONTAP.

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Etapa 5: Revise os problemas conhecidos

Não há problemas conhecidos.
