---
sidebar: sidebar 
permalink: hu_citrix_8x.html 
keywords: host utilities, citrix, hypervisor, 8.0, 8.1, 8.2, netapp, ontap, sanhost 
summary: Descreve como usar o Citrix Hypervisor 8.x com o ONTAP 
---
= Use o Citrix Hypervisor com o ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode configurar as configurações de host SAN ONTAP para as versões do sistema operacional Citrix Hypervisor série 8 com protocolos FC, FCoE e iSCSI.



== Inicialização de SAN

.O que você vai precisar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional do host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

Para o Citrix Hypervisor (CH) 8.x, o `/etc/multipath.conf` arquivo deve existir, mas você não precisa fazer alterações específicas no arquivo. O CH 8.x é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP. Você pode usar o `/sbin/mpathutil` comando status para verificar as configurações dos LUNs do ONTAP. As seções a seguir fornecem amostra de saída multipath para um LUN mapeado para personas do ASA.



=== Configuração de todas as matrizes SAN (ASA)

Para todas as configurações de storage SAN (ASA), deve haver um grupo de caminhos com prioridades únicas. Todos os caminhos são ativos/otimizados, o que significa que são atendidos pelo controlador e e/S é enviado em todos os caminhos ativos.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com quatro caminhos ativos/otimizados:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
....

NOTE: Não use um número excessivo de caminhos para um único LUN. Não mais de 4 caminhos devem ser necessários. Mais de 8 caminhos podem causar problemas de caminho durante falhas de storage.



=== Configuração sem ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com as prioridades mais altas são Ativo/otimizado, o que significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com as prioridades mais baixas estão ativos, mas não são otimizados porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
 |- 1:0:0:11   sde   8:64    active ready running
`- 12:0:8:11  sdua  66:544  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
   |- 1:0:9:11   sddo  71:96   active ready running
   `- 12:0:26:11 sdyt  129:720 active ready running
....

NOTE: Não use um número excessivo de caminhos para um único LUN. Não mais do que quatro caminhos devem ser necessários. Mais de oito caminhos podem causar problemas de caminho durante falhas de storage.



== Definições recomendadas

O sistema operacional Citrix Hypervisor 8.x é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP. Para o Citrix Hypervisor 8.x, um arquivo zerobyte vazio `/etc/multipath.conf` deve existir, mas você não precisa fazer alterações específicas no arquivo.

Ative o serviço multipath do host a partir do *XenCenter Management Portal* e verifique se o serviço multipath está ativado e em execução.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Não há necessidade de anexar conteúdo ao `/etc/multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou que você tenha configurações existentes que substituem os padrões. Você pode adicionar a seguinte sintaxe ao arquivo multipath.conf para excluir os dispositivos indesejados.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Substitua o *<DevID>* pela cadeia WWID do dispositivo que você deseja excluir.

.Exemplo
Neste exemplo para Citrix Hypervisor 8.x, `sda` é o disco SCSI local que precisamos adicionar à lista negra.

. Execute o seguinte comando para determinar o WWID:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Adicione este WWID à estrofe da lista negra no `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Consulte a configuração do tempo de execução do parâmetro multipath usando o `$multipathd show config` comando. Você deve sempre verificar a configuração em execução para configurações herdadas que podem estar substituindo as configurações padrão, especialmente na seção padrões.

A tabela a seguir mostra os parâmetros críticos *multipathd* para LUNs ONTAP e os valores necessários. Se um host estiver conetado a LUNs de outros fornecedores e qualquer um desses parâmetros for substituído, ele precisará ser corrigido por estrofes posteriores no *multipath.conf* que se aplicam especificamente aos LUNs ONTAP. Se isso não for feito, os LUNs do ONTAP podem não funcionar como esperado. Os padrões a seguir devem ser substituídos somente em consulta com o NetApp e/ou o fornecedor do sistema operacional e somente quando o impactos for totalmente compreendido.

[cols="2*"]
|===
| Parâmetro | Definição 


| `detect_prio` | sim 


| `dev_loss_tmo` | "infinito" 


| `failback` | imediato 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | "sim" 


| `hardware_handler` | "0" 


| `path_checker` | "tur" 


| `path_grouping_policy` | "group_by_prio" 


| `path_selector` | "tempo de serviço 0" 


| `polling_interval` | 5 


| `prio` | "ONTAP" 


| `product` | LUN.* 


| `retain_attached_hw_handler` | sim 


| `rr_weight` | "uniforme" 


| `user_friendly_names` | não 


| `vendor` | NetApp 
|===
.Exemplo
O exemplo a seguir ilustra como corrigir um padrão substituído. Neste caso, o arquivo *multipath.conf* define valores para *path_checker* e *Detect_prio* que não são compatíveis com LUNs ONTAP. Se eles não puderem ser removidos devido a outros arrays SAN conetados ao host, esses parâmetros podem ser corrigidos especificamente para LUNs ONTAP com uma estrofe de dispositivo.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: O Citrix Hypervisor recomenda o uso de ferramentas de VM Citrix para todas as VMs convidadas baseadas em Linux e Windows para uma configuração suportada.



== Problemas conhecidos

A versão do Citrix Hypervisor com ONTAP tem os seguintes problemas conhecidos:

[cols="4*"]
|===
| ID de erro do NetApp | Título | Descrição | ID do Citrix Tracker 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1242343["1242343"^] | Interrupção do kernel no Citrix Hypervisor 8,0 com QLogic QLE2742 32GB FC durante operações de failover de armazenamento | A interrupção do kernel pode ocorrer durante operações de failover de armazenamento no kernel Citrix Hypervisor 8,0 (4.19.0-1) com QLogic QLE2742 32GB HBA. Este problema solicita a reinicialização do sistema operacional e causa a interrupção do aplicativo. Se o kdump estiver configurado, a interrupção do kernel gera um arquivo vmcore no diretório /var/crash/. Você pode usar o arquivo vmcore para entender a causa da falha. Após a interrupção do kernel, você pode recuperar o sistema operacional reiniciando o sistema operacional host e reiniciando o aplicativo. | link:https://tracker.citrix.com/browse/NETAPP-98["NETAPP-98"^] 
|===