---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: Descreve como usar o Citrix XenServer 7.x com o ONTAP 
---
= Use o Citrix XenServer com ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode configurar as configurações de host SAN ONTAP para versões do sistema operacional Citrix XenServer série 7 com protocolos FC, FCoE e iSCSI.



== Inicialização de SAN

.O que você vai precisar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional do host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

O suporte de multipath no Citrix XenServer é baseado nos componentes Multipathd do Device Mapper. Os nós de mapeamento de dispositivos não são criados automaticamente para todos os LUNs apresentados ao XenServer e são provisionados somente quando os LUNs são usados ativamente pela camada de gerenciamento de storage (API). O plug-in da API do Citrix XenServer Storage Manager lida com a ativação e desativação automática de nós multipath.

Devido às incompatibilidades com a arquitetura de gerenciamento de múltiplos caminhos integrado, a Citrix recomenda que você use o aplicativo Citrix XenCenter para gerenciar a configuração de armazenamento. Se for necessário consultar manualmente o status das tabelas do Mapeador de dispositivos ou listar os nós multipath de mapper de dispositivos ativos no sistema, você pode usar o `/sbin/mpathutil status` comando para verificar as configurações dos LUNs do ONTAP. Para obter mais informações, consulte a documentação padrão do fornecedor do Citrix XenServer.



=== Configurações que não são ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com as prioridades mais altas são Ativo/otimizado, o que significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com as prioridades mais baixas estão ativos, mas não são otimizados porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: Não use um número excessivo de caminhos para um único LUN. Não mais do que quatro caminhos devem ser necessários. Mais de oito caminhos podem causar problemas de caminho durante falhas de storage.



=== Configuração de todas as matrizes SAN

Em todas as configurações de storage SAN (ASA), todos os caminhos para uma determinada unidade lógica (LUN) estão ativos e otimizados. Isso significa que a e/S pode ser servida por todos os caminhos ao mesmo tempo, permitindo assim um melhor desempenho.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com todos os quatro caminhos ativos/otimizados:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: Não use um número excessivo de caminhos para um único LUN. Não mais do que quatro caminhos devem ser necessários. Mais de oito caminhos podem causar problemas de caminho durante falhas de storage.



=== Definições recomendadas

O Citrix XenServer 7.x os é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP. Para o Citrix XenServer 7.x, um arquivo de zerobyte vazio `/etc/multipath.conf` deve existir, mas você não precisa fazer alterações específicas no arquivo.

Ative o serviço multipath do host a partir do *XenCenter Management Portal* e verifique se o serviço multipath está ativado e em execução.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
Não há necessidade de anexar conteúdo ao `/etc/multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou que você tenha configurações existentes que substituem os padrões. Você pode adicionar a seguinte sintaxe ao `multipath.conf` arquivo para excluir os dispositivos indesejados.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Substitua o *<DevID>* pela cadeia WWID do dispositivo que você deseja excluir.

.Exemplo
Neste exemplo para Citrix XenServer 7.x, `sda` é o disco SCSI local que precisamos adicionar à lista negra.

. Execute o seguinte comando para determinar o WWID:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Adicione este WWID à estrofe da lista negra no `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Consulte a configuração do tempo de execução do parâmetro multipath usando o `$multipathd show config` comando. Você deve sempre verificar a configuração em execução para configurações herdadas que podem estar substituindo as configurações padrão, especialmente na seção padrões.

A tabela a seguir mostra os parâmetros críticos *multipathd* para LUNs ONTAP e os valores necessários. Se um host estiver conetado a LUNs de outros fornecedores e qualquer um desses parâmetros for substituído, ele precisará ser corrigido por estrofes posteriores no *multipath.conf* que se aplicam especificamente aos LUNs ONTAP. Se isso não for feito, os LUNs do ONTAP podem não funcionar como esperado. Os padrões a seguir devem ser substituídos somente em consulta com o NetApp e/ou o fornecedor do sistema operacional e somente quando o impactos for totalmente compreendido.

[cols="2*"]
|===
| Parâmetro | Definição 


| `detect_prio` | sim 


| `dev_loss_tmo` | "infinito" 


| `failback` | imediato 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | "sim" 


| `hardware_handler` | "0" 


| `path_checker` | "tur" 


| `path_grouping_policy` | "group_by_prio" 


| `path_selector` | "tempo de serviço 0" 


| `polling_interval` | 5 


| `prio` | "ONTAP" 


| `product` | LUN.* 


| `retain_attached_hw_handler` | sim 


| `rr_weight` | "uniforme" 


| `user_friendly_names` | não 


| `vendor` | NetApp 
|===
.Exemplo
O exemplo a seguir ilustra como corrigir um padrão substituído. Neste caso, o arquivo *multipath.conf* define valores para *path_checker* e *Detect_prio* que não são compatíveis com LUNs ONTAP. Se eles não puderem ser removidos devido a outros arrays SAN conetados ao host, esses parâmetros podem ser corrigidos especificamente para LUNs ONTAP com uma estrofe de dispositivo.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: O Citrix XenServer recomenda o uso de ferramentas de VM Citrix para todas as VMs convidadas baseadas em Linux e Windows para uma configuração suportada.



== Problemas conhecidos

Não há problemas conhecidos para o Citrix XenServer com a versão ONTAP.
