---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Descreve como usar o IBM AIX 7,2 e/ou PowerVM VIOS 3,1 com o ONTAP 
---
= Configurar HP-UX 11i v3 para FCP e iSCSI com armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar as configurações do host SAN ONTAP para configurar o HP-UX 11i v3 com ONTAP como destino.

O software HP-UX Host Utilities fornece ferramentas de gerenciamento e diagnóstico para hosts HP-UX conectados ao armazenamento ONTAP .  Ao instalar o HP-UX Host Utilities em um host HP-UX 11i v3, você pode usá-lo para ajudar a gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP .



== Passo 1: Opcionalmente, ative a inicialização de SAN

Configure seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.  A inicialização SAN é o processo de configuração de um disco conectado à SAN (um LUN) como um dispositivo de inicialização para um host HP-UX.  Os utilitários de host oferecem suporte à inicialização SAN com protocolos FC e FCoE em ambientes HP-UX.

.Passos
. Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.
. Siga as práticas recomendadas para configurar uma inicialização SAN na documentação do fornecedor do HP-UX.




== Etapa 2: instalar os utilitários do host HP-UX

A NetApp recomenda fortemente a instalação do HP-UX Host Utilities para dar suporte ao gerenciamento de LUN do ONTAP e auxiliar o suporte técnico na coleta de dados de configuração.

link:hu_hpux_60.html["Instale os utilitários de host HP-UX 6,0"]



== Etapa 3: Confirme a configuração multipath do seu host

Use multipathing com o HP-UX 11i v3 para gerenciar LUNs ONTAP .  O multipathing permite que você configure vários caminhos de rede entre o host e o sistema de armazenamento.  Se um caminho falhar, o tráfego continua nos caminhos restantes.

Depois de instalar o HP-UX Host Utilities, verifique se você tem as configurações recomendadas da NetApp configuradas para seus LUNs ONTAP .

.Sobre esta tarefa
Os utilitários de host HP-UX oferecem suporte ao Native Microsoft Multipath I/O (MPIO) e ao Veritas Dynamic Multipathing.  As etapas a seguir são para a solução Native MPIO.

.Passos
. Quando você instala o HP-UX Host Utilities, as seguintes configurações padrão recomendadas são carregadas automaticamente para LUNs ONTAP .


.Mostrar definições de parâmetros
[%collapsible]
====
[cols="2*"]
|===
| Parâmetro | Usa o valor padrão 


| transient_secs | 120 


| leg_mpath_enable | VERDADEIRO 


| max_q_depth | 8 


| path_fail_secs | 120 


| load_bal_policy | Round_robin 


| lua_enabled | VERDADEIRO 


| esd_seg | 30 
|===
====
. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
[source, cli]
----
sanlun lun show
----
+
Os parâmetros multipath padrão suportam configurações ASA, AFF e FAS .  Os exemplos de saída a seguir mostram as configurações corretas dos parâmetros e o status do caminho para LUNs ONTAP em uma configuração ASA, AFF ou FAS .

+
[role="tabbed-block"]
====
.Configuração ASA
--
Uma configuração do ASA otimiza todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
--
.Configuração AFF ou FAS
--
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

O exemplo a seguir exibe a saída de um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
--
====




== Etapa 4: Revise os problemas conhecidos

A versão HP-UX 11i v3 com armazenamento ONTAP apresenta os seguintes problemas conhecidos:

[cols="4*"]
|===
| ID de erro do NetApp | Título | Descrição | ID do parceiro 


| 1447287 | O evento AUFO no cluster mestre isolado na configuração de sincronização ativa do SnapMirror causa interrupções temporárias no host HP-UX | Esse problema ocorre quando há um evento de failover não planejado automático (AUFO) no cluster mestre isolado na configuração de sincronização ativa do SnapMirror. Pode levar mais de 120 segundos para que a e/S seja retomada no host HP-UX, mas isso pode não causar interrupções ou mensagens de erro de e/S. Esse problema causa falha de evento duplo porque a conexão entre o cluster primário e o cluster secundário é perdida e a conexão entre o cluster primário e o mediador também é perdida. Este é considerado um evento raro, ao contrário de outros eventos AUFO. | NA 


| 1344935 | Host HP-UX 11,31 informando intermitentemente o status do caminho incorretamente na configuração do ASA. | Problemas de geração de relatórios de caminho com a configuração do ASA. | NA 


| 1306354 | A criação HP-UX LVM envia e/S de tamanho de bloco acima de 1MB | O comprimento máximo de transferência de SCSI de 1 MB é aplicado no ONTAP All SAN Array. Para restringir o comprimento máximo de transferência de hosts HP-UX quando conetado a ONTAP All SAN Array, é necessário definir o tamanho máximo de e/S permitido pelo subsistema HP-UX SCSI para 1 MB. Consulte a documentação do fornecedor HP-UX para obter detalhes. | NA 
|===


== O que vem a seguir

link:hu_hpux_60_cmd.html["Saiba mais sobre como usar a ferramenta HP-UX Host Utilities"] .
