---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Descreve como utilizar os utilitários de anfitrião HP-UX 6,0 com armazenamento ONTAP 
---
= Instale os utilitários de host HP-UX 6,0 para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os utilitários de host HP-UX ajudam você a gerenciar o armazenamento ONTAP conectado a um host HP-UX.  A NetApp recomenda fortemente a instalação do HP-UX Host Utilities, mas não é obrigatório.  Os utilitários melhoram o gerenciamento e auxiliam o suporte ao cliente da NetApp a coletar informações sobre sua configuração.

Os utilitários de host HP-UX oferecem suporte aos seguintes ambientes:

* E/S de múltiplos caminhos da Microsoft (MPIO) nativo
* Veritas Dynamic Multipathing (DMP)


.Antes de começar
Para uma operação confiável, use o https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se sua configuração iSCSI, FC ou FCoE é suportada.

.Passos
. Efetue login no seu host HP-UX.
. Transfira o ficheiro HP-UX Host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` do link:https://mysupport.netapp.com/site/["Site de suporte da NetApp"^] para o seu anfitrião HP-UX.
. Descomprimir o `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` ficheiro:
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
O sistema coloca o software extraído no diretório onde você descompactou o arquivo do depósito.

. Instale o software:
+
[source, cli]
----
swinstall -s /depot_path
----
+
`depot_path` fornece o caminho e o nome do arquivo do depósito.

+
O `swinstall` comando executa um script de instalação que verifica o status da configuração do HP-UX. Se o sistema atender aos requisitos, esse script instala o `sanlun` utilitário e os scripts de diagnóstico no `/opt/NetApp/santools/bin` diretório.

. Verifique a instalação:
+
[source, cli]
----
sanlun version
----




== O que se segue?

link:hu-hpux-sanlun-toolkit.html["Saiba mais sobre o SAN Toolkit"] .
