---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: Descreve como usar o Oracle Linux 7,6 com ONTAP 
---
= Use o Oracle Linux 7,6 com ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar as configurações de host SAN ONTAP para configurar o Oracle Linux 7,6 com ONTAP como destino.



== Instale os utilitários do host unificado do Linux

O pacote de software Utilitários de host unificado do NetApp Linux está disponível no link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^]em um arquivo .rpm de 32 e 64 bits. Se não souber qual é o ficheiro adequado para a sua configuração, utilize o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar qual necessita.

O NetApp recomenda fortemente a instalação dos Utilitários de host unificado do Linux, mas não é obrigatório. Os utilitários não alteram nenhuma configuração em seu host Linux. Os utilitários melhoram o gerenciamento e auxiliam o suporte ao cliente da NetApp na coleta de informações sobre sua configuração.

Se você tiver uma versão do Linux Unified Host Utilities atualmente instalada, você deve atualizá-la ou removê-la e seguir estas etapas para instalar a versão mais recente.

.Passos
. Faça o download do pacote de software Linux Unified Host Utilities de 32 ou 64 bits do link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^]site para o seu host.
. Use o seguinte comando para instalar o pacote de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Pode utilizar as definições de configuração fornecidas neste documento para configurar os clientes em nuvem ligados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de ferramentas SAN

O kit de ferramentas é instalado automaticamente quando você instala o pacote de utilitários de host do NetApp. Este kit fornece o `sanlun` utilitário, que ajuda você a gerenciar LUNs e HBAs. O `sanlun` comando retorna informações sobre os LUNs mapeados para o seu host, multipathing e informações necessárias para criar grupos de iniciadores.

.Exemplo
No exemplo a seguir, o `sanlun lun show` comando retorna informações de LUN.

[source, cli]
----
# sanlun lun show all
----
Exemplo de saída:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Inicialização de SAN

.O que você vai precisar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://mysupport.netapp.com/matrix/imt.jsp?components=86309;&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional do host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

Para o Oracle Linux 7,6 o arquivo /etc/multipath.conf deve existir, mas você não precisa fazer alterações específicas no arquivo. O Oracle Linux 7,6 é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP.

Você pode usar o `multipath -ll` comando para verificar as configurações dos LUNs do ONTAP. Deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com prioridades mais altas são Ativo/otimizado, o que significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com prioridades mais baixas estão ativos, mas não são otimizados porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



== Definições recomendadas

O sistema operacional Oracle Linux 7,6 é compilado para reconhecer LUNs ONTAP e definir automaticamente todos os parâmetros de configuração corretamente. O `multipath.conf` arquivo deve existir para o daemon multipath iniciar. Se este arquivo não existir, você pode criar um arquivo vazio, zero-byte usando o `touch /etc/multipath.conf` comando

Na primeira vez que você criar o `multipath.conf` arquivo, talvez seja necessário habilitar e iniciar os serviços multipath usando os seguintes comandos:

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

Não é necessário adicionar nada diretamente ao `multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou tenha configurações existentes que substituem os padrões. Para excluir dispositivos indesejados, adicione a seguinte sintaxe ao `multipath.conf` arquivo, substituindo o <DevId> pela cadeia WWID do dispositivo que você deseja excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
O exemplo a seguir determina o WWID de um dispositivo e o adiciona ao `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` É o disco SCSI local que você deseja adicionar à lista negra.

. Adicione a `WWID` à estrofe da lista negra no `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Você deve sempre verificar seu `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações herdadas que podem substituir as configurações padrão.

A tabela a seguir demonstra os parâmetros críticos `multipathd` para LUNs ONTAP e a configuração necessária. Se um host estiver conetado a LUNs de outros fornecedores e qualquer um desses parâmetros for substituído, ele precisará ser corrigido por estrofes posteriores `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Sem essa correção, os LUNs ONTAP podem não funcionar como esperado. Você só deve substituir esses padrões em consulta com o NetApp, o fornecedor do sistema operacional ou ambos, e apenas quando o impactos for totalmente compreendido.

[cols="2*"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN.* 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
.Exemplo
O exemplo a seguir mostra como corrigir um padrão substituído. Nesse caso, o `multipath.conf` arquivo define valores para `path_checker` e `detect_prio` que não são compatíveis com LUNs ONTAP. Se eles não puderem ser removidos devido a outros arrays SAN ainda conetados ao host, esses parâmetros podem ser corrigidos especificamente para LUNs ONTAP com uma estrofe de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Para configurar o Oracle Linux 7,6 Red Hat Enterprise Kernel (RHCK), use o link:hu_rhel_76.html#recommended-settings["definições recomendadas"] para Red Hat Enterprise Linux (RHEL) 7,6.



== Problemas conhecidos

O Oracle Linux 7,6 com ONTAP tem os seguintes problemas conhecidos:

[cols="3*"]
|===
| ID de erro do NetApp | Título | Descrição 


| 1440718 | Se você desmarcar ou mapear um LUN sem executar uma nova digitalização SCSI, isso pode levar à corrupção de dados no host. | Quando você define o parâmetro de configuração multipath 'testable_changed_wwwids' como SIM, ele desativa o acesso ao dispositivo de caminho no caso de uma alteração WWID. O multipath desativará o acesso ao dispositivo de caminho até que o WWID do caminho seja restaurado para o WWID do dispositivo multipath. Para saber mais, link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de dados de Conhecimento da NetApp: A corrupção do sistema de arquivos no iSCSI LUN no Oracle Linux 7"^]consulte . 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | Os LUNs podem não estar disponíveis durante a descoberta do host devido ao estado "não presente" de portas remotas em um host OL7U6 com adaptador QLogic QLE2742 | Durante a descoberta do host, o status das portas remotas Fibre Channel (FC) em um host OL7U6 com um adaptador QLogic QLE2742 pode entrar no estado "não presente". Portas remotas com um estado "não presente" podem fazer com que os caminhos para LUNs fiquem indisponíveis. Durante o failover de storage, a redundância de caminho pode ser reduzida e resultar em uma interrupção de e/S. Você pode verificar o status da porta remota digitando o seguinte comando: Cat /sys/class/fc_Remote_ports/rport-*/port_State o seguinte é um exemplo da saída que é exibida: Online Online não presente Online 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | A interrupção do kernel ocorre no Oracle Linux 7,6 executando com Qlogic(QLE2672) 16GB FC HBA durante operações de failover de armazenamento | Durante as operações de failover de armazenamento no Oracle Linux 7,6 com um adaptador de barramento de host (HBA) Qlogic QLE2672 Fibre Channel (FC), uma interrupção do kernel ocorre devido a um pânico no kernel. O pânico do kernel faz com que o Oracle Linux 7,6 seja reiniciado, o que leva a uma interrupção do aplicativo. Se o mecanismo kdump estiver ativado, o kernel panic gera um arquivo vmcore localizado no diretório /var/crash/. Você pode analisar o arquivo vmcore para determinar a causa do pânico. Após a interrupção do kernel, você pode reiniciar o sistema operacional do host e recuperar o sistema operacional e, em seguida, você pode reiniciar quaisquer aplicativos conforme necessário. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | A interrupção do kernel pode ocorrer no Oracle Linux 7,6 executando com Qlogic(QLE2742) 32GB FC HBA durante operações de failover de armazenamento | Durante operações de failover de armazenamento no Oracle Linux 7,6 com um adaptador de barramento de host (HBA) Fibre Channel (FC) Qlogic QLE2742, uma interrupção do kernel pode ocorrer devido a um pânico no kernel. O pânico do kernel faz com que o Oracle Linux 7,6 seja reiniciado, o que leva a uma interrupção do aplicativo. Se o mecanismo kdump estiver ativado, o kernel panic gera um arquivo vmcore localizado no diretório /var/crash/. Você pode analisar o arquivo vmcore para determinar a causa do pânico. Após a interrupção do kernel, você pode reiniciar o sistema operacional do host e recuperar o sistema operacional e, em seguida, você pode reiniciar quaisquer aplicativos conforme necessário. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | A interrupção do kernel pode ocorrer no Oracle Linux 7,6 executando com Emulex (LPe32002-M2)32GB FC HBA durante operações de failover de armazenamento | Durante operações de failover de armazenamento no Oracle Linux 7,6 com um adaptador de barramento de host (HBA) Fibre Channel (FC) Emulex LPe32002-M2, uma interrupção do kernel pode ocorrer devido a um pânico no kernel. O pânico do kernel faz com que o Oracle Linux 7,6 seja reiniciado, o que leva a uma interrupção do aplicativo. Se o mecanismo kdump estiver ativado, o kernel panic gera um arquivo vmcore localizado no diretório /var/crash/. Você pode analisar o arquivo vmcore para determinar a causa do pânico. Após a interrupção do kernel, você pode reiniciar o sistema operacional do host e recuperar o sistema operacional e, em seguida, você pode reiniciar quaisquer aplicativos conforme necessário. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | Nenhum progresso de e/S no Oracle Linux 7,6 com kernel UEK5U2, sendo executado com um HBA FC Emulex LPe16002B-M6 16G durante operações de failover de armazenamento | Durante as operações de failover de armazenamento no Oracle Linux 7,6 com o kernel UEK5U2 executado com um adaptador de barramento de host (HBA) Fibre Channel (FC) Emulex LPe16002B-M6 16G, o progresso da e/S pode parar devido ao bloqueio dos relatórios. Os relatórios de operação de failover de armazenamento mudam de um estado "online" para um estado "bloqueado", causando um atraso nas operações de leitura e gravação. Depois que a operação for concluída com êxito, os relatórios não conseguem voltar para um estado "online" e continuam a permanecer no estado "bloqueado". 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Status da porta remota no host QLogic QLE2672 16G bloqueado durante operações de failover de armazenamento | As portas remotas Fibre Channel (FC) podem estar bloqueadas no Red Hat Enterprise Linux (RHEL) 7,6 com o host QLogic QLE2672 16G durante operações de failover de armazenamento. Como as interfaces lógicas ficam inativas quando um nó de storage está inativo, as portas remotas definem o status do nó de storage como bloqueado. O progresso de e/S pode parar devido às portas bloqueadas se você estiver executando um host QLogic QLE2672 16G e um adaptador de barramento de host (HBA) Fibre Channel (FC) de QLE2742 32GB GB. Quando o nó de storage retorna ao seu estado ideal, as interfaces lógicas também aparecem e as portas remotas devem estar on-line. No entanto, as portas remotas ainda podem estar bloqueadas. Esse estado bloqueado Registra como falha em LUNS na camada multipath. Você pode verificar o estado das portas remotas com o seguinte comando: Cat /sys/class/fc_Remote_ports/rport-*/port_stat você deve ver a seguinte saída: Bloqueado bloqueado bloqueado bloqueado Online 
|===