---
sidebar: sidebar 
permalink: hu_ol_83.html 
keywords: host utilities, oracle, linux, 8.3, netapp, ontap 
summary: Descreve como usar o Oracle Linux 8,3 com ONTAP 
---
= Use o Oracle Linux 8,3 com ONTAP
:hardbreaks:
:toclevels: 1P
:allow-uri-read: 
:toclevels: 1P
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar as configurações de host SAN ONTAP para configurar o Oracle Linux 8,3 com ONTAP como destino.



== Instale os utilitários do host unificado do Linux

Você pode baixar o pacote de software Utilitários unificados de host do NetApp Linux como um arquivo 64-bit.rpm do link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^].

O NetApp recomenda fortemente a instalação dos Utilitários de host unificado do Linux, mas não é obrigatório. Os utilitários não alteram nenhuma configuração em seu host Linux. Os utilitários melhoram o gerenciamento e auxiliam o suporte ao cliente da NetApp na coleta de informações sobre sua configuração.

.Passos
. Baixe o pacote de software Linux Unified Host Utilities de 64 bits do https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^] para o seu host.
. Instale o pacote de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Pode utilizar as definições de configuração fornecidas neste documento para configurar os clientes em nuvem ligados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de ferramentas SAN

O kit de ferramentas é instalado automaticamente quando você instala o pacote de utilitários de host do NetApp. Este kit fornece o `sanlun` utilitário, que ajuda você a gerenciar LUNs e HBAs. O `sanlun` comando retorna informações sobre os LUNs mapeados para o seu host, multipathing e informações necessárias para criar grupos de iniciadores.

.Exemplo
No exemplo a seguir, o `sanlun lun show` comando retorna informações de LUN.

[source, cli]
----
# sanlun lun show all
----
Exemplo de saída:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Inicialização de SAN

.O que você vai precisar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://mysupport.netapp.com/matrix/imt.jsp?components=91863;&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

Para Oracle Linux (OL) 8,3 o arquivo /etc/multipath.conf deve existir, mas você não precisa fazer alterações específicas no arquivo. O OL 8,3 é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP.

Você pode usar o `multipath -ll` comando para verificar as configurações dos LUNs do ONTAP.

As seções a seguir fornecem exemplos de saídas multipath para um LUN mapeado para personas não-ASA.



=== Configurações que não são ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com prioridades mais altas são Ativo/otimizado, o que significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com prioridades mais baixas estão ativos, mas não são otimizados porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados.

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb 69:624 active ready running
| |- 16:0:5:35 sdun 66:752 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj 66:48 active ready running
|- 15:0:1:35 sdbx 68:176 active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



=== Todas as configurações do SAN Array

Todas as configurações de SAN Array (ASA) otimizam todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP.

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6   sdbz 68:208  active ready running
  |- 11:0:11:6  sddn 71:80   active ready running
  |- 11:0:15:6  sdfb 129:208 active ready running
  `- 12:0:1:6   sdgp 132:80  active ready running
----

NOTE: Não use um número excessivo de caminhos para um único LUN. Não mais de 4 caminhos devem ser necessários. Mais de 8 caminhos podem causar problemas de caminho durante falhas de storage.



== Definições recomendadas

O sistema operacional Oracle Linux 8,3 é compilado para reconhecer LUNs ONTAP e definir automaticamente todos os parâmetros de configuração corretamente para configurações ASA e não-ASA.

O `multipath.conf` arquivo deve existir para o daemon multipath iniciar. Se este arquivo não existir, você pode criar um arquivo vazio, zero-byte usando o `touch /etc/multipath.conf` comando.

Na primeira vez que você criar o `multipath.conf` arquivo, talvez seja necessário habilitar e iniciar os serviços multipath usando os seguintes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Não é necessário adicionar nada diretamente ao `multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou tenha configurações existentes que substituem os padrões. Para excluir dispositivos indesejados, adicione a seguinte sintaxe ao `multipath.conf` arquivo, substituindo <DevId> pela cadeia de carateres identificador mundial (WWID) do dispositivo que você deseja excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
O exemplo a seguir determina o WWID de um dispositivo e o adiciona ao `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
/lib/udev/scsi_id -gud /dev/sda
----
+
360030057024d0730239134810c0cb833



[listing]
----
+
`sda` is the local SCSI disk that you want to add to the blacklist.

. Add the `WWID` to the blacklist stanza in `/etc/multipath.conf`:
[source,cli]
+
----
se não 0 for o caso 9, não é necessário utilizar o sistema de controlo de qualidade, o sistema de controlo de qualidade de imagem do sistema de controlo de qualidade de imagem. o sistema de controlo de qualidade de imagem do sistema de controlo de qualidade de imagem do sistema de controlo de qualidade de imagem do sistema de controlo de qualidade de imagem (por exemplo, o sistema de controlo de velocidade de navegação). Selecione

[listing]
----

Always check your `/etc/multipath.conf` file, especially in the defaults section, for legacy settings that might be overriding default settings.

The following table demonstrates the critical `multipathd` parameters for ONTAP LUNs and the required values. If a host is connected to LUNs from other vendors and any of these parameters are overridden, they must be corrected by later stanzas in the `multipath.conf` file that apply specifically to ONTAP LUNs. Without this correction, the ONTAP LUNs might not work as expected. You should only override these defaults in consultation with NetApp, the OS vendor, or both, and only when the impact is fully understood.

//ONTAPDOC-2578 9-Dec-2024
//ONTAPDOC-2561 25-Nov-202


[cols=2*,options="header"]
|===
| Parameter
| Setting
| detect_prio | yes
| dev_loss_tmo | infinity
| failback | immediate
| fast_io_fail_tmo | 5
| features | 2 pg_init_retries 50
| flush_on_last_del | yes
| hardware_handler | 0
| no_path_retry | queue
| path_checker | tur
| path_grouping_policy | group_by_prio
| path_selector | service-time 0
| polling_interval | 5
| prio | ontap
| product | LUN.*
| retain_attached_hw_handler | yes
| rr_weight | uniform
| user_friendly_names | no
| vendor | NETAPP
|===

.Example

The following example shows how to correct an overridden default. In this case, the `multipath.conf` file defines values for `path_checker` and `no_path_retry` that are not compatible with ONTAP LUNs. If they cannot be removed because of other SAN arrays still attached to the host, these parameters can be corrected specifically for ONTAP LUNs with a device stanza.

----
Clique em "NetApp" product "LUN.*" no_path_retry queue path_checker tur." no_path_retry queue path_checker tur readsector0

[listing]
----

NOTE: To configure Oracle Linux 8.3 Red Hat Enterprise Kernel (RHCK), use the link:hu_rhel_83.html#recommended-settings[recommended settings] for Red Hat Enterprise Linux (RHEL) 8.3.

== Known issues

There are no known issues for the Oracle Linux 8.3 with ONTAP release.

NOTE: For Oracle Linux (Red Hat compatible kernel) known issues, see the link:hu_rhel_83.html#known-problems-and-limitations[known issues] section in the corresponding Red Hat Enterprise Linux release documentation.
----