---
sidebar: sidebar 
permalink: hu_ol_70.html 
keywords: host utilities, oracle, linux, 7.0, netapp, ontap 
summary: Instale o Linux Host Utilities em um host Oracle Linux 7.0 para gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP. 
---
= Configurar o Oracle Linux 7.0 para FCP e iSCSI com armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O software Utilitários de host Linux fornece ferramentas de gerenciamento e diagnóstico para hosts Linux que estão conetados ao storage ONTAP. Ao instalar o Linux Host Utilities em um host Oracle Linux 7.0, você pode usá-lo para ajudar a gerenciar operações de protocolo FCP e iSCSI com LUNs ONTAP.


NOTE: Você não precisa configurar manualmente as definições da Máquina Virtual baseada em Kernel (KVM) porque os LUNs ONTAP são mapeados automaticamente para o hipervisor.



== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.

.Antes de começar
Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.

.Passos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Crie um LUN de inicialização SAN e mapeie-o para o host"^].
. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Verifique se a configuração foi bem-sucedida reinicializando o host e verificando se o sistema operacional está funcionando.




== Passo 2: Instale os Utilitários de host do Linux

A NetApp recomenda fortemente a instalação dos utilitários de host Linux para suportar o gerenciamento de LUN ONTAP e auxiliar o suporte técnico na coleta de dados de configuração.

link:hu_luhu_71.html["Instale o Linux Host Utilities 7,1"].


NOTE: A instalação dos Utilitários de host do Linux não altera nenhuma configuração de tempo limite do host no seu host Linux.



== Etapa 3: Confirme a configuração multipath do seu host

Você pode usar multipathing com o Oracle Linux 7,0 para gerenciar LUNs ONTAP. O Oracle Linux 7,0 suporta Unbreakable Enterprise Kernel (UEK) R3 e UEK R4. O sistema operacional inicializa com o kernel UEK R3 por padrão


NOTE: Você pode usar o link:hu_rhel_70.html#rhel-rhck["configurações recomendadas para Red Hat Enterprise Linux (RHEL) 7.0"] para configurar o Red Hat Compatible Kernel para Oracle Linux 7.0.

.Passos
Dependendo da sua configuração, selecione a aba UEK 3 ou UEK 4.

[role="tabbed-block"]
====
.UEK 3
--
As configurações do Oracle Linux UEK 3 com e sem ALUA são atualizadas automaticamente. Após a atualização das configurações, você precisa habilitar o "ALUA Handler":

. Crie um backup da imagem initrd.
. Adicione o seguinte valor de parâmetro ao kernel para que ALUA e não ALUA funcionem:
+
[source, cli]
----
rdloaddriver=scsi_dh_alua
----
+
.Exemplo de saída
[listing]
----
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
----
. Recrie a imagem initrd:
+
[source, cli]
----
dracut -f
----
. Reinicie o host.
. Revise a saída do  `cat /proc/cmdline` comando para verificar se a configuração está completa.


--
.UEK 4
--
Para Oracle Linux UEK 4, verifique se o  `/etc/multipath.conf` arquivo está definido e que as configurações recomendadas da NetApp estão configuradas para seus LUNs ONTAP.

. Verifique se o `/etc/multipath.conf` arquivo sai. Se o arquivo não existir, crie um arquivo vazio de zero bytes:
+
[source, cli]
----
touch /etc/multipath.conf
----
. Na primeira vez que o `multipath.conf` arquivo é criado, talvez seja necessário ativar e iniciar os serviços multipath para carregar as configurações recomendadas:
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Cada vez que você inicializar o host, o arquivo vazio de `/etc/multipath.conf` zero byte carrega automaticamente os parâmetros de multipath de host recomendados pelo NetApp como as configurações padrão. Você não deve precisar fazer alterações no `/etc/multipath.conf` arquivo para o seu host porque o sistema operacional é compilado com os parâmetros multipath que reconhecem e gerenciam LUNs ONTAP corretamente.
+
.Mostrar definições de parâmetros
[%collapsible]
=====
[cols="2"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "2 pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
=====
. Verifique as configurações de parâmetros e o status do caminho para os LUNs do ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Os parâmetros padrão de multipath suportam configurações AFF e FAS . Nessas configurações, um único LUN ONTAP não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas durante uma falha de armazenamento.

+
Uma configuração AFF ou FAS deve ter dois grupos de caminhos com prioridades maiores e menores. Os caminhos ativos/otimizados de prioridade mais alta são servidos pelo controlador onde o agregado está localizado. Os caminhos de prioridade mais baixa estão ativos, mas não otimizados, porque são servidos por um controlador diferente. Caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

+
Os exemplos de saída a seguir mostram as configurações corretas dos parâmetros e o status do caminho para LUNs ONTAP em uma configuração AFF ou FAS com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

+
.Mostrar exemplo
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
====


== Passo 4: Opcionalmente, exclua um dispositivo de multipathing

Se necessário, você pode excluir um dispositivo de multipathing adicionando o WWID para o dispositivo indesejado à estrofe "lista negra" para o `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
"sda" é o disco SCSI local que você deseja adicionar à lista negra.

+
Um exemplo WWID é `360030057024d0730239134810c0cb833`.

. Adicione o WWID à estrofe "blacklist":
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Etapa 5: Personalizar parâmetros multipath para LUNs ONTAP

Se o seu host estiver conetado a LUNs de outros fornecedores e qualquer configuração de parâmetro multipath for substituída, você precisará corrigi-los adicionando estrofes posteriormente `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Se você não fizer isso, os LUNs do ONTAP podem não funcionar como esperado.

Verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações que possam estar substituindo o <<multipath-parameter-settings,configurações padrão para parâmetros multipath>>.


CAUTION: Não deve substituir as definições de parâmetros recomendadas para LUNs ONTAP. Essas configurações são necessárias para o desempenho ideal da configuração do seu host. Entre em Contato com o suporte da NetApp, seu fornecedor de sistemas operacionais ou ambos para obter mais informações.

O exemplo a seguir mostra como corrigir um padrão substituído. Neste exemplo, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP, e você não pode remover esses parâmetros porque os storages ONTAP ainda estão conetados ao host. Em vez disso, você corrige os valores `path_checker` de e `no_path_retry` adicionando uma estrofe de dispositivo ao `multipath.conf` arquivo que se aplica especificamente aos LUNs ONTAP.

.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Passo 6: Revise os problemas conhecidos

O host Oracle Linux 7.0 com armazenamento ONTAP tem os seguintes problemas conhecidos:

[cols="3*"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=901558["901558"^] | OL7,0 : o host perde todos os caminhos para o lun e trava devido ao erro "tempo limite RSCN" no OL 7,0 UEK r3U5 Beta no host Emulex 8G(LPe12002) | Você pode observar que o host Emulex 8G(LPe12002) trava e há uma alta interrupção de e/S durante operações de failover de storage com e/S. Você pode observar caminhos que não estão se recuperando, o que é um resultado do tempo limite do RSCN, devido ao qual o host perde todos os caminhos e trava. A probabilidade de atingir este problema é alta. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=901557["901557"^] | OL 7,0: Alta interrupção de e/S observada no host SAN QLogic 8G FC (QLE2562) durante operações de failover de storage com e/S. | É possível observar alta interrupção de e/S no host QLogic 8G FC (QLE2562) durante operações de failover de storage com e/S. Aborts e Device resets manifesta-se como interrupção de e/S no host. A probabilidade de atingir essa interrupção de e/S é alta. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894766["894766"^] | OL7,0: O Dracut falha em incluir o módulo scsi_DH_alua.ko em initramfs no UEKR3U5 alpha | O módulo scsi_DH_alua pode não carregar mesmo depois de adicionar o parâmetro "rdloaddriver_scsi_DH_alua" na linha de comando do kernel e criar Dracut. Como resultado, o ALUA não está habilitado para LUNs NetApp, conforme recomendado. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894796["894796"^] | O Anaconda exibe uma mensagem de falha de login iSCSI, embora os logins sejam bem-sucedidos durante a instalação do SO OL 7,0 | Quando você está instalando OL 7,0, a tela de instalação do anaconda exibe que o login iSCSI em vários IPs de destino falhou, embora os logins iSCSI sejam bem-sucedidos. O Anaconda exibe a seguinte mensagem de erro: "Nó Login falhou" você observará este erro somente quando você selecionar vários IPs de destino para login iSCSI. Você pode continuar a instalação do sistema operacional clicando no botão "ok". Este erro não dificulta a instalação do sistema operacional iSCSI ou OL 7,0. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894771["894771"^] | OL7,0 : o Anaconda não adiciona argumento bootdev na linha cmd do kernel para definir o endereço IP para a instalação do SO SANboot iSCSI | O Anaconda não adiciona um argumento bootdev na linha de comando do kernel onde você define o endereço IPv4 durante a instalação do OL 7,0 os em um LUN iSCSI multipath. Devido a isso, você não pode atribuir endereços IP a nenhuma das interfaces Ethernet que foram configuradas para estabelecer sessões iSCSI com o subsistema de armazenamento durante a inicialização OL 7,0. Como as sessões iSCSI não são estabelecidas, o LUN raiz não é descoberto quando o sistema operacional é inicializado e, portanto, a inicialização do sistema operacional falha. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=916501["916501"^] | Falha do kernel do host QLogic 10G FCoE (QLE8152) observada durante operações de failover de armazenamento com e/S. | Você pode observar uma falha do kernel no módulo de driver Qlogic no host 10G FCoE Qlogic (QLE8152). A falha ocorre durante operações de failover de storage com e/S.. A probabilidade de atingir essa falha é alta, o que leva a uma maior interrupção de e/S no host. 
|===


== O que se segue?

* link:hu-luhu-command-reference.html["Saiba mais sobre como usar a ferramenta Linux Host Utilities"] .
* Saiba mais sobre o espelhamento ASM.
+
O espelhamento do Gerenciamento Automático de armazenamento (ASM) pode exigir alterações nas configurações de multipath do Linux para permitir que o ASM reconheça um problema e alterne para um grupo de falhas alternativo. A maioria das configurações ASM no ONTAP usa redundância externa, o que significa que a proteção de dados é fornecida pelo array externo e o ASM não espelha dados. Alguns sites usam ASM com redundância normal para fornecer espelhamento bidirecional, normalmente em diferentes sites. link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bancos de dados Oracle no ONTAP"^]Consulte para obter mais informações.


