---
sidebar: sidebar 
permalink: hu_rhel_70.html 
keywords: host utilities, red hat, rhel, linux, 7.0, netapp, ontap 
summary: Descreve como usar o Red Hat Enterprise Linux 7,0 com o ONTAP 
---
= Use o Red Hat Enterprise Linux 7,0 com ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar as configurações de host SAN ONTAP para configurar o Red Hat Enterprise Linux 7,0 com ONTAP como destino.



== Instale os Utilitários de host do Linux

O pacote de software de utilitários de host NetApp está disponível no link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^]em um arquivo .rpm de 32 e 64 bits. Se não souber qual é o ficheiro adequado para a sua configuração, utilize o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar qual necessita.

O NetApp recomenda fortemente a instalação dos utilitários de host do Linux, mas não é obrigatório. Os utilitários não alteram nenhuma configuração em seu host Linux. Os utilitários melhoram o gerenciamento e auxiliam o suporte ao cliente da NetApp na coleta de informações sobre sua configuração.

Se você tiver Linux Host Utilities atualmente instalado, você deve atualizá-lo para a versão mais recente ou removê-lo e siga estas etapas para instalar a versão mais recente.

.Passos
. Baixe o pacote de software Linux Host Utilities de 32 ou 64 bits do link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^] para o seu host.
. Instale o pacote de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Pode utilizar as definições de configuração fornecidas neste procedimento para configurar os clientes em nuvem ligados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de ferramentas SAN

O kit de ferramentas é instalado automaticamente quando você instala o pacote de utilitários de host do NetApp. Este kit fornece o `sanlun` utilitário, que ajuda você a gerenciar LUNs e HBAs. O `sanlun` comando retorna informações sobre os LUNs mapeados para o seu host, multipathing e informações necessárias para criar grupos de iniciadores.

.Exemplo
No exemplo a seguir, o `sanlun lun show` comando retorna informações de LUN.

[source, cli]
----
# sanlun lun show all
----
Exemplo de saída:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Inicialização de SAN

.Antes de começar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional do host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

Para Red Hat Enterprise Linux (RHEL) 7,0 o arquivo /etc/multipath.conf deve existir, mas você não precisa fazer alterações específicas no arquivo. O RHEL 7,0 é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP.

Você pode usar o `multipath -ll` comando para verificar as configurações dos LUNs do ONTAP.

As seções a seguir fornecem exemplos de saídas multipath para um LUN mapeado para personas ASA e não ASA.



=== Todas as configurações do SAN Array

Todas as configurações de SAN Array (ASA) otimizam todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G  features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



=== Configurações que não são ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com prioridades mais altas são Ativo/otimizado. Isso significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com prioridades mais baixas estão ativos, mas não otimizados, porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle’ hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj  8:144  active ready running
| |- 11:0:2:0 sdr  65:16  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 11:0:0:0 sdb  8:i6   active ready running
  |- 12:0:0:0 sdz  65:144 active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



== Definições recomendadas

O sistema operacional RHEL 7,0 é compilado para reconhecer LUNs ONTAP e definir automaticamente todos os parâmetros de configuração corretamente para configurações ASA e não ASA.

O `multipath.conf` arquivo deve existir para o daemon multipath iniciar. Se este arquivo não existir, você pode criar um arquivo vazio, zero-byte usando o `touch /etc/multipath.conf` comando.

Na primeira vez que você criar o `multipath.conf` arquivo, talvez seja necessário habilitar e iniciar os serviços multipath usando os seguintes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Não é necessário adicionar nada diretamente ao `multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou tenha configurações existentes que substituem os padrões. Para excluir dispositivos indesejados, adicione a seguinte sintaxe ao `multipath.conf` arquivo, substituindo <DevId> pela cadeia de carateres identificador mundial (WWID) do dispositivo que você deseja excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
O exemplo a seguir determina o WWID de um dispositivo e o adiciona ao `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` É o disco SCSI local que você deseja adicionar à lista negra.

. Adicione a `WWID` à estrofe da lista negra no `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Sempre verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações herdadas que podem estar substituindo as configurações padrão.

A tabela a seguir demonstra os parâmetros críticos `multipathd` para LUNs ONTAP e os valores necessários. Se um host estiver conetado a LUNs de outros fornecedores e qualquer um desses parâmetros for substituído, ele precisará ser corrigido por estrofes posteriores `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Sem essa correção, os LUNs ONTAP podem não funcionar como esperado. Você só deve substituir esses padrões em consulta com o NetApp, o fornecedor do sistema operacional ou ambos, e apenas quando o impactos for totalmente compreendido.

[cols="2*"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN.* 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
.Exemplo
O exemplo a seguir mostra como corrigir um padrão substituído. Nesse caso, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP. Se eles não puderem ser removidos devido a outros arrays SAN ainda conetados ao host, esses parâmetros podem ser corrigidos especificamente para LUNs ONTAP com uma estrofe de dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


== Configurar definições KVM

Você não precisa configurar configurações para uma Máquina Virtual baseada em Kernel porque o LUN é mapeado para o hipervisor.



== Espelhamento ASM

O espelhamento do Gerenciamento Automático de armazenamento (ASM) pode exigir alterações nas configurações de multipath do Linux para permitir que o ASM reconheça um problema e alterne para um grupo de falhas alternativo. A maioria das configurações ASM no ONTAP usa redundância externa, o que significa que a proteção de dados é fornecida pelo array externo e o ASM não espelha dados. Alguns sites usam ASM com redundância normal para fornecer espelhamento bidirecional, normalmente em diferentes sites. link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bancos de dados Oracle no ONTAP"^]Consulte para obter mais informações.



== Problemas conhecidos

A versão RHEL 7,0 com ONTAP tem os seguintes problemas conhecidos:

[cols="3*"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=844417["844417"^] | O host Emulex 16G FC (LPe16002B-M6) falha durante a e/S com operações de failover de storage | Você pode observar uma falha de host do Emulex FC de 16G GB (LPe16002B-M6) durante a e/S com operações de failover de storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=811587["811587"^] | O host Emulex 16G FC (LPe16002B-M6) falha durante a e/S com operações de failover de storage | Você pode observar uma falha de host do Emulex FC de 16G GB (LPe16002B-M6) durante a e/S com operações de failover de storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=803071["803071"^] | O host Emulex 16G FC (LPe16002B-M6) falha durante a e/S com operações de failover de storage | Você pode observar uma falha de host do Emulex FC de 16G GB (LPe16002B-M6) durante a e/S com operações de failover de storage. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=820163["820163"^] | Falhas de travamento ou caminho do host QLogic observadas durante e/S com operações de failover de armazenamento | Você pode observar falhas de travamento ou caminho de um host no host QLogic durante e/S com operações de failover de armazenamento. Em tais cenários, você pode ver a seguinte mensagem: "Caixa de correio cmd timeout ocorreu, cmd 0X54, mb[0] e firmware dump salvo para temp buffer" mensagens que leva à falha do host hung/path. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=799323["799323"^] | Falhas de travamento ou caminho do host Emulex FCoE (OCe10102-FX-D) observadas durante e/S com operações de failover de armazenamento | Você pode observar falhas de travamento ou caminho de um host no host FCoE Emulex 10G (OCe10102-FX-D) durante e/S com operações de failover de armazenamento. Em tais cenários, você pode ver a seguinte mensagem: "O pool de buffer do driver está vazio, mensagens de barramento de e/S de camada SCSI e/S Abort Request Status" que levam a falhas de host/caminho. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=849212["849212"^] | Falhas de travamento ou caminho do host Emulex 16G FC (LPe16002B-M6) são observadas durante a e/S com operações de failover de storage | É possível observar falhas de travamento ou caminho do host no host Emulex 16G FC (LPe16002B-M6) durante a e/S com operações de failover de storage. Em tais cenários, você pode ver a seguinte mensagem: "RSCN timeout Data e iotag x1301 está fora do intervalo: max iotag" mensagens que leva a falhas de host hung/path. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836800["836800"^] | O Anaconda exibe uma mensagem de falha de login iSCSI, embora os logins sejam bem-sucedidos durante a instalação do sistema operacional RHEL 7,0 | Quando você instala o root(/) em um LUN de multipath iSCSI, o endereço IP das interfaces Ethernet é especificado na linha de comando do kernel para que os endereços IP sejam atribuídos antes do início do serviço iSCSI. No entanto, o dracut não pode atribuir endereços IP a todas as portas Ethernet durante a inicialização, antes do início do serviço iSCSI. Isso faz com que o login iSCSI falhe em interfaces sem endereços IP. Você verá o serviço iSCSI tentar fazer login várias vezes, o que causará um atraso no tempo de inicialização do sistema operacional. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836875["836875"^] | Os endereços IP nem sempre são atribuídos durante a inicialização de um sistema operacional RHEL 7,0 instalado em um LUN multipath iSCSI | Quando você está instalando o RHEL 7,0, a tela de instalação do anaconda exibe que o login iSCSI em vários IPs de destino falhou, embora os logins iSCSI sejam bem-sucedidos. O Anaconda exibe a seguinte mensagem de erro: "Falha no login do nó" você observará esse erro somente quando você selecionar vários IPs de destino para login iSCSI. Você pode continuar a instalação do sistema operacional clicando no botão "ok". Este bug não dificulta a instalação do iSCSI ou do RHEL 7,0 os. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=836657["836657"^] | O Anaconda não adiciona argumento bootdev na linha cmd do kernel para definir o endereço IP para o RHEL 7,0 os instalado no iSCSI multipath'd LUN | O Anaconda não adiciona um argumento bootdev na linha de comando do kernel onde você define o endereço IPv4 durante a instalação do sistema operacional RHEL 7,0 em um LUN iSCSI multipath. Isso impede a atribuição de endereços IP a qualquer uma das interfaces Ethernet que foram configuradas para estabelecer sessões iSCSI com o subsistema de armazenamento durante a inicialização do RHEL 7,0. Como as sessões iSCSI não são estabelecidas, o LUN raiz não é descoberto quando o sistema operacional é inicializado e, portanto, a inicialização do sistema operacional falha. 
|===