---
sidebar: sidebar 
permalink: hu_sanhost_index.html 
keywords: san, host, utility, software, netapp 
summary: Saiba mais sobre as informações mais recentes sobre as versões do SAN Host Utility e acesse o procedimento de instalação para a configuração do seu host. 
---
= Saiba mais sobre os utilitários de host SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Saiba mais sobre as informações mais recentes sobre as versões do SAN Host Utility e acesse o procedimento de instalação para a configuração do seu host.

Existem vários pacotes de software de utilitários de host SAN disponíveis no site de suporte da NetApp. A NetApp recomenda o uso do software de utilitários de host SAN, se estiver disponível para seu host SAN.

O software AIX, HP-UX, Linux e Solaris Host Utilities fornece um kit de ferramentas de linha de comando. O kit de ferramentas ajuda você a gerenciar LUNs ONTAP e adaptadores de barramento de host (HBAs). O suporte ao cliente do NetApp também pode usar os Utilitários de host SAN para coletar informações sobre sua configuração se você tiver um problema que exija assistência. O kit de ferramentas é instalado automaticamente quando você instala o pacote de software Host Utilities.

Os Utilitários de host do Windows permitem que você conete um computador host do Windows aos sistemas de armazenamento do NetApp. O software inclui um programa de instalação que define os parâmetros necessários do registo do Windows e do HBA. Isso permite que o host do Windows gerencie corretamente os comportamentos do sistema de storage para as plataformas ONTAP e e-Series.


NOTE: Para obter operações confiáveis após a instalação, use o link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o host oferece suporte à configuração completa de NVMe sobre Fabrics (incluindo NVMe sobre TCP e NVMe sobre Fibre Channel), iSCSI, FC ou FCoE.
