---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: Host Utilities, solaris, 6.2 netapp, ontap 
summary: Notas de versão para Solaris Host Utilities 6,2 
---
= Notas de versão do Solaris Host Utilities 6,2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As notas de versão descrevem novos recursos e aprimoramentos, problemas corrigidos na versão atual, problemas e limitações conhecidos e precauções importantes relacionadas à configuração e gerenciamento de seu host específico Solaris com seu sistema de armazenamento ONTAP.

Para obter informações específicas sobre as versões e atualizações do sistema operacional compatíveis com os Utilitários do host, consulte link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^].



== Problemas e limitações conhecidos

Você deve estar ciente dos seguintes problemas conhecidos e limitações que podem afetar o desempenho em seu host específico.

[cols="3"]
|===
| ID do bug | Título | Descrição 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Alterações de vinculação de driver do Solaris 11,4 FC necessárias no HUK 6,2 | Recomendações do Solaris 11,4 e HUK: A vinculação do driver FC é alterada de `ssd(4D)` para `sd(4D)`. Mova a configuração para a `sd.conf` qual você tem acesso `ssd.conf`, conforme mencionado no Oracle (Doc ID 2595926,1). O comportamento varia entre sistemas Solaris 11,4 recém-instalados e sistemas atualizados a partir de versões 11,3 ou inferiores. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"^] fornece informações completas para a maioria dos problemas conhecidos, incluindo soluções alternativas sugeridas sempre que possível. Algumas combinações de palavras-chave e tipos de bug que você pode querer usar incluem o seguinte:

* FCP Geral: Exibe bugs FC e adaptador de barramento de host (HBA) que não estão associados a um host específico.
* FCP - Solaris

