---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Descreve como usar os Utilitários de host Solaris 6,2 com ONTAP 
---
= Instalar os Utilitários de host Solaris 6,2 para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os utilitários de host Solaris ajudam você a gerenciar o armazenamento ONTAP conectado a um host Solaris e auxiliam o suporte técnico na coleta de dados de configuração.

Os utilitários de host Solaris oferecem suporte a vários ambientes Solaris e vários protocolos de transporte.  Estes são os principais ambientes do Solaris Host Utilities:

* O sistema operacional nativo com MPxIO e o protocolo Fibre Channel (FC) ou iSCSI em um sistema usando um processador SPARC ou um processador x86/64.
* Veritas Dynamic Multipathing (DMP) com o protocolo FC ou iSCSI em um sistema que usa um processador SPARC, ou o protocolo iSCSI em um sistema que usa um processador x86/64.


O Solaris Host Utilities 6.2 oferece suporte às seguintes séries Solaris:

* Solaris 11.x
* Solaris 10.x


.Antes de começar
Verifique se sua configuração iSCSI, FC ou FCoE é suportada.  Você pode usar olink:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar sua configuração.

.Passos
. Efetue login no seu host como root.
. Baixe uma cópia do arquivo compactado contendo os utilitários do host dolink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Site de suporte da NetApp"^] para um diretório no seu host Solaris:
+
[role="tabbed-block"]
====
.CPU SPARC
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.CPU x86/x64
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Vá para o diretório no seu host Solaris que contém o download.
. Descompacte o arquivo usando o `gunzip` comando:
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. Extraia o arquivo usando o `tar xvf` comando:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. Adicione os pacotes que você extraiu do arquivo tar ao seu host
+
[source, cli]
----
pkgadd
----
+
Os pacotes são adicionados ao `/opt/NTAP/SANToolkit/bin` diretório.

+
O exemplo a seguir usa o `pkgadd` comando para instalar o pacote de instalação do Solaris:

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Confirme se o kit de ferramentas foi instalado com sucesso usando um dos seguintes comandos:
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.Mostrar exemplos de saídas
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. Configure os parâmetros do host para seu ambiente MPxIO ou Veritas DMP:
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. Verifique a instalação:
+
[source, cli]
----
sanlun version
----




== O que se segue?

link:hu-solaris-san-toolkit.html["Saiba mais sobre o SAN Toolkit"] .
