---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Descreve como usar o SUSE Linux Enterprise Server 12 SP3 com o ONTAP 
---
= Use o SUSE Linux Enterprise Server 12 SP3 com ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar as configurações de host SAN ONTAP para configurar o SUSE Linux Enterprise Server 12 SP3 com ONTAP como destino.



== Instale os Utilitários de host do Linux

O pacote de software de utilitários de host NetApp está disponível no link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^]em um arquivo .rpm de 32 e 64 bits. Se não souber qual é o ficheiro adequado para a sua configuração, utilize o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar qual necessita.

O NetApp recomenda fortemente a instalação dos utilitários de host do Linux, mas não é obrigatório. Os utilitários não alteram nenhuma configuração em seu host Linux. Os utilitários melhoram o gerenciamento e auxiliam o suporte ao cliente da NetApp na coleta de informações sobre sua configuração.

Se você tiver Linux Host Utilities atualmente instalado, você deve atualizá-lo para a versão mais recente ou removê-lo e siga estas etapas para instalar a versão mais recente.

.Passos
. Baixe o pacote de software Linux Host Utilities de 32 ou 64 bits do link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Site de suporte da NetApp"^] para o seu host.
. Instale o pacote de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Pode utilizar as definições de configuração fornecidas neste procedimento para configurar os clientes em nuvem ligados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de ferramentas SAN

O kit de ferramentas é instalado automaticamente quando você instala o pacote de utilitários de host do NetApp. Este kit fornece o `sanlun` utilitário, que ajuda você a gerenciar LUNs e HBAs. O `sanlun` comando retorna informações sobre os LUNs mapeados para o seu host, multipathing e informações necessárias para criar grupos de iniciadores.

.Exemplo
No exemplo a seguir, o `sanlun lun show` comando retorna informações de LUN.

[source, cli]
----
# sanlun lun show all
----
Exemplo de saída:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Inicialização de SAN

.Antes de começar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o link:https://imt.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional do host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

Para o SUSE Linux Enterprise Server 12 SP3, o arquivo /etc/multipath.conf deve existir, mas você não precisa fazer alterações específicas no arquivo. O SUSE Linux Enterprise Server 12 SP3 é compilado com todas as configurações necessárias para reconhecer e gerenciar corretamente LUNs ONTAP.

Você pode usar o `multipath -ll` comando para verificar as configurações dos LUNs do ONTAP.

As seções a seguir fornecem exemplos de saídas multipath para um LUN mapeado para personas ASA e não ASA.



=== Todas as configurações do SAN Array

Todas as configurações de SAN Array (ASA) otimizam todos os caminhos para um determinado LUN, mantendo-os ativos. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP.

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



=== Configurações que não são ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com prioridades mais altas são Ativo/otimizado. Isso significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com prioridades mais baixas estão ativos, mas não otimizados, porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Um único LUN não deve exigir mais de quatro caminhos. Ter mais de quatro caminhos pode causar problemas de caminho durante falhas de storage.



== Definições recomendadas

O SUSE Linux Enterprise Server 12 SP3 os é compilado para reconhecer LUNs ONTAP e definir automaticamente todos os parâmetros de configuração corretamente. O `multipath.conf` arquivo deve existir para o daemon multipath iniciar. Se este arquivo não existir, você pode criar um arquivo vazio, zero-byte usando o `touch /etc/multipath.conf` comando.

Na primeira vez que você criar o `multipath.conf` arquivo, talvez seja necessário habilitar e iniciar os serviços multipath usando os seguintes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
Não é necessário adicionar nada diretamente ao `multipath.conf` arquivo, a menos que você tenha dispositivos que não deseja que o multipath gerencie ou tenha configurações existentes que substituem os padrões. Para excluir dispositivos indesejados, adicione a seguinte sintaxe ao `multipath.conf` arquivo, substituindo <DevId> pela cadeia de carateres identificador mundial (WWID) do dispositivo que você deseja excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
O exemplo a seguir determina o WWID de um dispositivo e o adiciona ao `multipath.conf` arquivo.

.Passos
. Determine o WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` É o disco SCSI local que você deseja adicionar à lista negra.

. Adicione a `WWID` à estrofe da lista negra no `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Sempre verifique o `/etc/multipath.conf` arquivo, especialmente na seção padrões, para configurações herdadas que podem estar substituindo as configurações padrão.

A tabela a seguir demonstra os parâmetros críticos `multipathd` para LUNs ONTAP e os valores necessários. Se um host estiver conetado a LUNs de outros fornecedores e qualquer um desses parâmetros for substituído, ele precisará ser corrigido por estrofes posteriores `multipath.conf` no arquivo que se aplicam especificamente aos LUNs ONTAP. Sem essa correção, os LUNs ONTAP podem não funcionar como esperado. Você só deve substituir esses padrões em consulta com o NetApp, o fornecedor do sistema operacional ou ambos, e apenas quando o impactos for totalmente compreendido.

[cols="2*"]
|===
| Parâmetro | Definição 


| detectar_prio | sim 


| dev_loss_tmo | "infinito" 


| failback | imediato 


| fast_io_fail_tmo | 5 


| caraterísticas | "2 pg_init_retries 50" 


| flush_on_last_del | "sim" 


| hardware_handler | "0" 


| no_path_retry | fila de espera 


| path_checker | "tur" 


| path_grouing_policy | "group_by_prio" 


| path_selector | "tempo de serviço 0" 


| polling_interval | 5 


| prio | "ONTAP" 


| produto | LUN.* 


| reter_anexado_hw_handler | sim 


| rr_peso | "uniforme" 


| user_friendly_names | não 


| fornecedor | NetApp 
|===
.Exemplo
O exemplo a seguir mostra como corrigir um padrão substituído. Nesse caso, o `multipath.conf` arquivo define valores para `path_checker` e `no_path_retry` que não são compatíveis com LUNs ONTAP. Se eles não puderem ser removidos devido a outros arrays SAN ainda conetados ao host, esses parâmetros podem ser corrigidos especificamente para LUNs ONTAP com uma estrofe de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
}
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----


== Espelhamento ASM

O espelhamento do Gerenciamento Automático de armazenamento (ASM) pode exigir alterações nas configurações de multipath do Linux para permitir que o ASM reconheça um problema e alterne para um grupo de falhas alternativo. A maioria das configurações ASM no ONTAP usa redundância externa, o que significa que a proteção de dados é fornecida pelo array externo e o ASM não espelha dados. Alguns sites usam ASM com redundância normal para fornecer espelhamento bidirecional, normalmente em diferentes sites. link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bancos de dados Oracle no ONTAP"^]Consulte para obter mais informações.



== Problemas conhecidos

O SUSE Linux Enterprise Server 15 SP3 com a versão ONTAP tem os seguintes problemas conhecidos:

[cols="3*"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Interrupção do kernel observada no kernel versão SLES12 SP3 com Emulex LPe16002 16GB FC durante a operação de failover de armazenamento | Uma interrupção do kernel pode ocorrer durante operações de failover de armazenamento no kernel versão SLES12 SP3 com Emulex LPe16002 HBA. A interrupção do kernel solicita uma reinicialização do sistema operacional, o que, por sua vez, causa uma interrupção do aplicativo. Se o kdump estiver configurado, a interrupção do kernel gera um arquivo vmcore em /var/crash/Directory. Você pode investigar a causa da falha no arquivo vmcore. Exemplo: No caso observado, a interrupção do kernel foi observada no módulo "lpfc_sli_ringtxcmpl_put 51" e é registrada no arquivo vmcore – exceção RIP: Lpfc_sli_ringtxcmpl_put 51. Recupere o sistema operacional após a interrupção do kernel reiniciando o sistema operacional host e reiniciando o aplicativo. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Interrupção do kernel observada no kernel versão SLES12 SP3 com Emulex LPe32002 32GB FC durante operações de failover de armazenamento | Uma interrupção do kernel pode ocorrer durante operações de failover de armazenamento no kernel versão SLES12 SP3 com Emulex LPe32002 HBA. A interrupção do kernel solicita uma reinicialização do sistema operacional, o que, por sua vez, causa uma interrupção do aplicativo. Se o kdump estiver configurado, a interrupção do kernel gera um arquivo vmcore em /var/crash/Directory. Você pode investigar a causa da falha no arquivo vmcore. Exemplo: No caso observado, a interrupção do kernel foi observada no módulo "lpfc_sli_free_hbq-76" e é registrada no arquivo vmcore – exceção RIP: Lpfc_sli_free_hbq-76. Recupere o sistema operacional após a interrupção do kernel reiniciando o sistema operacional host e reiniciando o aplicativo. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Interrupção do kernel observada no SLES12SP3 com QLogic QLE2562 8GB FC durante operações de failover de armazenamento | Durante as operações de failover de armazenamento no kernel Sles12sp3 (kernel-default-4,4.82-6,3.1) com QLogic QLE2562 HBA, a interrupção do kernel foi observada devido a um pânico no kernel. O pânico do kernel leva a uma reinicialização do sistema operacional, causando uma interrupção do aplicativo. O pânico do kernel gera o arquivo vmcore sob o diretório /var/crash/ se o kdump estiver configurado. Após o pânico do kernel, o arquivo vmcore pode ser usado para entender a causa da falha. Exemplo: Neste caso, o pânico foi observado no módulo "blk_finish_request 289". Ele é registrado no arquivo vmcore com a seguinte string: "Exceção RIP: blk_finish_request.289" após a interrupção do kernel, você pode recuperar o sistema operacional reiniciando o sistema operacional. Você pode reiniciar o aplicativo conforme necessário. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Interrupção do kernel observada no SLES12SP3 com Qlogic QLE2662 16GB FC durante operações de failover de armazenamento | Durante as operações de failover de armazenamento no kernel Sles12sp3 (kernel-default-4,4.82-6,3.1) com Qlogic QLE2662 HBA, você pode observar a interrupção do kernel. Isso solicita a reinicialização do sistema operacional, causando interrupção do aplicativo. A interrupção do kernel gera um arquivo vmcore no diretório /var/crash/ se o kdump estiver configurado. O arquivo vmcore pode ser usado para entender a causa da falha. Exemplo: Neste caso, a interrupção do Kernel foi observada no módulo "endereço desconhecido ou inválido" e é registrada no arquivo vmcore com a seguinte string - exceção RIP: Endereço desconhecido ou inválido. Após a interrupção do kernel, o sistema operacional pode ser recuperado reiniciando o sistema operacional host e reiniciando o aplicativo conforme necessário. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Interrupção do kernel observada no SLES12SP3 com Emulex LPe16002 16GB FC durante operações de failover de armazenamento | Durante as operações de failover de armazenamento no kernel Sles12sp3 (kernel-default-4,4.87-3,1) com Emulex LPe16002 HBA, você pode observar a interrupção do kernel. Isso solicita a reinicialização do sistema operacional, causando interrupção do aplicativo. A interrupção do kernel gera um arquivo vmcore sob o diretório /var/crash/ se o kdump estiver configurado. O arquivo vmcore pode ser usado para entender a causa da falha. Exemplo: Neste caso, a interrupção do kernel foi observada no módulo "Raw_spin_lock_irqsave-30" e é registrada no arquivo vmcore com a seguinte cadeia de carateres: – Exceção RIP: _RAW_spin_lock_irqsave-30. Após a interrupção do kernel, o sistema operacional pode ser recuperado reiniciando o sistema operacional host e reiniciando o aplicativo conforme necessário. 
|===