---
sidebar: sidebar 
permalink: hu_solaris_62_cmd.html 
keywords: host utilities, unified, solaris, 6.2, netapp, ontap 
summary: Descreve como usar os Utilitários de host Solaris 6,2 com ONTAP 
---
= Referência de comando do Solaris Host Utilities 6,2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode usar a referência de exemplo de comando Utilitários de host Solaris 6,2 para uma validação completa da configuração de armazenamento NetApp usando a ferramenta Utilitários de host.



== Listar todos os iniciadores de host mapeados para o host

Você pode recuperar uma lista de todos os iniciadores de host mapeados para um host.

[source, cli]
----
# sanlun fcp show adapter -v
----
*Exemplo de saída*

[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


== Listar todos os LUNs mapeados para o host

Você pode recuperar uma lista de todos os LUNs mapeados para um host.

[source, cli]
----
# sanlun lun show -p -v all
----
*Exemplo de saída*

[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


== Listar todos os LUNs mapeados para o host de um determinado SVM/Liste todos os atributos de um determinado LUN mapeados para o host

É possível recuperar uma lista de todas as LUNs mapeadas para um host de uma determinada SVM.

[source, cli]
----
# sanlun lun show -p -v sanboot_unix`
----
*Exemplo de saída*

[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


== Listar atributos LUN ONTAP por nome de arquivo do dispositivo host

Você pode recuperar uma lista de todos os atributos LUN do ONTAP especificando um nome de arquivo do dispositivo host.

[source, cli]
----
# sanlun lun show all
----
*Exemplo de saída*

[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----