---
sidebar: sidebar 
permalink: hu_vsphere_8.html 
keywords: host utilities, veritas, infoscale, 8.x, netapp, ontap, vmware, vspehere 
summary: Você pode configurar as configurações de host SAN ONTAP para a versão do VMware vSphere 8.x com protocolos FC, FCoE e iSCSI. 
---
= Use o VMware vSphere 8.x com o ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode configurar as configurações de host SAN ONTAP para a versão do VMware vSphere 8.x com protocolos FC, FCoE e iSCSI.



== Inicialização de SAN do hipervisor

.O que você vai precisar
Se você decidir usar a inicialização de SAN, ele deve ser suportado por sua configuração. Você pode usar o https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar se o seu sistema operacional, HBA, HBA firmware e o BIOS de inicialização HBA e a versão ONTAP são suportados.

.Passos
. Mapeie o LUN de inicialização SAN para o host.
. Verifique se há vários caminhos disponíveis.
+

NOTE: Vários caminhos ficam disponíveis depois que o sistema operacional host estiver ativo e em execução nos caminhos.

. Ative a inicialização SAN no BIOS do servidor para as portas às quais o LUN de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Reinicie o host para verificar se a inicialização foi bem-sucedida.




== Multipathing

O ESXi fornece um módulo multipathing extensível chamado NMP (Native Multipathing Plug-in) que gerencia os sub-plugins, os SATPs (Storage Array Type Plugins) e os PSPs (Path Selection Plugins). Por padrão, essas regras SATP estão disponíveis no ESXi.

Para armazenamento NetApp ONTAP, `VMW_SATP_ALUA` o plugin é usado por padrão com `VMW_PSP_RR` como política de seleção de caminho (PSP). Você pode confirmar usando o seguinte comando:

[listing]
----
`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`
----
Exemplo de saída:

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
---------------------------------------------------------------------------------
VMW_SATP_ALUA          LSI       INF-01-00                        reset_on_attempted_reserve  system
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve  system

Rule Group  Claim Options  Default PSP  PSP Options     Description
------------------------------------------------------------------
tpgs_on        VMW_PSP_MRU                  NetApp E-Series arrays with ALUA support
tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Configurações que não são ASA

Para configurações que não sejam ASA, deve haver dois grupos de caminhos com prioridades diferentes. Os caminhos com prioridades mais altas são Ativo/otimizado, o que significa que eles são atendidos pelo controlador onde o agregado está localizado. Os caminhos com prioridades mais baixas estão ativos, mas não são otimizados porque são servidos de um controlador diferente. Os caminhos não otimizados são usados somente quando caminhos otimizados não estão disponíveis.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP com dois caminhos ativos/otimizados e dois caminhos ativos/não otimizados:

[listing]
----
# esxcli storage nmp device list -d naa.600a0980383148693724545244395855
----
Exemplo de saída:

[listing]
----
naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L11, vmhba3:C0:T0:L11
   Is USB: false
----
[listing]
----
# esxcli storage nmp path list -d naa.600a0980383148693724545244395855
----
Exemplo de saída:

[listing, subs="+quotes"]
----
fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2003d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2002d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T0:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a51:21000024ff7f4a51-fc.2009d039ea3ab21f:2001d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba4:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff7f4a50:21000024ff7f4a50-fc.2009d039ea3ab21f:2000d039ea3ab21f-naa.600a0980383148693724545244395855
   Runtime Name: vmhba3:C0:T3:L11
   Device: naa.600a0980383148693724545244395855
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a0980383148693724545244395855)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=ANO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Todas as configurações do SAN Array

Em todas as configurações de storage SAN (ASA), todos os caminhos para um determinado LUN estão ativos e otimizados. Isso melhora a performance atendendo operações de e/S em todos os caminhos ao mesmo tempo.

.Exemplo
O exemplo a seguir exibe a saída correta para um LUN ONTAP:

[listing]
----
esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453
----
Exemplo de saída:

[listing]
----
naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1000,bytes=10485760,useANO=0; lastPathIndex=3: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L14, vmhba4:C0:T1:L14, vmhba3:C0:T0:L14, vmhba3:C0:T1:L14
   Is USB: false

----
[listing]
----
# esxcli storage nmp path list -d naa.600a098038314962485d543078486c7a
----
Exemplo de saída:

[listing, subs="+quotes"]
----
fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2015d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=2,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a75:210034800d756a75-fc.2018d039ea936319:2017d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba4:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2014d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T0:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,*TPG_state=AO*,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.200034800d756a74:210034800d756a74-fc.2018d039ea936319:2016d039ea936319-naa.600a098038314962485d543078486c7a
   Runtime Name: vmhba3:C0:T1:L14
   Device: naa.600a098038314962485d543078486c7a
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038314962485d543078486c7a)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,*TPG_state=AO*,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== Evolução

Os volumes virtuais (vVols) são um tipo de objeto VMware que corresponde a um disco de máquina virtual (VM), seus snapshots e clones rápidos.

As ferramentas do ONTAP para VMware vSphere incluem o provedor VASA para ONTAP, que fornece o ponto de integração para um VMware vCenter utilizar o storage baseado em vVols. Quando você implementa o ONTAP Tools Open Virtualization Appliance (OVA), ele é registrado automaticamente no servidor vCenter e habilita o provedor VASA.

Quando você cria um datastore vVols usando a interface de usuário do vCenter, ele orienta você a criar FlexVols como armazenamento de backup para o datastore. VVols dentro dos datastores vVols são acessados por hosts ESXi usando um endpoint de protocolo (PE). Em ambientes SAN, um LUN de 4MB GB é criado em cada FlexVol no datastore para uso como PE. Um SAN PE é uma unidade lógica administrativa (ALU). VVols são unidades lógicas subsidiárias (SLUs).

Os requisitos padrão e as práticas recomendadas para ambientes SAN se aplicam ao usar vVols, incluindo (entre outros) o seguinte:

* Crie pelo menos um SAN LIF em cada nó por SVM que você pretende usar. A prática recomendada é criar pelo menos dois por nó, mas não mais do que o necessário.
* Elimine qualquer ponto único de falha. Use várias interfaces de rede VMkernel em sub-redes de rede diferentes que usam agrupamento NIC quando vários switches virtuais são usados ou use várias NICs físicas conetadas a vários switches físicos para fornecer HA e maior throughput.
* Configurar zoneamento, VLANs ou ambos conforme necessário para a conetividade do host.
* Verifique se todos os iniciadores necessários estão conetados aos LIFs de destino no SVM desejado.



NOTE: Você deve implantar as ferramentas do ONTAP para o VMware vSphere para habilitar o provedor VASA. O Fornecedor VASA irá gerir todas as suas definições do iGroup para si, pelo que não há necessidade de criar ou gerir iGroups num ambiente vVols.

O NetApp não recomenda alterar as configurações do vVols do padrão no momento.

Consulte o https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^] para obter versões específicas das ferramentas do ONTAP ou do Fornecedor VASA legado para as suas versões específicas do vSphere e do ONTAP.

Para obter informações detalhadas sobre o provisionamento e o gerenciamento de vVols, consulte as ferramentas do ONTAP para a documentação do VMware vSphere, link:https://docs.netapp.com/us-en/netapp-solutions/hybrid-cloud/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^]e link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Definições recomendadas



=== Bloqueio ATS

O bloqueio ATS é *obrigatório* para armazenamento compatível com VAAI e VMFS5 atualizado e é necessário para interoperabilidade adequada e desempenho ideal de e/S de armazenamento compartilhado VMFS com LUNs ONTAP. Consulte a documentação da VMware para obter detalhes sobre como ativar o bloqueio ATS.

[cols="4*"]
|===
| Definições | Padrão | ONTAP recomendado | Descrição 


| HardwareAcceleratedLocking | 1 | 1 | Ajuda a ativar o uso de bloqueio atômico de teste e conjunto (ATS) 


| IOPs de disco | 1000 | 1 | Limite de IOPS: A PSP Round Robin tem um limite de IOPS de 1000. Neste caso padrão, um novo caminho é usado depois que 1000 operações de e/S são emitidas. 


| Disco/QFullSampleSize | 0 | 32 | A contagem de condições DE FILA CHEIA ou OCUPADO leva antes do ESXi começar a estrangular. 
|===

NOTE: Ative `Space-alloc` a configuração para todos os LUNs mapeados para o VMware vSphere para `UNMAP` funcionar. Para obter mais detalhes, consulte a Documentação do ONTAP.



=== Tempos limite de tempo do SO convidado

Você pode configurar manualmente as máquinas virtuais com as afinações recomendadas do SO Guest. Depois de ajustar as atualizações, você deve reiniciar o convidado para que as atualizações entrem em vigor.

*Valores de tempo limite do GOS:*

[cols="2*"]
|===
| Tipo de SO convidado | Tempos limite 


| Variantes do Linux | tempo limite do disco: 60 


| Windows | tempo limite do disco: 60 


| Solaris | tempo limite do disco: 60 tentativa de ocupado: 300 tentativa de rearme: 300 tentativa de rearme: 30 máximo de aceleração: 32 min. de aceleração: 8 
|===


=== Valide o vSphere ajustável

Você pode usar o seguinte comando para verificar a `HardwareAcceleratedLocking` configuração.

`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`

[listing, subs="+quotes"]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: *1*
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Valide a configuração Disk IOPs (IOPs de disco)

Você pode usar o seguinte comando para verificar a configuração IOPs.

`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`

[listing, subs="+quotes"]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,*iops=1*,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Valide o QFullSampleSize

Você pode usar o seguinte comando para verificar o QFullSampleSize.

`esxcli system settings  advanced list --option /Disk/QFullSampleSize`

[listing, subs="+quotes"]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: *32*
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Problemas conhecidos

A versão do VMware vSphere 8.x com ONTAP tem os seguintes problemas conhecidos:

[cols="10,30,30"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1543660["1543660"^] | O erro de e/S ocorre quando as VMs Linux que usam adaptadores vNVMe encontram uma janela longa de todos os caminhos para baixo (APD)  a| 
As VMs Linux que executam o vSphere 8.x e posterior e que usam adaptadores NVMe virtuais (vNVME) encontram um erro de e/S porque a operação de repetição do vNVMe está desativada por padrão. Para evitar uma interrupção nas VMs Linux que executam kernels mais antigos durante um APD (All Paths Down) ou uma carga de e/S pesada, a VMware introduziu um "VSCSIDisableNvmeRetry" sintonizável para desativar a operação de repetição do vNVMe.

|===
.Informações relacionadas
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere com ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Suporte ao VMware vSphere 5.x, 6.x e 7.x com o NetApp MetroCluster (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP com sincronização ativa do NetApp SnapMirror com o VMware vSphere Metro Storage Cluster (vMSC)"^]

