---
sidebar: sidebar 
permalink: hu_wuhu_troubleshoot.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Os Utilitários de host do Windows incluem um programa de instalação que define os parâmetros necessários do Registro do Windows e do HBA para que o host do Windows manipule corretamente os comportamentos do sistema de storage para plataformas ONTAP e e-Series. 
---
= Solucionar problemas de utilitários de host do Windows com configuração de armazenamento ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Use as técnicas gerais de solução de problemas para investigar problemas que podem ocorrer em um Windows Host Utilities com configuração de armazenamento ONTAP .  Você também deve verificar olink:hu-wuhu-release-notes.html["Notas de lançamento dos Utilitários do sistema anfitrião do Windows"] para problemas e soluções conhecidos.

Segue-se uma lista das diferentes áreas que pode investigar para potenciais problemas de interoperabilidade:

* Para identificar possíveis problemas de interoperabilidade, confirme se os Utilitários do host oferecem suporte à combinação de software do sistema operacional host, hardware do host, software ONTAP e hardware do sistema de storage. Consulte http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade"^] para obter mais informações.
* Verifique se tem a configuração iSCSI correta.
* Se os LUNs iSCSI não estiverem disponíveis após uma reinicialização, verifique se o destino está listado como persistente na guia *alvos persistentes* da GUI do iniciador iSCSI da Microsoft.
* Se os aplicativos que usam os LUNs exibirem erros na inicialização, verifique se os aplicativos estão configurados para depender do serviço iSCSI.
* Para caminhos FC para controladores de storage que executam o ONTAP, verifique se os switches FC estão zoneados usando as WWPNs dos LIFs de destino, e não as WWPNs das portas físicas no nó.
* Revise olink:hu-wuhu-release-notes.html["Notas de versão"] para que os utilitários de host do Windows verifiquem problemas conhecidos.  As notas de versão incluem uma lista de problemas e limitações conhecidos.
* Revise as informações de solução de problemas na https://docs.netapp.com/us-en/ontap/san-admin/index.html["Administração de SAN ONTAP"^] documentação.
* Procure https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] por problemas recentemente descobertos.
+
** No campo tipo de Bug em Pesquisa Avançada, selecione *iSCSI - Windows* e, em seguida, selecione *Go*. Você deve repetir a pesquisa por tipo de Bug *FCP -Windows*.


* Recolha informações sobre o seu sistema.
* Registre quaisquer mensagens de erro exibidas no host ou no console do sistema de armazenamento.
* Colete os arquivos de log do sistema de host e armazenamento.
* Registre os sintomas do problema e quaisquer alterações feitas no host ou sistema de armazenamento imediatamente antes que o problema apareça.
* Se não conseguir resolver o problema, contacte o suporte técnico da NetApp para obter assistência.

