---
sidebar: sidebar 
permalink: hu_wuhu_71_rn.html 
keywords: host utilities, linux, 7.1, 7.2, netapp, ontap, release, notes 
summary: Notas de versão para Utilitários de sistema de anfitrião unificado do Windows 
---
= Notas de lançamento dos Utilitários do sistema de anfitrião Unificado do Windows
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As notas de versão descrevem novos recursos e aprimoramentos, problemas corrigidos na versão atual, problemas e limitações conhecidos e precauções importantes relacionadas à configuração e gerenciamento de seu host Windows específico com seu sistema de armazenamento ONTAP.

Para obter informações específicas sobre as versões e atualizações do sistema operacional compatíveis com os Utilitários do host, consulte link:https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Ferramenta de Matriz de interoperabilidade do NetApp"^].



== O que há de novo

* O Windows Unified Host Utilities 7,2 inclui suporte para configurações de parâmetros de driver NVMe/FC e correções de bugs para novas placas de fornecedores.
* Os Utilitários unificados de host do Windows 7,1 incluem suporte para sistemas de storage e-Series, suporte para ONTAP 9 e versões posteriores e tempos limite de iSCSI aprimorados para failover mais rápido.




== Problemas e limitações conhecidos

Você deve estar ciente dos seguintes problemas conhecidos e limitações que podem afetar o desempenho em seu host específico. Alguns comportamentos inesperados e potencialmente indesejados e soluções alternativas para evitar esses comportamentos foram identificados na versão do Windows Unified Host Utilities 7,1.

[cols="30, 30, 20"]
|===
| Título | Descrição | Solução alternativa 


| A execução `linux_gos_timeout-install.sh` do script não é mais necessária em convidados do Hyper-V que executam o Red Hat Enterprise Linux ou o SUSE Linux Enterprise Server | Não é mais necessário executar `linux_gos_timeout-install.sh` o script para alterar o tempo limite de disco nos convidados Red Hat Enterprise Linux 5, Red Hat Enterprise Linux 6 ou SUSE Linux Enterprise Server 11 Hyper-V porque as configurações de tempo limite padrão estão sendo usadas. O `linux_gos_timeout-install.sh` script que foi incluído em versões anteriores dos Utilitários de host não está mais incluído na versão do Windows Unified Host Utilities 7,1. O Windows Unified Host Utilities 7,1 usa as configurações padrão de tempo limite do disco. | Não aplicável 


| As sessões iSCSI não se reconetam após a reinicialização com IPv4 e IPv6 mistos | Em uma configuração de e/S multipath (MPIO) ou em várias conexões por sessão (MCS) que tenha endpoints IPv4 e IPv6, algumas sessões iSCSI podem não se reconetar após reinicializar o host do Windows. | Use todos os endpoints IPv4 ou IPv6 endpoints. Não misture IPv4 e IPv6. 


| Várias conexões por sessão (MCS) não são suportadas com inicialização de software iSCSI | Ao utilizar o arranque do software iSCSI com iSCSI MCS, a ligação principal de arranque iSCSI não pode ser protegida. Isso pode levar à desconexão do LUN de inicialização e causar interrupção do sistema host. | A Microsoft não suporta MCS para hosts inicializados por software iSCSI. Use o MPIO como solução de alta disponibilidade. Note que a mistura de MPIO e MCS não é suportada. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] fornece informações completas para a maioria dos problemas conhecidos, incluindo soluções alternativas sugeridas sempre que possível.
