---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Os Utilitários unificados de host do Windows incluem um programa de instalação que define os parâmetros necessários do Registro do Windows e do HBA para que o host do Windows manipule corretamente os comportamentos do sistema de storage para plataformas NetApp ONTAP e e-Series. 
---
= Atualize os Utilitários do sistema de anfitrião unificado do Windows
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
O novo pacote de instalação do Host Utilities deve estar em um caminho acessível pelo host do Windows. Siga as instruções para instalar os Utilitários do host de forma interativa ou a partir da linha de comando do Windows para atualizar o pacote de instalação.

[role="tabbed-block"]
====
.Atualizar de forma interativa
--
Para atualizar o pacote de software Host Utilities de forma interativa, você deve executar o programa de instalação Host Utilities e seguir as instruções.

.Passos
. Mude para o diretório onde você baixou o arquivo executável.
. Execute o arquivo executável e siga as instruções na tela.
. Reinicie o host do Windows quando solicitado.
. Após a conclusão da reinicialização, verifique a versão do utilitário host:
+
.. Abra o *Painel de Controle*.
.. Vá para *Programa e recursos* e verifique a versão do utilitário host.




--
.Atualizar a partir de uma linha de comando
--
Você pode executar uma atualização silenciosa (sem supervisão) dos novos Utilitários do host inserindo os comandos apropriados no prompt de comando do Windows.

.Passos
. Digite o seguinte comando no prompt de comando do Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` É o nome do `.msi` arquivo para a arquitetura da CPU.
** MULTIPATHING especifica se o suporte MPIO está instalado. Os valores permitidos são "0" para não e "1" para sim.
** `inst_path` É o caminho onde os arquivos do Host Utilities estão instalados. O caminho padrão é `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver as opções padrão do Microsoft Installer (MSI) para Registro e outras funções, digite `msiexec /help` no prompt de comando do Windows. Por exemplo, o `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` comando exibe informações de Registro.

O sistema reinicia automaticamente quando a instalação está concluída.

--
====