---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Os Utilitários de host do Windows incluem um programa de instalação que define os parâmetros necessários do Registro do Windows e do HBA para que o host do Windows manipule corretamente os comportamentos do sistema de storage para plataformas ONTAP e e-Series. 
---
= Atualizar os utilitários de host do Windows para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode atualizar o software Windows Host Utilities na sua configuração de armazenamento ONTAP seguindo as instruções de instalação interativamente ou usando a linha de comando do Windows.  Você precisa instalar o novo software de instalação do Windows Host Utilities em um caminho que seja acessível ao host Windows.

[role="tabbed-block"]
====
.Atualizar de forma interativa
--
Atualize o software Windows Host Utilities interativamente executando o programa de instalação do Host Utilities e seguindo as instruções.

.Passos
. Mude para o diretório onde você baixou o arquivo executável.
. Execute o arquivo executável e siga as instruções na tela.
. Reinicie o host do Windows quando solicitado.
. Após a conclusão da reinicialização, verifique a versão do utilitário host:
+
.. Abra o *Painel de Controle*.
.. Vá para *Programa e recursos* e verifique a versão do utilitário host.




--
.Atualizar de forma não interativa
--
Execute uma atualização não interativa do software Windows Host Utilities usando a linha de comando do Windows.

.Passos
. Digite o seguinte comando no prompt de comando do Windows:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` É o nome do `.msi` arquivo para a arquitetura da CPU.
** Especifica se o suporte de e/S Multipath da Microsoft (MPIO) está instalado. Os valores permitidos são "0" para não e "1" para sim.
** `inst_path` É o caminho onde os arquivos do Host Utilities estão instalados. O caminho padrão é `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver as opções padrão do Microsoft Installer (MSI) para Registro e outras funções, digite `msiexec /help` no prompt de comando do Windows. Por exemplo, o `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` comando exibe informações de Registro.

O sistema reinicia automaticamente quando a instalação está concluída.

--
====