---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Como configurar o host NVMe/FC para AIX com o ONTAP 
---
= Configurar o AIX com NVMe-oF para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os hosts IBM AIX e Virtual I/O Server (VIOS)/PowerVM suportam o protocolo NVMe/FC com Asymmetric Namespace Access (ANA).  ANA é equivalente ao multipathing de acesso assimétrico à unidade lógica (ALUA) em ambientes iSCSI e FCP.

Para obter detalhes adicionais sobre as configurações suportadas, consulte olink:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade (IMT)"^] .

.Sobre esta tarefa
Você pode usar o suporte e os recursos a seguir com a configuração do host NVMe-oF para hosts AIX.  Você também deve revisar as limitações conhecidas antes de iniciar o processo de configuração.

* Suporte disponível:
+
** A partir do ONTAP 9.13.1, o suporte NVMe/FC é adicionado para IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 e VIOS 3.1.4.21 com suporte de inicialização SAN para pilhas físicas e virtuais.  Consulte a documentação da IBM para obter mais informações sobre como configurar o suporte à inicialização SAN.
** O NVMe/FC é compatível com servidores IBM Power9 e Power10.
** Um PCM (Path Control Module) separado, como o Host Utilities para suporte a AIX SCSI Multipath I/O (MPIO), não é necessário para dispositivos NVMe.
** O suporte à virtualização com o NetApp (VIOS/PowerVM) é introduzido com o VIOS 3,1.4,21. Isso é _somente_ suportado pelo modo de virtualização de armazenamento NPIV (N_PortID Virtualization) usando o servidor IBM Power10.


* Limitações conhecidas:
+
** Os HBAs Qlogic/Marvel 32G FC em um host AIX não oferecem suporte a NVMe/FC.
** A inicialização SAN não é suportada para dispositivos NVMe/FC que usam o servidor IBM Power9.




.Antes de começar
* Verifique se você tem 32GB adaptadores FC Emulex (EN1A, EN1B, EN1L, EN1M) ou 64GB adaptadores FC (EN1N, EN1P) com o firmware do adaptador 12.4.257.30 e versões posteriores.
* Se você tiver uma configuração do MetroCluster, a NetApp recomenda alterar o tempo de APD padrão do AIX NVMe/FC (All Path Down) para oferecer suporte a eventos de switchover não planejado do MetroCluster para evitar que o sistema operacional AIX aplique um tempo limite de I/O. Para obter informações adicionais e as alterações recomendadas às configurações padrão, consulte NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* Dependendo da sua versão do AIX, o Asymmetric Namespace Access Transition Timeout (ANATT) para o sistema operacional host do AIX é de 30 segundos ou 60 segundos por padrão.  Se o padrão ANATT para seu host for 30 segundos, você precisará instalar um IBM Interim Fix (ifix) do site da IBM que define o ANATT para 60 segundos para garantir que todos os fluxos de trabalho do ONTAP não causem interrupções.
+
[NOTE]
====
Para suporte a NVMe/FC AIX, você deve instalar um ifix na versão GA do sistema operacional AIX.  O ifix não é necessário para o sistema operacional VIOS/PowerVM.

Você precisa instalar os ifixes em uma versão do AIX sem ifixes instalados anteriormente relacionados a `devices.pciex.pciexclass.010802.rte` no sistema.  Ifixes instalados anteriormente podem entrar em conflito com a nova instalação.

====
+
[role="tabbed-block"]
====
.Defina ANATT para 60 segundos
--
O ANATT padrão para as versões AIX nível 72-TL5-SP6-2320 e AIX nível 73-TL1-SP2-2320 é de 30 segundos.  A IBM fornece um ifix que define o ANATT para 60 segundos.  O ifix está disponível por meio do ID do caso IBM TS018079082 e você pode instalá-lo para as seguintes versões do AIX:

** Para AIX nível 72-TL5-SP6-2320, instale o `IJ46710s6a.230509.epkg.Z` pacote.
** Para AIX nível 73-TL1-SP2-2320, instale o `IJ46711s2a.230509.epkg.Z` pacote.


--
.ANATT padrão é 60 segundos
--
O ANATT padrão é de 60 segundos para as seguintes versões do AIX:

** Nível AIX 73-TL2-SP3-2446
** AIX nível 73-TL2-SP2-2420
** Nível AIX 72-TL5-SP8-2420


--
.Opcionalmente, defina ANATT para 120 segundos
--
A IBM fornece um ifix que define o ANATT para 120 segundos.  Quando você define o ANATT para 120 segundos, ele melhora o desempenho durante eventos de failover de armazenamento ONTAP .  O ifix está disponível por meio do ID do caso IBM TS012877410 e você pode instalá-lo para as seguintes versões do AIX:

** Para o nível AIX 73-TL3-SP0-2446, instale o `IJ53487s0a.250130.epkg.Z` pacote.
** Para o nível AIX 72-TL5-SP9-2446, instale o `IJ53445s9a.250130.epkg.Z` pacote.


--
====
+
[NOTE]
====
A versão mínima do firmware do servidor para servidores Power9 para suporte a NVMe/FC é FW 950.

A versão mínima do firmware do servidor para servidores Power10 para suporte a NVMe/FC é FW 1010.

====
+
Para obter mais informações sobre como gerenciar ifixos, link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gerenciando correções provisórias no AIX"^]consulte .





== Etapa 1: confirme a configuração multipath para seu host

Quando você instala o sistema operacional AIX, o IBM MPIO usado para multicaminhos NVMe é habilitado por padrão.

.Passos
. Verifique se o multipathing NVMe está habilitado:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== Etapa 2: Configurar NVMe/FC

Você precisa configurar NVMe/FC para adaptadores Broadcom/Emulex no VIOS porque o suporte ao protocolo NVMe/FC está desabilitado no Virtual Fibre Channel (vFC) no VIOS.  O suporte ao protocolo NVMe/FC é habilitado no FC físico por padrão.

.Passos
. link:https://mysupport.netapp.com/matrix/["Verifique se você está usando o adaptador compatível"^] .
. Recuperar uma lista de adaptadores virtuais:
+
[source, cli]
----
lsmap -all -npiv
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. Habilite o suporte ao protocolo NVMe/FC em um adaptador executando o `ioscli vfcctrl` comando no VIOS:
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.Exemplo de saída
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Verifique se o suporte foi ativado no adaptador:
+
[source, cli]
----
lsattr -El vfchost0
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. Habilite o protocolo NVMe/FC para todos os adaptadores:
+
.. Altere o `dflt_enabl_nvme` valor do atributo de `viosnpiv0` pseudo dispositivo para `yes`.
.. Defina o `enable_nvme` valor do atributo como `yes` para todos os dispositivos host VFC.
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. Ative o protocolo NVMe/FC para adaptadores selecionados alterando o `enable_nvme` valor do atributo dispositivo host VFC para `yes`.
. Verifique se `FC-NVMe Protocol Device` foi criado no servidor:
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.Exemplo de saída
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Registre o NQN do host do servidor:
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. Verifique o NQN do host e verifique se ele corresponde à string NQN do host para o subsistema correspondente no array ONTAP:
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.Exemplo de saída
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Verifique se as portas do iniciador estão ativas e em execução e você pode ver os LIFs de destino.




== Etapa 3: Validar NVMe/FC

Verifique se os namespaces ONTAP estão corretos para a configuração NVMe/FC.

.Passos
. Verifique se os namespaces ONTAP refletem corretamente no host:
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.Exemplo de saída
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. Opcionalmente, verifique o status do multipathing:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== Etapa 4: Revise os problemas conhecidos

A configuração do host NVMe/FC para AIX com armazenamento ONTAP tem os seguintes problemas conhecidos:

[cols="10,30,30"]
|===
| Código Burt | Título | Descrição 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | Tempo APD padrão do NVMe/FC AIX a ser modificado para dar suporte a eventos de switchover não planejado de MCC | Por padrão, os sistemas operacionais AIX usam um valor de tempo limite de todos os caminhos para baixo (APD) de 20sec para NVMe/FC. No entanto, os fluxos de trabalho de switchover não planejado (AUSO) e de transição iniciados pelo tiebreaker do ONTAP MetroCluster podem levar um pouco mais do que a janela de tempo limite do APD, causando erros de e/S. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | AIX NVMe/FC CAPS ANATT em 60s, em vez de 120s como anunciado pela ONTAP | O ONTAP anuncia o tempo limite de transição ANA (Asymmetric namespace Access) no controlador Identify em 120sec. Atualmente, com o ifix, o AIX lê o tempo limite de transição ANA do controlador Identify, mas efetivamente o prende a 60sec se estiver acima desse limite. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | AIX NVMe/FC atinge EIO após a expiração da ANATT | Para qualquer evento de failover de armazenamento (SFO), se a transição ANA (Asymmetric namespace Access) exceder o limite de tempo limite de transição ANA em um determinado caminho, o host AIX NVMe/FC falha com um erro de e/S apesar de ter caminhos alternativos de integridade disponíveis para o namespace. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC espera que o ANATT meio/completo expire antes de retomar a I/o após o ANA AEN | O IBM AIX NVMe/FC não oferece suporte a algumas notificações assíncronas (AENs) publicadas pelo ONTAP. Esta manipulação ANA sub-ótima resultará em desempenho abaixo do ideal durante as operações de SFO. 
|===


== Etapa 5: Solução de problemas

Antes de solucionar quaisquer falhas de NVMe/FC, verifique se você está executando uma configuração compatível com olink:https://mysupport.netapp.com/matrix/["IMT"^] especificações.  Se você continuar tendo problemas, entre em contatolink:https://mysupport.netapp.com["Suporte à NetApp"^] .
