---
sidebar: sidebar 
permalink: nvme-rockylinux-90.html 
keywords: nvme, linux, rocky linux, enterprise 
summary: Como configurar o host NVMe-oF para Rocky Linux 9.0 com ONTAP 
---
= Configurar o Rocky Linux 9.0 com NVMe-oF para armazenamento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os hosts Rocky Linux 9.0 suportam os protocolos NVMe/FC e NVMe/TCP com Acesso Assimétrico ao Namespace (ANA). ANA é equivalente ao multipathing de acesso assimétrico à unidade lógica (ALUA) em ambientes iSCSI e FCP e é implementado usando o recurso multipath NVMe no kernel.

Para obter detalhes adicionais sobre as configurações suportadas, consulte o link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^].

.Sobre esta tarefa
Você pode usar o seguinte suporte e recursos com a configuração do host NVMe-oF para o Rocky Linux 9.0. Você também deve rever as limitações conhecidas antes de iniciar o processo de configuração.

* Suporte disponível:
+
** Suporte a NVMe em TCP (NVMe/TCP), além de NVMe em Fibre Channel (NVMe/FC). O plug-in do NetApp no pacote nativo `nvme-cli` exibe detalhes do ONTAP para namespaces NVMe/FC e NVMe/TCP.
** Executando o tráfego NVMe e SCSI no mesmo host. Por exemplo, você pode configurar dm-multipath para dispositivos SCSI mpath em LUNs SCSI e usar NVMe multipath para configurar dispositivos de namespace NVMe-oF no host.


* Caraterísticas disponíveis:
+
** O Rocky Linux 9.0 habilita multicaminhos NVMe no kernel para namespaces NVMe por padrão, eliminando a necessidade de configurações explícitas.


* Limitações conhecidas:
+
** A inicialização DE SAN usando o protocolo NVMe-of não é atualmente suportada.






== Passo 1: Opcionalmente, ative a inicialização de SAN

Você pode configurar seu host para usar a inicialização SAN para simplificar a implantação e melhorar a escalabilidade.

.Antes de começar
Use o link:https://mysupport.netapp.com/matrix/#welcome["Ferramenta de Matriz de interoperabilidade"^] para verificar se o sistema operacional Linux, o adaptador de barramento do host (HBA), o firmware HBA, o BIOS de inicialização HBA e a versão do ONTAP suportam inicialização por SAN.

.Passos
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Crie um namespace de inicialização SAN e mapeie-o para o host"^].
. Habilite a inicialização SAN no BIOS do servidor para as portas para as quais o namespace de inicialização SAN está mapeado.
+
Para obter informações sobre como ativar o BIOS HBA, consulte a documentação específica do fornecedor.

. Verifique se a configuração foi bem-sucedida reinicializando o host e verificando se o sistema operacional está funcionando.




== Etapa 2: Validar versões de software

Use o procedimento a seguir para validar as versões mínimas suportadas do software Rocky Linux 9.0.

.Passos
. Instale o Rocky Linux 9.0 no servidor. Após a conclusão da instalação, verifique se você está executando o kernel especificado do Rocky Linux 9.0:
+
[source, cli]
----
uname -r
----
+
O exemplo a seguir mostra uma versão do kernel do Rocky Linux:

+
[listing]
----
5.14.0-570.12.1.el9_6.x86_64
----
. Instale o `nvme-cli` pacote:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
O exemplo a seguir mostra uma versão do pacote nvme-cli:

+
[listing]
----
nvme-cli-2.11-5.el9.x86_64
----
. Instale o `libnvme` pacote:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
O exemplo a seguir mostra um  `libnvme` versão do pacote:

+
[listing]
----
libnvme-1.11.1-1.el9.x86_64
----
. No host Rocky Linux, verifique a string hostnqn em  `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
O exemplo a seguir mostra um  `hostnqn` versão:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
----
. Verifique se a `hostnqn` cadeia corresponde à `hostnqn` cadeia para o subsistema correspondente na matriz ONTAP:
+
[source, cli]
----
::> vserver nvme subsystem host show -vserver vs_coexistence_LPE36002
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_coexistence_LPE36002
        nvme
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
        nvme_3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0056-5410-8048-b9c04f425633
4 entries were displayed.
----
====
+

NOTE: Se as `hostnqn` strings não corresponderem, use o `vserver modify` comando para atualizar a `hostnqn` cadeia de carateres no subsistema de matriz ONTAP correspondente para corresponder à `hostnqn` cadeia de carateres `/etc/nvme/hostnqn` do host.





== Etapa 3: Configurar NVMe/FC

Você pode configurar o NVMe/FC com adaptadores Broadcom/Emulex FC ou Marvell/Qlogic FC. Você também precisa descobrir manualmente os subsistemas e namespaces NVMe/TCP.

[role="tabbed-block"]
====
.Broadcom/Emulex
Configurar o NVMe/FC para um adaptador Broadcom/Emulex.

--
.Passos
. Verifique se você está usando o modelo de adaptador suportado:
+
.. Exibir os nomes dos modelos:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Você deve ver a seguinte saída:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Exibir as descrições do modelo:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Verifique se você está usando o firmware Broadcom recomendado e o driver da `lpfc` caixa de entrada:
+
.. Exibir a versão do firmware:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
O exemplo a seguir mostra as versões de firmware:

+
[listing]
----
14.4.317.10, sli-4:6:d
14.4.317.10, sli-4:6:d
----
.. Exibir a versão do driver da caixa de entrada:
+
[source, cli]
----
cat /sys/module/lpfc/version`
----
+
O exemplo a seguir mostra uma versão do driver:

+
[listing]
----
0:14.4.0.2
----


+
Para obter a lista atual de versões de firmware e drivers de adaptador suportados, consulte link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^].

. Verifique se a saída esperada de `lpfc_enable_fc4_type` está definida como `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Verifique se você pode exibir suas portas do iniciador:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
O exemplo a seguir mostra identidades de porta:

+
[listing]
----
0x100000109bf044b1
0x100000109bf044b2
----
. Verifique se as portas do iniciador estão online:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Você deve ver a seguinte saída:

+
[listing]
----
Online
Online
----
. Verifique se as portas do iniciador NVMe/FC estão ativadas e se as portas de destino estão visíveis:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Mostrar exemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x022a00 *ONLINE*
NVME RPORT       WWPN x202fd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x021310 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x202dd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020b10 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000810 Cmpl 0000000810 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007b098f07 Issue 000000007aee27c4 OutIO ffffffffffe498bd
        abort 000013b4 noxri 00000000 nondlp 00000058 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000013b4 Err 00021443

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x021b00 *ONLINE*
NVME RPORT       WWPN x2033d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020110 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2032d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x022910 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000840 Cmpl 0000000840 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007afd4434 Issue 000000007ae31b83 OutIO ffffffffffe5d74f
        abort 000014a5 noxri 00000000 nondlp 0000006a qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000014a5 Err 0002149a
----
=====


--
.Marvell/QLogic
--
Configure o NVMe/FC para um adaptador Marvell/QLogic.


NOTE: O driver nativo qla2xxx da caixa de entrada incluído no kernel do Rocky Linux tem as correções mais recentes. Essas correções são essenciais para o suporte ao ONTAP.

.Passos
. Verifique se você está executando o driver de adaptador e as versões de firmware compatíveis:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
O exemplo a seguir mostra as versões do driver e do firmware:

+
[listing]
----
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
----
. Verifique se `ql2xnvmeenable` está definido. Isso permite que o adaptador Marvell funcione como um iniciador NVMe/FC:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
A saída esperada é 1.



--
====


== Etapa 4: opcionalmente, habilite 1 MB de E/S

Você pode habilitar solicitações de E/S de 1 MB para NVMe/FC configurado com um adaptador Broadcom. O ONTAP relata um Tamanho Máximo de Transferência de Dados (MDTS) de 8 nos dados do Controlador de Identificação. Isso significa que o tamanho máximo da solicitação de e/S pode ser de até 1MBMB. Para emitir solicitações de E/S de 1 MB, você precisa aumentar o valor de lpfc do  `lpfc_sg_seg_cnt` parâmetro para 256 do valor padrão de 64.


NOTE: Essas etapas não se aplicam a hosts Qlogic NVMe/FC.

.Passos
. Defina `lpfc_sg_seg_cnt` o parâmetro como 256:
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Execute o `dracut -f` comando e reinicie o host.
. Verifique se o valor para `lpfc_sg_seg_cnt` é 256:
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Etapa 5: Configurar NVMe/TCP

O protocolo NVMe/TCP não suporta a `auto-connect` operação. Em vez disso, você pode descobrir os subsistemas e namespaces NVMe/TCP executando as operações NVMe/TCP `connect` ou `connect-all` manualmente.



== Etapa 6: Validar NVMe-oF

Verifique se o status multipath do NVMe no kernel, o status ANA e os namespaces do ONTAP estão corretos para a configuração do NVMe-of.

.Passos
. Verifique se o multipath NVMe no kernel está habilitado:
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Você deve ver a seguinte saída:

+
[listing]
----
Y
----
. Verifique se as configurações de NVMe-of apropriadas (como o modelo definido como controlador NetApp ONTAP e o balanceamento de carga iopolicy definido como round-robin) para os respetivos namespaces ONTAP refletem corretamente no host:
+
.. Exibir os subsistemas:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Você deve ver a seguinte saída:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Exibir a política:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Você deve ver a seguinte saída:

+
[listing]
----
round-robin
round-robin
----


. Verifique se os namespaces são criados e descobertos corretamente no host:
+
[source, cli]
----
nvme list
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====




== Passo 7: Revise os problemas conhecidos

A configuração do host NVMe-oF para Rocky Linux 9.0 com ONTAP tem os seguintes problemas conhecidos:

[cols="20,40,40"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"^] | Hosts Rocky Linux 9.0 NVMe-oF criam controladores de descoberta persistentes duplicados | Em hosts NVMe over Fabrics (NVMe-of), você pode usar o comando "nvme Discover -p" para criar PDCs (Controladoras de descoberta persistentes). Quando este comando é usado, apenas um PDC deve ser criado por combinação iniciador-alvo. Entretanto, se você estiver executando o ONTAP 9.10.1 e o Rocky Linux 9.0 com um host NVMe-oF, um PDC duplicado será criado sempre que "nvme discover -p" for executado. Isso leva ao uso desnecessário de recursos no host e no destino. 
|===