---
sidebar: sidebar 
permalink: nvme_windows_2012r2.html 
keywords: nvme, windows, enterprise 
summary: 'Você pode configurar o NVMe em Fibre Channel (NVMe/FC) em hosts que executam o Windows Server 2012 R2 para operação com LUNs ONTAP.' 
---
= Configurar o Windows Server 2012 R2 com NVMe/FC para ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode configurar o NVMe em Fibre Channel (NVMe/FC) em hosts que executam o Windows Server 2012 R2 para operação com LUNs ONTAP.

.Sobre esta tarefa
Você pode usar o suporte a seguir com a configuração de host NVMe/FC para Windows 2012 R2. Você também deve rever as limitações conhecidas antes de iniciar o processo de configuração.


NOTE: Pode utilizar as definições de configuração fornecidas neste procedimento para configurar os clientes em nuvem ligados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] e link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].

* Suporte disponível:
+
A partir do ONTAP 9,7, o NVMe/FC é compatível com o Windows Server 2012 R2.

+
Para obter uma lista de adaptadores e controladores FC compatíveis, consulte link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. Para obter a lista atual de configurações e versões suportadas, consulte link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade"^].

* Limitações conhecidas:
+
O cluster de failover do Windows não é compatível com NVMe/FC porque o ONTAP não oferece suporte a reservas persistentes com NVMe/FC.

+

NOTE: A Broadcom envia um driver externo para Windows NVMe/FC que é um driver SCSI ⇄ NVMe translacional e não um verdadeiro driver NVMe/FC. A sobrecarga translacional não afeta necessariamente o desempenho, mas nega os benefícios de desempenho do NVMe/FC. Como resultado, a performance de NVMe/FC e FCP é a mesma em servidores Windows, ao contrário de outros sistemas operacionais, como o Linux, em que a performance de NVMe/FC é significativamente melhor do que a do FCP.





== Habilite o NVMe/FC

Habilite o FC/NVMe no host iniciador do Windows.

.Passos
. Instale o utilitário OneCommand Manager no host do Windows.
. Em cada uma das portas do iniciador HBA, defina os seguintes parâmetros do controlador HBA:
+
** EnableNVMe: 1
** NVMEMode (modo NVMEMode): 0


. Reinicie o host.




== Configure o adaptador Broadcom FC

O iniciador Broadcom pode atender ao tráfego NVMe/FC e FCP nas mesmas portas de adaptador de FC de 32G GB. Para FCP e FC/NVMe, deve utilizar o módulo específico do dispositivo (DSM) Microsft como a opção Microsoft Multipath I/o (MPIO).

A `+hostnqn+` é associada a cada porta do adaptador de barramento do host (HBA) para o adaptador Broadcom com com FC/NVMe em um ambiente Windows. O `+hostnqn+` é formatado como mostrado no exemplo a seguir:

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Ative o MPIO para dispositivos NVMe

Você precisa habilitar o MPIO para dispositivos NVMe para concluir a configuração NVMe no host do Windows.

.Passos
. Instale link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Kit de utilitário de host do Windows 7,1"] para definir os parâmetros do driver que são comuns ao FC e ao NVMe.
. Abra as propriedades MPIO.
. Na guia *Discover Multi-paths*, adicione a ID do dispositivo listada para NVMe.
+
O MPIO toma conhecimento dos dispositivos NVMe, que são visíveis no gerenciamento de disco.

. Abra *Disk Management* e vá para *Disk Properties*.
. Na guia *MPIO*, selecione *Detalhes*.
. Defina as seguintes definições do Microsoft DSM:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Enable* (Ativar)
** RetryCount: *6*
** RetryInterval: *1*
** PDORemovedPeriod: *130*


. Selecione a Política MPIO *Round Robin with Subset*.
. Altere os valores do registo:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Reinicie o host.




== Validar o NVMe/FC

Verifique se os subsistemas NVMe foram descobertos e os namespaces ONTAP estão corretos para a configuração NVMe-of.

.Passos
. Verifique se "tipo de porta" é `+FC+NVMe+`:
+
`listhba`

+
.Mostrar exemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. Verifique se os subsistemas NVMe/FC foram descobertos:
+
** `+nvme-list+`
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. Verifique se os namespaces foram criados:
+
`+nvme-list-ns+`

+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

