---
sidebar: sidebar 
permalink: nvme_rhel_87.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Como configurar o host NVMe-of para RHEL 8,7 com o ONTAP 
---
= Configuração de host NVMe-of para RHEL 8,7 com ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NVMe over Fabrics ou NVMe-of (incluindo NVMe/FC e outros transportes) é compatível com Red Hat Enterprise Linux (RHEL) 8,7 com ANA (acesso de namespace assimétrico). ANA é o equivalente de acesso por unidade lógica assimétrica (ALUA) no ambiente NVMe-of e atualmente é implementado com o NVMe Multipath no kernel. Durante esse procedimento, você habilita o NVMe-of com o Multipath NVMe no kernel usando ANA no RHEL 8,7 e ONTAP como destino.

Consulte a link:https://mysupport.netapp.com/matrix/["Ferramenta de Matriz de interoperabilidade do NetApp"^] para obter detalhes precisos sobre as configurações suportadas.



== Caraterísticas

O RHEL 8,7 inclui suporte para NVMe/TCP (como recurso de prévia tecnologia), além de NVMe/FC. O plugin NetApp no pacote nativo nvme-cli é capaz de exibir detalhes do ONTAP para namespaces NVMe/FC e NVMe/TCP.



== Limitações conhecidas

* Para RHEL 8,7, o multipath NVMe no kernel permanece desativado por padrão. Portanto, você precisa ativá-lo manualmente.
* O NVMe/TCP no RHEL 8,7 continua sendo um recurso de visualização de tecnologia devido a problemas de abertura. Consultelink:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.7_release_notes/index["RHEL 8,7 notas de lançamento"^] para obter mais informações.
* A inicialização DE SAN usando o protocolo NVMe-of não é atualmente suportada.




== Habilite o NVMe Multipath no kernel

Você pode usar o seguinte procedimento para ativar o multipath NVMe no kernel.

.Passos
. Instale o RHEL 8,7 no servidor.
. Depois que a instalação estiver concluída, verifique se você está executando o kernel RHEL 8,7 especificado. Consulte a link:https://mysupport.netapp.com/matrix/["Matriz de interoperabilidade do NetApp"^] para obter a lista mais atual de versões suportadas.
+
Exemplo:

+
[listing]
----
# uname -r
4.18.0-425.3.1.el8.x86_64
----
. Instale o `nvme-cli` pacote:
+
Exemplo:

+
[listing]
----
# rpm -qa|grep nvme-cli
nvme-cli-1.16-5.el8.x86_64
----
. Ativar multipath NVMe no kernel:
+
*Exemplo*

+
[listing]
----
# grubby --args=nvme_core.multipath=Y --update-kernel
/boot/vmlinuz-4.18.0-425.3.1.el8.x86_64
----
. No host, verifique a string NQN do host em `/etc/nvme/hostnqn` e verifique se ela corresponde à string NQN do host para o subsistema correspondente no array ONTAP. Exemplo:
+
[listing]
----

# cat /etc/nvme/hostnqn

          nqn.2014-08.org.nvmexpress:uuid:a7f7a1d4-311a-11e8-b634-            7ed30aef10b7

::> vserver nvme subsystem host show -vserver vs_nvme167
Vserver     Subsystem       Host NQN
----------- --------------- ----------------
vs_nvme167 rhel_167_LPe35002  nqn.2014-08.org.nvmexpress:uuid: a7f7a1d4-311a-11e8-b634-7ed30aef10b7

----
+

NOTE: Se as strings NQN do host não corresponderem, você deve usar o `vserver modify` comando para atualizar a string NQN do host no subsistema NVMe do ONTAP correspondente para corresponder à string NQN do host `/etc/nvme/hostnqn`.

. Reinicie o host.
+
[NOTE]
====
Se você pretende executar o tráfego coexistente NVMe e SCSI no mesmo host, a NetApp recomenda o uso de multipath NVMe no kernel para namespaces ONTAP e dm-multipath para LUNs ONTAP, respetivamente. Isso significa que os namespaces do ONTAP devem ser excluídos do dm-multipath para evitar que o dm-multipath recupere esses dispositivos de namespace. Você pode fazer isso adicionando a configuração enable_Foreign ao `/etc/multipath.conf` arquivo:

[listing]
----
# cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
Reinicie o daemon multipathd executando um `systemctl restart multipathd` comando para permitir que a nova configuração entre em vigor.

====




== Configurar o NVMe/FC

Você pode configurar o NVMe/FC para adaptadores Broadcom/Emulex ou Marvell/Qlogic.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
.Passos
. Verifique se você está usando o adaptador suportado. Consulte a link:https://mysupport.netapp.com/matrix/["Matriz de interoperabilidade do NetApp"^] para obter a lista mais atual de adaptadores suportados.
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
LPe35002-M2
LPe35002-M2
# cat /sys/class/scsi_host/host*/modeldesc
Emulex LightPulse LPe35002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe35002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Verifique se você está usando o firmware Broadcom lpfc recomendado e o driver da caixa de entrada. Consulte a link:https://mysupport.netapp.com/matrix/["Matriz de interoperabilidade do NetApp"^] para obter a lista mais atual de versões de firmware e drivers de adaptador suportados.
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.0.505.12, sli-4:6:d
14.0.505.12, sli-4:6:d
# cat /sys/module/lpfc/version
0:14.0.0.15
----
. Verifique se `lpfc_enable_fc4_type` está definido como 3
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Verifique se as portas do iniciador estão ativas e em execução e se você pode ver os LIFs de destino.
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b95467c
0x100000109b95467b
# cat /sys/class/fc_host/host*/port_state
Online
Online
# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b95467c WWNN x200000109b95467c DID x0a1500 ONLINE
NVME RPORT       WWPN x2071d039ea36a105 WWNN x206ed039ea36a105 DID x0a0907 TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x2072d039ea36a105 WWNN x206ed039ea36a105 DID x0a0805 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 00000001c7 Cmpl 00000001c7 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000004909837 Issue 0000000004908cfc OutIO fffffffffffff4c5
abort 0000004a noxri 00000000 nondlp 00000458 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000061 Err 00017f43

NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b95467b WWNN x200000109b95467b DID x0a1100 ONLINE
NVME RPORT       WWPN x2070d039ea36a105 WWNN x206ed039ea36a105 DID x0a1007 TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x206fd039ea36a105 WWNN x206ed039ea36a105 DID x0a0c05 TARGET DISCSRVC ONLINE

NVME Statistics
LS: Xmt 00000001c7 Cmpl 00000001c7 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000004909464 Issue 0000000004908531 OutIO fffffffffffff0cd
abort 0000004f noxri 00000000 nondlp 00000361 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 0000006b Err 00017f99
----


--
.Adaptador Marvell/QLogic FC para NVMe/FC
--
O driver nativo da caixa de entrada `qla2xxx` incluído no kernel RHEL 8,7 tem as correções mais recentes. Essas correções são essenciais para o suporte ao ONTAP.

.Passos
. Verifique se você está executando o driver de adaptador suportado e as versões de firmware usando o seguinte comando:
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
QLE2772 FW:v9.08.02 DVR:v10.02.07.400-k-debug
QLE2772 FW:v9.08.02 DVR:v10.02.07.400-k-debug
----
. Verify is `ql2xnvmeenable` set, que permite que o adaptador Marvell funcione como um iniciador NVMe/FC usando o seguinte comando:
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


--
====


=== Ativar 1MB I/o (Opcional)

O ONTAP relata um MDTS (MAX Data Transfer Size) de 8 nos dados do controlador de identificação. Isso significa que o tamanho máximo da solicitação de e/S pode ser de até 1MBMB. Para emitir solicitações de e/S de tamanho 1 MB para um host NVMe/FC Broadcom, você deve aumentar `lpfc` o valor `lpfc_sg_seg_cnt` do parâmetro para 256 do valor padrão 64.


NOTE: Essas etapas não se aplicam a hosts Qlogic NVMe/FC.

.Passos
. Defina `lpfc_sg_seg_cnt` o parâmetro como 256:
+
[listing]
----
cat /etc/modprobe.d/lpfc.conf
----
+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Execute o `dracut -f` comando e reinicie o host.
. Verifique se o valor esperado de `lpfc_sg_seg_cnt` é 256:
+
[listing]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Configurar o NVMe/TCP

O NVMe/TCP não tem a funcionalidade de conexão automática. Portanto, se um caminho for desativado e não for restaurado dentro do período de tempo limite padrão de 10 minutos, o NVMe/TCP não poderá se reconetar automaticamente. Para evitar um tempo limite, você deve definir o período de repetição para eventos de failover para pelo menos 30 minutos.

.Passos
. Verifique se a porta do iniciador pode buscar os dados da página de log de descoberta nas LIFs NVMe/TCP suportadas:
+
[listing]
----
# nvme discover -t tcp -w 192.168.211.5 -a 192.168.211.14

Discovery Log Number of Records 8, Generation counter 10

=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  0
trsvcid: 8009
subnqn:  nqn.199208.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.111.15
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.14
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.111.14
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
traddr:  192.168.111.15
sectype: none
=====Discovery Log Entry 6======

trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
traddr:  192.168.211.14
sectype: none

=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified

   portid:  3

trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
traddr:  192.168.111.14
sectype: none
[root@R650-13-79 ~]#
----
. Verifique se outros combos de LIF entre iniciador e destino NVMe/TCP podem obter com sucesso os dados da página de log de descoberta. Por exemplo:
+
[listing]
----
# nvme discover -t tcp -w 192.168.211.5 -a 192.168.211.14
# nvme discover -t tcp -w 192.168.211.5 -a 192.168.211.15
# nvme discover -t tcp -w 192.168.111.5 -a 192.168.111.14
# nvme discover -t tcp -w 192.168.111.5 -a 192.168.111.15

----
. Execute `nvme connect-all` o comando em todos os LIFs de destino do iniciador NVMe/TCP compatíveis nos nós. Certifique-se de definir um período de repetição do temporizador mais longo `ctrl_loss_tmo` (por exemplo, 30 minutos, que pode ser definido através `-l 1800`de ) durante a ligação de tudo para que tente novamente durante um período de tempo mais longo em caso de perda de caminho. Por exemplo:
+
[listing]
----
# nvme connect-all -t tcp -w 192.168.211.5-a 192.168.211.14 -l 1800
# nvme connect-all -t tcp -w 192.168.211.5 -a 192.168.211.15 -l 1800
# nvme connect-all -t tcp -w 192.168.111.5 -a 192.168.111.14 -l 1800
# nvme connect-all -t tcp -w 192.168.111.5 -a 192.168.111.15 -l 1800
----




== Validar o NVMe-of

Use o procedimento a seguir para validar o NVMe-of.

.Passos
. Verifique se o multipath NVMe no kernel está realmente habilitado, verificando:
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
. Verifique se as configurações de NVMe-of apropriadas (como, `model` definido como `NetApp ONTAP Controller` e balanceamento de carga `iopolicy` definido como `round-robin`) para os respetivos namespaces do ONTAP refletem adequadamente no host:
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller

# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Verifique se os namespaces do ONTAP refletem corretamente no host. Por exemplo:
+
[listing]
----
# nvme list
Node           SN                    Model                   Namespace
------------   --------------------- ---------------------------------
/dev/nvme0n1   81Gx7NSiKSRNAAAAAAAB   NetApp ONTAP Controller   1

Usage                Format         FW Rev
-------------------  -----------    --------
21.47  GB /  21.47  GB  4 KiB + 0 B    FFFFFFFF
----
. Verifique se o estado do controlador de cada caminho está ativo e tem o status ANA adequado. Por exemplo:
+
[listing, subs="+quotes"]
----
# nvme list-subsys /dev/nvme1n1

nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165

\

 +- nvme0 tcp traddr=192.168.211.15 trsvcid=4420 host_traddr=192.168.211.5 live non-optimized

 +- nvme1 tcp traddr=192.168.211.14 trsvcid=4420 host_traddr=192.168.211.5 live optimized

 +- nvme2 tcp traddr=192.168.111.15 trsvcid=4420 host_traddr=192.168.111.5 live non-optimized

 +- nvme3 tcp traddr=192.168.111.14 trsvcid=4420 host_traddr=192.168.111.5 live optimized
----
. Verifique se o plug-in NetApp exibe os valores adequados para cada dispositivo de namespace ONTAP. Por exemplo:
+
[listing]
----
# nvme netapp ontapdevices -o column
Device       Vserver          Namespace Path
---------    -------          --------------------------------------------------
/dev/nvme0n1 vs_tcp79     /vol/vol1/ns1 

NSID  UUID                                   Size
----  ------------------------------         ------
1     79c2c569-b7fa-42d5-b870-d9d6d7e5fa84  21.47GB


# nvme netapp ontapdevices -o json
{

  "ONTAPdevices" : [
  {

      "Device" : "/dev/nvme0n1",
      "Vserver" : "vs_tcp79",
      "Namespace_Path" : "/vol/vol1/ns1",
      "NSID" : 1,
      "UUID" : "79c2c569-b7fa-42d5-b870-d9d6d7e5fa84",
      "Size" : "21.47GB",
      "LBA_Data_Size" : 4096,
      "Namespace_Size" : 5242880
    },

]

}
----




== Problemas conhecidos

A configuração de host NVMe-of para RHEL 8,7 com ONTAP tem os seguintes problemas conhecidos:

[cols="20,40,40"]
|===
| ID de erro do NetApp | Título | Descrição 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"^] | Os hosts NVMe-of RHEL 8,7 criam controladoras de descoberta persistente duplicadas | Em hosts NVMe over Fabrics (NVMe-of), você pode usar o comando "nvme Discover -p" para criar PDCs (Controladoras de descoberta persistentes). Quando este comando é usado, apenas um PDC deve ser criado por combinação iniciador-alvo. No entanto, se você estiver executando o ONTAP 9.10,1 e o Red Hat Enterprise Linux (RHEL) 8,7 com um host NVMe-of, um PDC duplicado será criado sempre que "nvme Discover -p" for executado. Isso leva ao uso desnecessário de recursos no host e no destino. 
|===