---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Este conteúdo fornece orientação específica para distribuição sobre como configurar clientes em nuvem conetados ao Cloud Volumes ONTAP e aos hosts do Amazon FSX for ONTAP e SAN conetados ao armazenamento ONTAP local. 
---
= Saiba mais sobre as configurações de host SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve configurar hosts SAN para multipathing e com parâmetros e configurações específicos críticos para a operação correta com LUNs ONTAP. A configuração do host varia dependendo do sistema operacional do host e do protocolo. A configuração correta é importante para o melhor desempenho e o failover bem-sucedido.

Você deve configurar seus hosts SAN para usar os Utilitários de host SAN NetApp. Os utilitários de host SAN ajudam a gerenciar e monitorar LUNs e adaptadores de barramento de host (HBAs). Por exemplo, você pode usar os Utilitários de host SAN para recuperar uma lista de todos os LUNs mapeados para um host ou para ver uma lista de todos os atributos de um LUN específico mapeado para um host. O suporte ao cliente do NetApp também pode usar os Utilitários de host SAN para coletar informações sobre sua configuração se você tiver um problema que exija assistência.

A NetApp recomenda o uso do software de utilitários de host SAN, se estiver disponível para seu host SAN.

Se a sua configuração de SAN suportar a inicialização de SAN, você também pode configurar seu host para usar a inicialização de SAN para simplificar a implantação e melhorar a escalabilidade. Usando a inicialização SAN, você pode implantar vários novos servidores conetando-os à SAN e configurando as configurações de inicialização apropriadas. Isso economiza tempo, eliminando a necessidade de instalar o sistema operacional em cada servidor individualmente.

Seus hosts SAN e o storage ONTAP podem residir no local, na nuvem ou em ambos.


NOTE: Em um ambiente de nuvem, os hosts são normalmente chamados de clientes. Todas as informações específicas do host neste conteúdo também se aplicam a clientes na nuvem.

Por exemplo, você pode configurar o armazenamento ONTAP local para se conectar a hosts SAN locais ou clientes de nuvem SAN.  Você também pode configurar serviços de armazenamento em execução em um ambiente de nuvem, comolink:https://docs.netapp.com/us-en/cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] oulink:https://docs.netapp.com/us-en/storage-management-fsx-ontap/index.html["Amazon FSX para NetApp ONTAP"^] para se conectar a hosts SAN locais ou clientes de nuvem SAN.

.Informações relacionadas
* link:https://docs.netapp.com/us-en/ontap/san-config/index.html["Referência de configuração de SAN ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Gerenciamento de storage SAN ONTAP"^]
* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de versão do ONTAP 9"^]
* Documentação relacionada com o SANtricity no link:https://docs.netapp.com/us-en/e-series/index.html["Documentação dos sistemas e-Series"^]

