---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Este conteúdo fornece orientação específica para distribuição sobre como configurar clientes em nuvem conetados ao Cloud Volumes ONTAP e aos hosts do Amazon FSX for ONTAP e SAN conetados ao armazenamento ONTAP local. 
---
= Visão geral da configuração do host SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os hosts DE SAN devem ser configurados para multipathing e com parâmetros específicos e configurações essenciais para a operação adequada com LUNs ONTAP. A configuração do host varia dependendo do sistema operacional do host e do protocolo. A configuração correta é importante para o melhor desempenho e o failover bem-sucedido.

Você deve configurar seus hosts SAN para usar os utilitários de host SAN NetApp. Os utilitários de host SAN ajudam a gerenciar e monitorar LUNs e adaptadores de barramento de host (HBAs). Por exemplo, você pode usar os utilitários de host SAN para recuperar uma lista de todos os LUNs mapeados para um host ou para ver uma lista de todos os atributos de um LUN específico mapeados para um host. O suporte ao cliente da NetApp também pode usar os utilitários de host SAN para coletar informações sobre sua configuração se você tiver um problema que exija assistência.

A NetApp recomenda o uso do software de utilitários de host SAN se ele estiver disponível para o seu host SAN.

Se ele for suportado pela configuração de SAN, você também pode configurar seu host para usar a inicialização de SAN para implantação simplificada e escalabilidade aprimorada. Usando a inicialização SAN, você pode implantar vários novos servidores conetando-os à SAN e configurando as configurações de inicialização apropriadas. Isso economiza tempo, eliminando a necessidade de instalar o sistema operacional em cada servidor individualmente.

Seus hosts SAN e o storage ONTAP podem residir no local, na nuvem ou em ambos.


NOTE: Em um ambiente de nuvem, os hosts são normalmente chamados de clientes. Todas as informações específicas do host neste conteúdo também se aplicam a clientes na nuvem.

Por exemplo, você pode configurar o storage ONTAP no local para se conectar a hosts SAN no local ou a clientes de nuvem SAN. Você também pode configurar serviços de storage em execução em um ambiente de nuvem, como link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] ou link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/index.html["Amazon FSX para NetApp ONTAP"^] para se conetar a hosts SAN no local ou a clientes de nuvem SAN.

.Informações relacionadas
* A link:https://docs.netapp.com/us-en/ontap/san-config/index.html["Configuração SAN ONTAP"^] para a sua versão do ONTAP
* A link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Guia de administração de SAN ONTAP"^] para a sua versão do ONTAP
* A link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de versão do ONTAP"^] para a sua versão do ONTAP
* link:https://docs.netapp.com/us-en/e-series/index.html["Documentação do e-Series"^]Para encontrar a documentação relacionada ao SANtricity.

