---
settings:
  name: ONTAP SAN Host Utilities
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Hosts SAN ONTAP e clientes em nuvem
    url: "/index.html"
  - title: Saiba mais sobre as configurações de host SAN
    url: "/overview.html"
  - title: Instale os Utilitários do host SAN
    entries:
    - title: Saiba mais sobre os utilitários de host SAN
      url: "/hu_sanhost_index.html"
    - title: AIX Host Utilities
      entries:
      - title: Notas de lançamento
        url: "/hu-aix-release-notes.html"
      - title: Instalar utilitários de host do AIX
        entries:
        - title: Instalar o AIX Host Utilities 8.0
          url: "/hu-aix-80.html"
        - title: Instale os Utilitários de host AIX 7,0
          url: "/hu-aix-70.html"
        - title: Instalar o AIX Host Utilities 6.1
          url: "/hu_aix_61.html"
      - title: Saiba mais sobre o AIX SAN Tollkit
        url: "/hu-aix-san-toolkit.html"
      - title: Referência de comando do AIX Host Utilities
        url: "/hu-aix-command-reference.html"
    - title: Utilitários de host HP-UX
      entries:
      - title: Notas de lançamento
        url: "/hu-hpux-release-notes.html"
      - title: Instale os utilitários de host HP-UX 6,0
        url: "/hu_hpux_60.html"
      - title: Saiba mais sobre o SAN Toolkit
        url: "/hu-hpux-sanlun-toolkit.html"
      - title: Saiba mais sobre a referência de comando do HP-UX
        url: "/hu_hpux_60_cmd.html"
    - title: Utilitários de host Linux
      entries:
      - title: Notas de lançamento
        url: "/hu-luhu-release-notes.html"
      - title: Instalar utilitários de host Linux
        entries:
        - title: Instalar o Linux Host Utilities 8.0
          url: "/hu-luhu-80.html"
        - title: Instale o Linux Host Utilities 7,1
          url: "/hu_luhu_71.html"
      - title: Saiba mais sobre o utilitário sanlun
        url: "/hu-luhu-sanlun-utility.html"
      - title: Referência de comandos do Linux Host Utilities
        url: "/hu-luhu-command-reference.html"
    - title: Utilitários do Solaris Host
      entries:
      - title: Notas de lançamento
        url: "/hu-solaris-release-notes.html"
      - title: Instale os Utilitários do Solaris Host
        entries:
        - title: Instalar o Solaris Host Utilities 8.0
          url: "/hu-solaris-80.html"
        - title: Instalar o Solaris Host Utilities 6.2
          url: "/hu_solaris_62.html"
      - title: Saiba mais sobre o SAN Toolkit
        url: "/hu-solaris-san-toolkit.html"
      - title: Saiba mais sobre a referência de comando do Solaris
        url: "/hu-solaris-command-reference.html"
    - title: Utilitários de host do Windows
      entries:
      - title: Notas de lançamento
        url: "/hu-wuhu-release-notes.html"
      - title: Instalar utilitários de host do Windows
        entries:
        - title: Instalar o Windows Host Utilities 8.0
          url: "/hu-wuhu-80.html"
        - title: Instale os Utilitários de host do Windows 7,2
          url: "/hu_wuhu_72.html"
        - title: Instale os Utilitários de host do Windows 7,1
          url: "/hu_wuhu_71.html"
      - title: Configurar definições para utilitários de host do Windows
        url: "/hu_wuhu_hba_settings.html"
      - title: Atualize os Utilitários do sistema anfitrião do Windows
        url: "/hu_wuhu_upgrade.html"
      - title: Repare e remova os Utilitários de host do Windows
        url: "/hu_wuhu_repair_remove.html"
      - title: Solucionar problemas
        url: "/hu_wuhu_troubleshoot.html"
  - title: Configurar hosts com FCP e iSCSI
    entries:
    - title: Visão geral
      url: "/hu_fcp_scsi_index.html"
    - title: AIX e PowerVM/VIOS
      entries:
      - title: 7.3/4.x
        url: "/hu-aix-73.html"
      - title: 7,2/3,1
        url: "/hu_aix_72.html"
      - title: '7,1'
        url: "/hu_aix_71.html"
    - title: CentOS
      entries:
      - title: CentOS 8.x
        url: "/hu-centos-8x.html"
      - title: CentOS 7
        entries:
        - title: '7,9'
          url: "/hu_centos_79.html"
        - title: '7,8'
          url: "/hu_centos_78.html"
        - title: '7,7'
          url: "/hu_centos_77.html"
        - title: '7,6'
          url: "/hu_centos_76.html"
        - title: '7,5'
          url: "/hu_centos_75.html"
        - title: '7,4'
          url: "/hu_centos_74.html"
        - title: '7,3'
          url: "/hu_centos_73.html"
        - title: '7,2'
          url: "/hu_centos_72.html"
        - title: '7,1'
          url: "/hu_centos_71.html"
        - title: '7,0'
          url: "/hu_centos_70.html"
      - title: CentOS 6
        entries:
        - title: '6,10'
          url: "/hu_centos_610.html"
        - title: '6,9'
          url: "/hu_centos_69.html"
        - title: '6,8'
          url: "/hu_centos_68.html"
        - title: '6,7'
          url: "/hu_centos_67.html"
        - title: '6,6'
          url: "/hu_centos_66.html"
        - title: '6,5'
          url: "/hu_centos_65.html"
        - title: '6,4'
          url: "/hu_centos_64.html"
    - title: Citrix
      entries:
      - title: Xenserver 8.4
        url: "/hu_citrix_84.html"
      - title: Hipervisor 8.2
        url: "/hu_citrix_82.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/hu_vsphere_8.html"
      - title: VMware vSphere 7
        url: "/hu_vsphere_7.html"
      - title: VMware vSphere 6,5 e 6,7
        url: "/hu_vsphere_6.html"
    - title: HP-UX
      entries:
      - title: 11i v3
        url: "/hu_hpux_11iv3.html"
    - title: Oracle Linux
      pdf-filename: OL-FCP
      entries:
      - title: 9.x
        url: "/hu-ol-9x.html"
      - title: 8.x
        url: "/hu-ol-8x.html"
      - title: Oracle Linux 7
        pdf-filename: OL-7-FCP
        entries:
        - title: '7,9'
          url: "/hu_ol_79.html"
        - title: '7,8'
          url: "/hu_ol_78.html"
        - title: '7,7'
          url: "/hu_ol_77.html"
        - title: '7,6'
          url: "/hu_ol_76.html"
        - title: '7,5'
          url: "/hu_ol_75.html"
        - title: '7,4'
          url: "/hu_ol_74.html"
        - title: '7,3'
          url: "/hu_ol_73.html"
        - title: '7,2'
          url: "/hu_ol_72.html"
        - title: '7,1'
          url: "/hu_ol_71.html"
        - title: '7,0'
          url: "/hu_ol_70.html"
      - title: Oracle Linux 6
        pdf-filename: OL-6-FCP
        entries:
        - title: '6,10'
          url: "/hu_ol_610.html"
        - title: '6,9'
          url: "/hu_ol_69.html"
        - title: '6,8'
          url: "/hu_ol_68.html"
        - title: '6,7'
          url: "/hu_ol_67.html"
        - title: '6,6'
          url: "/hu_ol_66.html"
        - title: '6,5'
          url: "/hu_ol_65.html"
        - title: '6,4'
          url: "/hu_ol_64.html"
    - title: Proxmox
      entries:
      - title: VE 9.x
        url: "/hu-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/hu-proxmox-ve-8x.html"
    - title: RHEL
      entries:
      - title: 10.x
        url: "/hu-rhel-10x.html"
        pdf-filename: RHEL-10-FCP
      - title: 9.x
        url: "/hu-rhel-9x.html"
        pdf-filename: RHEL-9-FCP
      - title: 8.x
        pdf-filename: RHEL-8-FCP
        url: "/hu-rhel-8x.html"
      - title: RHEL 7
        pdf-filename: RHEL-7-FCP
        entries:
        - title: '7,9'
          url: "/hu_rhel_79.html"
        - title: '7,8'
          url: "/hu_rhel_78.html"
        - title: '7,7'
          url: "/hu_rhel_77.html"
        - title: '7,6'
          url: "/hu_rhel_76.html"
        - title: '7,5'
          url: "/hu_rhel_75.html"
        - title: '7,4'
          url: "/hu_rhel_74.html"
        - title: '7,3'
          url: "/hu_rhel_73.html"
        - title: '7,2'
          url: "/hu_rhel_72.html"
        - title: '7,1'
          url: "/hu_rhel_71.html"
        - title: '7,0'
          url: "/hu_rhel_70.html"
      - title: RHEL 6
        pdf-filename: RHEL-6-FCP
        entries:
        - title: '6,10'
          url: "/hu_rhel_610.html"
        - title: '6,9'
          url: "/hu_rhel_69.html"
        - title: '6,8'
          url: "/hu_rhel_68.html"
        - title: '6,7'
          url: "/hu_rhel_67.html"
        - title: '6,6'
          url: "/hu_rhel_66.html"
        - title: '6,5'
          url: "/hu_rhel_65.html"
        - title: '6,4'
          url: "/hu_rhel_64.html"
    - title: Rocky Linux
      entries:
      - title: 10.x
        pdf-filename: RL-10-FCP
        url: "/hu-rockylinux-10x.html"
      - title: 9.x
        pdf-filename: RL-9-FCP
        url: "/hu-rockylinux-9x.html"
      - title: 8.x
        pdf-filename: RL-8-FCP
        url: "/hu-rockylinux-8x.html"
    - title: Solaris
      entries:
      - title: '11,4'
        url: "/hu-solaris-114.html"
      - title: '11,3'
        url: "/hu_solaris_113.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        pdf-filename: SLES-15-FCP
        url: "/hu-sles-15spx.html"
      - title: SUSE Linux Enterprise Server 12
        entries:
        - title: 12 SP 5
          url: "/hu_sles_12SP5.html"
        - title: 12 SP 4
          url: "/hu_sles_12SP4.html"
        - title: 12 SP 3
          url: "/hu_sles_12SP3.html"
        - title: 12 SP 2
          url: "/hu_sles_12SP2.html"
        - title: 12 SP 1
          url: "/hu_sles_12SP1.html"
        - title: '12'
          url: "/hu_sles_12.html"
    - title: Ubuntu
      pdf-filename: Ubuntu-FCP
      entries:
      - title: '24,04'
        url: "/hu_ubuntu_2404.html"
      - title: '22,04'
        url: "/hu_ubuntu_2204.html"
      - title: '20,04'
        url: "/hu_ubuntu_2004.html"
    - title: Veritas
      entries:
      - title: Infoscale 9
        url: "/hu-veritas-9x.html"
      - title: Infoscale 8
        url: "/hu-veritas-8x.html"
      - title: Infoscale 7
        url: "/hu-veritas-7x.html"
      - title: Base de storage 6
        url: "/hu_veritas_6x.html"
    - title: Windows
      pdf-filename: Windows-FCP
      entries:
      - title: '2025'
        url: "/hu-windows-2025.html"
      - title: '2022'
        url: "/hu_windows_2022.html"
      - title: '2019'
        url: "/hu_windows_2019.html"
      - title: '2016'
        url: "/hu_windows_2016.html"
      - title: 2012 R2
        url: "/hu_windows_2012r2.html"
  - title: Configurar hosts com o NVMe-of
    entries:
    - title: Saiba mais sobre como configurar hosts NVMe-oF
      url: "/hu-nvme-index.html"
    - title: AIX
      url: "/nvme_aix.html"
    - title: ESXi
      entries:
      - title: VMware vSphere 8
        url: "/nvme_esxi_8.html"
      - title: VMware vSphere 7
        url: "/nvme_esxi_7.html"
    - title: Oracle Linux
      pdf-filename: NVMeoF OL
      entries:
      - title: Suporte e recursos do ONTAP
        url: "/nvme-ol-supported-features.html"
      - title: 9.x
        url: "/nvme-ol-9x.html"
      - title: 8.x
        url: "/nvme-ol-8x.html"
      - title: 7.x
        url: "/nvme-ol-7x.html"
    - title: Proxmox
      pdf-filename: NVMeoF Proxmox
      entries:
      - title: Suporte e recursos do ONTAP
        url: "/nvme-proxmox-supported-features.html"
      - title: VE 9.x
        url: "/nvme-proxmox-ve-9x.html"
      - title: VE 8.x
        url: "/nvme-proxmox-ve-8x.html"
    - title: RHEL
      pdf-filename: NVMeoF RHEL
      entries:
      - title: Suporte e recursos do ONTAP
        url: "/nvme-rhel-supported-features.html"
      - title: 10.x
        url: "/nvme-rhel-10x.html"
      - title: 9.x
        url: "/nvme-rhel-9x.html"
      - title: 8.x
        url: "/nvme-rhel-8x.html"
    - title: Rocky Linux
      entries:
      - title: Suporte e recursos do ONTAP
        url: "/nvme-rockylinux-supported-features.html"
      - title: 10.x
        url: "/nvme-rockylinux-10x.html"
      - title: 9.x
        url: "/nvme-rockylinux-9x.html"
      - title: 8.x
        url: "/nvme-rockylinux-8x.html"
    - title: SUSE Linux Enterprise Server
      entries:
      - title: SUSE Linux Enterprise Server 15
        entries:
        - title: 15 SP7
          url: "/nvme_sles15_sp7.html"
        - title: 15 SP6
          url: "/nvme_sles15_sp6.html"
        - title: 15 SP5
          url: "/nvme_sles15_sp5.html"
        - title: 15 SP4
          url: "/nvme_sles15_sp4.html"
        - title: 15 SP3
          url: "/nvme_sles15_sp3.html"
        - title: 15 SP2
          url: "/nvme_sles15_sp2.html"
        - title: 15 SP1
          url: "/nvme_sles15_sp1.html"
    - title: Ubuntu
      entries:
      - title: '24,04'
        url: "/nvme_ubuntu_2404.html"
      - title: '22,04'
        url: "/nvme_ubuntu_2204.html"
    - title: Windows
      entries:
      - title: '2025'
        url: "/nvme-windows-2025.html"
      - title: '2022'
        url: "/nvme_windows_2022.html"
      - title: '2019'
        url: "/nvme_windows_2019.html"
      - title: '2016'
        url: "/nvme_windows_2016.html"
      - title: 2012 R2
        url: "/nvme_windows_2012r2.html"
    - title: Solucionar problemas
      url: "/troubleshoot.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
