= 
:allow-uri-read: 


. Se sua configuração de armazenamento incluir sincronização ativa do MetroCluster ou do SnapMirror , altere as configurações padrão:
+
[role="tabbed-block"]
====
.MetroCluster
--
Por padrão, o sistema operacional AIX impõe um tempo limite de E/S menor quando não há caminhos disponíveis para um LUN.  Isso pode ocorrer em configurações que incluem malha SAN de switch único e em configurações do MetroCluster que apresentam failovers não planejados.  Para obter informações adicionais e alterações recomendadas nas configurações padrão, consulte o artigo da Base de conhecimentolink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["Quais são as considerações de suporte ao host AIX em uma configuração do MetroCluster ?"^] .

--
.Sincronização ativa do SnapMirror
--
SnapMirror active sync é compatível com um host AIX. O comportamento de suporte varia conforme a versão do ONTAP:

** A partir do ONTAP 9.19.1, SnapMirror active sync é suportado na configuração Active/Active, permitindo operações de SnapMirror active sync sem interrupções. Consulte o artigo da Knowledge Base link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/SnapMirror_active_sync_support_for_AIX%3A_behavior_by_ONTAP_release_and_migration_guidance["SnapMirror active sync suporte para AIX: comportamento por release do ONTAP e orientações de migração"^].
** Para ONTAP 9.11.1 a 9.18.1, SnapMirror active sync é suportado na configuração ativo/em espera. Consulte o artigo da Knowledge Base link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Como configurar um host AIX para SnapMirror active sync no ONTAP 9.11.1 a 9.18.1"^].


--
====

