= 
:allow-uri-read: 


Certifique-se de que iSCSI esteja configurado corretamente para seu host.

.Sobre esta tarefa
Você executa as seguintes etapas no host iSCSI.

.Passos
. Verifique se o pacote do iniciador iSCSI (iscsi-initiator-utils) está instalado:
+
[source, cli]
----
rpm -qa | grep iscsi-initiator-utils
----
+
Você deverá ver uma saída semelhante ao exemplo a seguir:

+
[listing]
----
iscsi-initiator-utils-6.2.1.11-0.git4b3e853.el10.x86_64
----
. Verifique o nome do nó do iniciador iSCSI, que está localizado no  `/etc/iscsi/initiatorname.iscsi` arquivo:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configure o parâmetro de tempo limite da sessão iSCSI localizado no arquivo  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
O parâmetro  `replacement_timeout`iSCSI controla por quanto tempo a camada iSCSI deve esperar que um caminho ou sessão com tempo limite expirado se restabeleça antes de falhar quaisquer comandos nele. Você deve definir o valor de  `replacement_timeout`para 5 no arquivo de configuração iSCSI.

. Ative o serviço iSCSI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Inicie o serviço iSCSI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verifique se o serviço iSCSI está em execução:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
● iscsid.service - Open-iSCSI
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; enabled; preset: disabled)
     Active: active (running) since Tue 2026-4-18 11:36:21 EST; 1 weeks 1 day ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
             man:iscsiuio(8)
             man:iscsiadm(8)
   Main PID: 2263 (iscsid)
     Status: "Ready to process requests"
      Tasks: 1 (limit: 816061)
     Memory: 18.5M
        CPU: 14.480s
     CGroup: /system.slice/iscsid.service
             └─2263 /usr/sbin/iscsid -f -d2
----
====
. Descubra os alvos iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal 192.168.20.28
192.168.20.28:3260,1063 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15
192.168.20.29:3260,1061 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15
192.168.21.29:3260,1059 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15
192.168.21.28:3260,1057 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15
----
====
. Faça login nos destinos:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Defina o iSCSI para fazer login automaticamente quando o host for inicializado:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Substitua  `<target_name>` pelo nome do alvo ao qual você deseja fazer login automaticamente quando o host for inicializado. Substitua  `<ip:port>` pelo endereço IP e número da porta do alvo. Por exemplo:

+
[source, cli]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15 -p 192.168.20.28:3260 -o update -n node.startup -v automatic
----
. Verifique as sessões iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Mostrar exemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.20.28:3260,1063 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15 (non-flash)
tcp: [2] 192.168.20.29:3260,1061 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15 (non-flash)
tcp: [3] 192.168.21.28:3260,1057 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15 (non-flash)
tcp: [4] 192.168.21.29:3260,1059 iqn.1992-08.com.netapp:sn.08818e1f130811f1b8b4d039eac0cc5b:vs.15 (non-flash)
----
====

